// Code generated by ent, DO NOT EDIT.

package observabilitypayload

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the observabilitypayload type in the database.
	Label = "observability_payload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldSha256 holds the string denoting the sha256 field in the database.
	FieldSha256 = "sha256"
	// FieldByteLength holds the string denoting the byte_length field in the database.
	FieldByteLength = "byte_length"
	// FieldChargedBytes holds the string denoting the charged_bytes field in the database.
	FieldChargedBytes = "charged_bytes"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// EdgeRequest holds the string denoting the request edge name in mutations.
	EdgeRequest = "request"
	// EdgeRequestBodyRequests holds the string denoting the request_body_requests edge name in mutations.
	EdgeRequestBodyRequests = "request_body_requests"
	// EdgeRequestBodyExecutions holds the string denoting the request_body_executions edge name in mutations.
	EdgeRequestBodyExecutions = "request_body_executions"
	// Table holds the table name of the observabilitypayload in the database.
	Table = "observability_payloads"
	// RequestTable is the table that holds the request relation/edge.
	RequestTable = "observability_payloads"
	// RequestInverseTable is the table name for the Request entity.
	// It exists in this package in order to avoid circular dependency with the "request" package.
	RequestInverseTable = "requests"
	// RequestColumn is the table column denoting the request relation/edge.
	RequestColumn = "request_id"
	// RequestBodyRequestsTable is the table that holds the request_body_requests relation/edge.
	RequestBodyRequestsTable = "requests"
	// RequestBodyRequestsInverseTable is the table name for the Request entity.
	// It exists in this package in order to avoid circular dependency with the "request" package.
	RequestBodyRequestsInverseTable = "requests"
	// RequestBodyRequestsColumn is the table column denoting the request_body_requests relation/edge.
	RequestBodyRequestsColumn = "request_body_payload_id"
	// RequestBodyExecutionsTable is the table that holds the request_body_executions relation/edge.
	RequestBodyExecutionsTable = "request_executions"
	// RequestBodyExecutionsInverseTable is the table name for the RequestExecution entity.
	// It exists in this package in order to avoid circular dependency with the "requestexecution" package.
	RequestBodyExecutionsInverseTable = "request_executions"
	// RequestBodyExecutionsColumn is the table column denoting the request_body_executions relation/edge.
	RequestBodyExecutionsColumn = "request_body_payload_id"
)

// Columns holds all SQL columns for observabilitypayload fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRequestID,
	FieldKind,
	FieldSha256,
	FieldByteLength,
	FieldChargedBytes,
	FieldData,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	Sha256Validator func(string) error
	// ByteLengthValidator is a validator for the "byte_length" field. It is called by the builders before save.
	ByteLengthValidator func(int64) error
	// ChargedBytesValidator is a validator for the "charged_bytes" field. It is called by the builders before save.
	ChargedBytesValidator func(int64) error
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindRequestBody Kind = "request_body"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindRequestBody:
		return nil
	default:
		return fmt.Errorf("observabilitypayload: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the ObservabilityPayload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// BySha256 orders the results by the sha256 field.
func BySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSha256, opts...).ToFunc()
}

// ByByteLength orders the results by the byte_length field.
func ByByteLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldByteLength, opts...).ToFunc()
}

// ByChargedBytes orders the results by the charged_bytes field.
func ByChargedBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChargedBytes, opts...).ToFunc()
}

// ByRequestField orders the results by request field.
func ByRequestField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestStep(), sql.OrderByField(field, opts...))
	}
}

// ByRequestBodyRequestsCount orders the results by request_body_requests count.
func ByRequestBodyRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRequestBodyRequestsStep(), opts...)
	}
}

// ByRequestBodyRequests orders the results by request_body_requests terms.
func ByRequestBodyRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestBodyRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRequestBodyExecutionsCount orders the results by request_body_executions count.
func ByRequestBodyExecutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRequestBodyExecutionsStep(), opts...)
	}
}

// ByRequestBodyExecutions orders the results by request_body_executions terms.
func ByRequestBodyExecutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestBodyExecutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRequestStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RequestTable, RequestColumn),
	)
}
func newRequestBodyRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestBodyRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, RequestBodyRequestsTable, RequestBodyRequestsColumn),
	)
}
func newRequestBodyExecutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestBodyExecutionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, RequestBodyExecutionsTable, RequestBodyExecutionsColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Kind) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Kind) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Kind(str)
	if err := KindValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Kind", str)
	}
	return nil
}
