// Code generated by ent, DO NOT EDIT.

package observabilitypayload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldRequestID, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldSha256, v))
}

// ByteLength applies equality check predicate on the "byte_length" field. It's identical to ByteLengthEQ.
func ByteLength(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldByteLength, v))
}

// ChargedBytes applies equality check predicate on the "charged_bytes" field. It's identical to ChargedBytesEQ.
func ChargedBytes(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldChargedBytes, v))
}

// Data applies equality check predicate on the "data" field. It's identical to DataEQ.
func Data(v []byte) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldData, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLTE(FieldUpdatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...int) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNotIn(FieldRequestID, vs...))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNotIn(FieldKind, vs...))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldContainsFold(FieldSha256, v))
}

// ByteLengthEQ applies the EQ predicate on the "byte_length" field.
func ByteLengthEQ(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldByteLength, v))
}

// ByteLengthNEQ applies the NEQ predicate on the "byte_length" field.
func ByteLengthNEQ(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNEQ(FieldByteLength, v))
}

// ByteLengthIn applies the In predicate on the "byte_length" field.
func ByteLengthIn(vs ...int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldIn(FieldByteLength, vs...))
}

// ByteLengthNotIn applies the NotIn predicate on the "byte_length" field.
func ByteLengthNotIn(vs ...int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNotIn(FieldByteLength, vs...))
}

// ByteLengthGT applies the GT predicate on the "byte_length" field.
func ByteLengthGT(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGT(FieldByteLength, v))
}

// ByteLengthGTE applies the GTE predicate on the "byte_length" field.
func ByteLengthGTE(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGTE(FieldByteLength, v))
}

// ByteLengthLT applies the LT predicate on the "byte_length" field.
func ByteLengthLT(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLT(FieldByteLength, v))
}

// ByteLengthLTE applies the LTE predicate on the "byte_length" field.
func ByteLengthLTE(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLTE(FieldByteLength, v))
}

// ChargedBytesEQ applies the EQ predicate on the "charged_bytes" field.
func ChargedBytesEQ(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldChargedBytes, v))
}

// ChargedBytesNEQ applies the NEQ predicate on the "charged_bytes" field.
func ChargedBytesNEQ(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNEQ(FieldChargedBytes, v))
}

// ChargedBytesIn applies the In predicate on the "charged_bytes" field.
func ChargedBytesIn(vs ...int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldIn(FieldChargedBytes, vs...))
}

// ChargedBytesNotIn applies the NotIn predicate on the "charged_bytes" field.
func ChargedBytesNotIn(vs ...int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNotIn(FieldChargedBytes, vs...))
}

// ChargedBytesGT applies the GT predicate on the "charged_bytes" field.
func ChargedBytesGT(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGT(FieldChargedBytes, v))
}

// ChargedBytesGTE applies the GTE predicate on the "charged_bytes" field.
func ChargedBytesGTE(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGTE(FieldChargedBytes, v))
}

// ChargedBytesLT applies the LT predicate on the "charged_bytes" field.
func ChargedBytesLT(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLT(FieldChargedBytes, v))
}

// ChargedBytesLTE applies the LTE predicate on the "charged_bytes" field.
func ChargedBytesLTE(v int64) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLTE(FieldChargedBytes, v))
}

// DataEQ applies the EQ predicate on the "data" field.
func DataEQ(v []byte) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldEQ(FieldData, v))
}

// DataNEQ applies the NEQ predicate on the "data" field.
func DataNEQ(v []byte) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNEQ(FieldData, v))
}

// DataIn applies the In predicate on the "data" field.
func DataIn(vs ...[]byte) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldIn(FieldData, vs...))
}

// DataNotIn applies the NotIn predicate on the "data" field.
func DataNotIn(vs ...[]byte) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldNotIn(FieldData, vs...))
}

// DataGT applies the GT predicate on the "data" field.
func DataGT(v []byte) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGT(FieldData, v))
}

// DataGTE applies the GTE predicate on the "data" field.
func DataGTE(v []byte) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldGTE(FieldData, v))
}

// DataLT applies the LT predicate on the "data" field.
func DataLT(v []byte) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLT(FieldData, v))
}

// DataLTE applies the LTE predicate on the "data" field.
func DataLTE(v []byte) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.FieldLTE(FieldData, v))
}

// HasRequest applies the HasEdge predicate on the "request" edge.
func HasRequest() predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RequestTable, RequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestWith applies the HasEdge predicate on the "request" edge with a given conditions (other predicates).
func HasRequestWith(preds ...predicate.Request) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(func(s *sql.Selector) {
		step := newRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRequestBodyRequests applies the HasEdge predicate on the "request_body_requests" edge.
func HasRequestBodyRequests() predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, RequestBodyRequestsTable, RequestBodyRequestsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestBodyRequestsWith applies the HasEdge predicate on the "request_body_requests" edge with a given conditions (other predicates).
func HasRequestBodyRequestsWith(preds ...predicate.Request) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(func(s *sql.Selector) {
		step := newRequestBodyRequestsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRequestBodyExecutions applies the HasEdge predicate on the "request_body_executions" edge.
func HasRequestBodyExecutions() predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, RequestBodyExecutionsTable, RequestBodyExecutionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestBodyExecutionsWith applies the HasEdge predicate on the "request_body_executions" edge with a given conditions (other predicates).
func HasRequestBodyExecutionsWith(preds ...predicate.RequestExecution) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(func(s *sql.Selector) {
		step := newRequestBodyExecutionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ObservabilityPayload) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ObservabilityPayload) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ObservabilityPayload) predicate.ObservabilityPayload {
	return predicate.ObservabilityPayload(sql.NotPredicates(p))
}
