// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplate"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplaterevision"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/objects"
)

// APIKeyProfileTemplateRevisionCreate is the builder for creating a APIKeyProfileTemplateRevision entity.
type APIKeyProfileTemplateRevisionCreate struct {
	config
	mutation *APIKeyProfileTemplateRevisionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyProfileTemplateRevisionCreate) SetCreatedAt(v time.Time) *APIKeyProfileTemplateRevisionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIKeyProfileTemplateRevisionCreate) SetNillableCreatedAt(v *time.Time) *APIKeyProfileTemplateRevisionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIKeyProfileTemplateRevisionCreate) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateRevisionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIKeyProfileTemplateRevisionCreate) SetNillableUpdatedAt(v *time.Time) *APIKeyProfileTemplateRevisionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *APIKeyProfileTemplateRevisionCreate) SetProjectID(v int) *APIKeyProfileTemplateRevisionCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *APIKeyProfileTemplateRevisionCreate) SetTemplateID(v int) *APIKeyProfileTemplateRevisionCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetRevision sets the "revision" field.
func (_c *APIKeyProfileTemplateRevisionCreate) SetRevision(v int64) *APIKeyProfileTemplateRevisionCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetName sets the "name" field.
func (_c *APIKeyProfileTemplateRevisionCreate) SetName(v string) *APIKeyProfileTemplateRevisionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *APIKeyProfileTemplateRevisionCreate) SetDescription(v string) *APIKeyProfileTemplateRevisionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *APIKeyProfileTemplateRevisionCreate) SetNillableDescription(v *string) *APIKeyProfileTemplateRevisionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetProfile sets the "profile" field.
func (_c *APIKeyProfileTemplateRevisionCreate) SetProfile(v *objects.APIKeyProfile) *APIKeyProfileTemplateRevisionCreate {
	_c.mutation.SetProfile(v)
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *APIKeyProfileTemplateRevisionCreate) SetCreatedByUserID(v int) *APIKeyProfileTemplateRevisionCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_c *APIKeyProfileTemplateRevisionCreate) SetNillableCreatedByUserID(v *int) *APIKeyProfileTemplateRevisionCreate {
	if v != nil {
		_c.SetCreatedByUserID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *APIKeyProfileTemplateRevisionCreate) SetProject(v *Project) *APIKeyProfileTemplateRevisionCreate {
	return _c.SetProjectID(v.ID)
}

// SetTemplate sets the "template" edge to the APIKeyProfileTemplate entity.
func (_c *APIKeyProfileTemplateRevisionCreate) SetTemplate(v *APIKeyProfileTemplate) *APIKeyProfileTemplateRevisionCreate {
	return _c.SetTemplateID(v.ID)
}

// Mutation returns the APIKeyProfileTemplateRevisionMutation object of the builder.
func (_c *APIKeyProfileTemplateRevisionCreate) Mutation() *APIKeyProfileTemplateRevisionMutation {
	return _c.mutation
}

// Save creates the APIKeyProfileTemplateRevision in the database.
func (_c *APIKeyProfileTemplateRevisionCreate) Save(ctx context.Context) (*APIKeyProfileTemplateRevision, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyProfileTemplateRevisionCreate) SaveX(ctx context.Context) *APIKeyProfileTemplateRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyProfileTemplateRevisionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyProfileTemplateRevisionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeyProfileTemplateRevisionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if apikeyprofiletemplaterevision.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikeyprofiletemplaterevision.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := apikeyprofiletemplaterevision.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if apikeyprofiletemplaterevision.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikeyprofiletemplaterevision.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := apikeyprofiletemplaterevision.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := apikeyprofiletemplaterevision.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyProfileTemplateRevisionCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "APIKeyProfileTemplateRevision.project_id"`)}
	}
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "APIKeyProfileTemplateRevision.template_id"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "APIKeyProfileTemplateRevision.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := apikeyprofiletemplaterevision.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "APIKeyProfileTemplateRevision.revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "APIKeyProfileTemplateRevision.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "APIKeyProfileTemplateRevision.description"`)}
	}
	if _, ok := _c.mutation.Profile(); !ok {
		return &ValidationError{Name: "profile", err: errors.New(`ent: missing required field "APIKeyProfileTemplateRevision.profile"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "APIKeyProfileTemplateRevision.project"`)}
	}
	if len(_c.mutation.TemplateIDs()) == 0 {
		return &ValidationError{Name: "template", err: errors.New(`ent: missing required edge "APIKeyProfileTemplateRevision.template"`)}
	}
	return nil
}

func (_c *APIKeyProfileTemplateRevisionCreate) sqlSave(ctx context.Context) (*APIKeyProfileTemplateRevision, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyProfileTemplateRevisionCreate) createSpec() (*APIKeyProfileTemplateRevision, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeyProfileTemplateRevision{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeyprofiletemplaterevision.Table, sqlgraph.NewFieldSpec(apikeyprofiletemplaterevision.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeyprofiletemplaterevision.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyprofiletemplaterevision.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(apikeyprofiletemplaterevision.FieldRevision, field.TypeInt64, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(apikeyprofiletemplaterevision.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(apikeyprofiletemplaterevision.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Profile(); ok {
		_spec.SetField(apikeyprofiletemplaterevision.FieldProfile, field.TypeJSON, value)
		_node.Profile = value
	}
	if value, ok := _c.mutation.CreatedByUserID(); ok {
		_spec.SetField(apikeyprofiletemplaterevision.FieldCreatedByUserID, field.TypeInt, value)
		_node.CreatedByUserID = &value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyprofiletemplaterevision.ProjectTable,
			Columns: []string{apikeyprofiletemplaterevision.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyprofiletemplaterevision.TemplateTable,
			Columns: []string{apikeyprofiletemplaterevision.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeyprofiletemplate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TemplateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyProfileTemplateRevision.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyProfileTemplateRevisionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyProfileTemplateRevisionCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyProfileTemplateRevisionUpsertOne {
	_c.conflict = opts
	return &APIKeyProfileTemplateRevisionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplateRevision.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyProfileTemplateRevisionCreate) OnConflictColumns(columns ...string) *APIKeyProfileTemplateRevisionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyProfileTemplateRevisionUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyProfileTemplateRevisionUpsertOne is the builder for "upsert"-ing
	//  one APIKeyProfileTemplateRevision node.
	APIKeyProfileTemplateRevisionUpsertOne struct {
		create *APIKeyProfileTemplateRevisionCreate
	}

	// APIKeyProfileTemplateRevisionUpsert is the "OnConflict" setter.
	APIKeyProfileTemplateRevisionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyProfileTemplateRevisionUpsert) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateRevisionUpsert {
	u.Set(apikeyprofiletemplaterevision.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyProfileTemplateRevisionUpsert) UpdateUpdatedAt() *APIKeyProfileTemplateRevisionUpsert {
	u.SetExcluded(apikeyprofiletemplaterevision.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplateRevision.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyProfileTemplateRevisionUpsertOne) UpdateNewValues() *APIKeyProfileTemplateRevisionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeyprofiletemplaterevision.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ProjectID(); exists {
			s.SetIgnore(apikeyprofiletemplaterevision.FieldProjectID)
		}
		if _, exists := u.create.mutation.TemplateID(); exists {
			s.SetIgnore(apikeyprofiletemplaterevision.FieldTemplateID)
		}
		if _, exists := u.create.mutation.Revision(); exists {
			s.SetIgnore(apikeyprofiletemplaterevision.FieldRevision)
		}
		if _, exists := u.create.mutation.Name(); exists {
			s.SetIgnore(apikeyprofiletemplaterevision.FieldName)
		}
		if _, exists := u.create.mutation.Description(); exists {
			s.SetIgnore(apikeyprofiletemplaterevision.FieldDescription)
		}
		if _, exists := u.create.mutation.Profile(); exists {
			s.SetIgnore(apikeyprofiletemplaterevision.FieldProfile)
		}
		if _, exists := u.create.mutation.CreatedByUserID(); exists {
			s.SetIgnore(apikeyprofiletemplaterevision.FieldCreatedByUserID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplateRevision.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyProfileTemplateRevisionUpsertOne) Ignore() *APIKeyProfileTemplateRevisionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyProfileTemplateRevisionUpsertOne) DoNothing() *APIKeyProfileTemplateRevisionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyProfileTemplateRevisionCreate.OnConflict
// documentation for more info.
func (u *APIKeyProfileTemplateRevisionUpsertOne) Update(set func(*APIKeyProfileTemplateRevisionUpsert)) *APIKeyProfileTemplateRevisionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyProfileTemplateRevisionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyProfileTemplateRevisionUpsertOne) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateRevisionUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateRevisionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyProfileTemplateRevisionUpsertOne) UpdateUpdatedAt() *APIKeyProfileTemplateRevisionUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateRevisionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *APIKeyProfileTemplateRevisionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyProfileTemplateRevisionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyProfileTemplateRevisionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyProfileTemplateRevisionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyProfileTemplateRevisionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyProfileTemplateRevisionCreateBulk is the builder for creating many APIKeyProfileTemplateRevision entities in bulk.
type APIKeyProfileTemplateRevisionCreateBulk struct {
	config
	err      error
	builders []*APIKeyProfileTemplateRevisionCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeyProfileTemplateRevision entities in the database.
func (_c *APIKeyProfileTemplateRevisionCreateBulk) Save(ctx context.Context) ([]*APIKeyProfileTemplateRevision, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeyProfileTemplateRevision, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyProfileTemplateRevisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyProfileTemplateRevisionCreateBulk) SaveX(ctx context.Context) []*APIKeyProfileTemplateRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyProfileTemplateRevisionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyProfileTemplateRevisionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyProfileTemplateRevision.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyProfileTemplateRevisionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyProfileTemplateRevisionCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyProfileTemplateRevisionUpsertBulk {
	_c.conflict = opts
	return &APIKeyProfileTemplateRevisionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplateRevision.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyProfileTemplateRevisionCreateBulk) OnConflictColumns(columns ...string) *APIKeyProfileTemplateRevisionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyProfileTemplateRevisionUpsertBulk{
		create: _c,
	}
}

// APIKeyProfileTemplateRevisionUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeyProfileTemplateRevision nodes.
type APIKeyProfileTemplateRevisionUpsertBulk struct {
	create *APIKeyProfileTemplateRevisionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplateRevision.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyProfileTemplateRevisionUpsertBulk) UpdateNewValues() *APIKeyProfileTemplateRevisionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeyprofiletemplaterevision.FieldCreatedAt)
			}
			if _, exists := b.mutation.ProjectID(); exists {
				s.SetIgnore(apikeyprofiletemplaterevision.FieldProjectID)
			}
			if _, exists := b.mutation.TemplateID(); exists {
				s.SetIgnore(apikeyprofiletemplaterevision.FieldTemplateID)
			}
			if _, exists := b.mutation.Revision(); exists {
				s.SetIgnore(apikeyprofiletemplaterevision.FieldRevision)
			}
			if _, exists := b.mutation.Name(); exists {
				s.SetIgnore(apikeyprofiletemplaterevision.FieldName)
			}
			if _, exists := b.mutation.Description(); exists {
				s.SetIgnore(apikeyprofiletemplaterevision.FieldDescription)
			}
			if _, exists := b.mutation.Profile(); exists {
				s.SetIgnore(apikeyprofiletemplaterevision.FieldProfile)
			}
			if _, exists := b.mutation.CreatedByUserID(); exists {
				s.SetIgnore(apikeyprofiletemplaterevision.FieldCreatedByUserID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplateRevision.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyProfileTemplateRevisionUpsertBulk) Ignore() *APIKeyProfileTemplateRevisionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyProfileTemplateRevisionUpsertBulk) DoNothing() *APIKeyProfileTemplateRevisionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyProfileTemplateRevisionCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyProfileTemplateRevisionUpsertBulk) Update(set func(*APIKeyProfileTemplateRevisionUpsert)) *APIKeyProfileTemplateRevisionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyProfileTemplateRevisionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyProfileTemplateRevisionUpsertBulk) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateRevisionUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateRevisionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyProfileTemplateRevisionUpsertBulk) UpdateUpdatedAt() *APIKeyProfileTemplateRevisionUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateRevisionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *APIKeyProfileTemplateRevisionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyProfileTemplateRevisionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyProfileTemplateRevisionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyProfileTemplateRevisionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
