// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplaterevision"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// APIKeyProfileTemplateRevisionUpdate is the builder for updating APIKeyProfileTemplateRevision entities.
type APIKeyProfileTemplateRevisionUpdate struct {
	config
	hooks     []Hook
	mutation  *APIKeyProfileTemplateRevisionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the APIKeyProfileTemplateRevisionUpdate builder.
func (_u *APIKeyProfileTemplateRevisionUpdate) Where(ps ...predicate.APIKeyProfileTemplateRevision) *APIKeyProfileTemplateRevisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyProfileTemplateRevisionUpdate) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateRevisionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the APIKeyProfileTemplateRevisionMutation object of the builder.
func (_u *APIKeyProfileTemplateRevisionUpdate) Mutation() *APIKeyProfileTemplateRevisionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyProfileTemplateRevisionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyProfileTemplateRevisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyProfileTemplateRevisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyProfileTemplateRevisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyProfileTemplateRevisionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if apikeyprofiletemplaterevision.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikeyprofiletemplaterevision.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := apikeyprofiletemplaterevision.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyProfileTemplateRevisionUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyProfileTemplateRevision.project"`)
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyProfileTemplateRevision.template"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *APIKeyProfileTemplateRevisionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *APIKeyProfileTemplateRevisionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *APIKeyProfileTemplateRevisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyprofiletemplaterevision.Table, apikeyprofiletemplaterevision.Columns, sqlgraph.NewFieldSpec(apikeyprofiletemplaterevision.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyprofiletemplaterevision.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByUserIDCleared() {
		_spec.ClearField(apikeyprofiletemplaterevision.FieldCreatedByUserID, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyprofiletemplaterevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyProfileTemplateRevisionUpdateOne is the builder for updating a single APIKeyProfileTemplateRevision entity.
type APIKeyProfileTemplateRevisionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *APIKeyProfileTemplateRevisionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateRevisionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the APIKeyProfileTemplateRevisionMutation object of the builder.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) Mutation() *APIKeyProfileTemplateRevisionMutation {
	return _u.mutation
}

// Where appends a list predicates to the APIKeyProfileTemplateRevisionUpdate builder.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) Where(ps ...predicate.APIKeyProfileTemplateRevision) *APIKeyProfileTemplateRevisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) Select(field string, fields ...string) *APIKeyProfileTemplateRevisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeyProfileTemplateRevision entity.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) Save(ctx context.Context) (*APIKeyProfileTemplateRevision, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) SaveX(ctx context.Context) *APIKeyProfileTemplateRevision {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if apikeyprofiletemplaterevision.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikeyprofiletemplaterevision.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := apikeyprofiletemplaterevision.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyProfileTemplateRevision.project"`)
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyProfileTemplateRevision.template"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *APIKeyProfileTemplateRevisionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *APIKeyProfileTemplateRevisionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *APIKeyProfileTemplateRevisionUpdateOne) sqlSave(ctx context.Context) (_node *APIKeyProfileTemplateRevision, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyprofiletemplaterevision.Table, apikeyprofiletemplaterevision.Columns, sqlgraph.NewFieldSpec(apikeyprofiletemplaterevision.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeyProfileTemplateRevision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeyprofiletemplaterevision.FieldID)
		for _, f := range fields {
			if !apikeyprofiletemplaterevision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeyprofiletemplaterevision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyprofiletemplaterevision.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByUserIDCleared() {
		_spec.ClearField(apikeyprofiletemplaterevision.FieldCreatedByUserID, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &APIKeyProfileTemplateRevision{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyprofiletemplaterevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
