// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplate"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/objects"
)

// APIKeyProfileTemplate is the model entity for the APIKeyProfileTemplate schema.
type APIKeyProfileTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Template name
	Name string `json:"name,omitempty"`
	// Template description
	Description string `json:"description,omitempty"`
	// Project ID, set via project edge
	ProjectID int `json:"project_id,omitempty"`
	// Profile holds the value of the "profile" field.
	Profile *objects.APIKeyProfile `json:"profile,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int64 `json:"revision,omitempty"`
	// SelfServiceVisible holds the value of the "self_service_visible" field.
	SelfServiceVisible bool `json:"self_service_visible,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the APIKeyProfileTemplateQuery when eager-loading is set.
	Edges        APIKeyProfileTemplateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// APIKeyProfileTemplateEdges holds the relations/edges for other nodes in the graph.
type APIKeyProfileTemplateEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// Revisions holds the value of the revisions edge.
	Revisions []*APIKeyProfileTemplateRevision `json:"revisions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedAPIKeys   map[string][]*APIKey
	namedRevisions map[string][]*APIKeyProfileTemplateRevision
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyProfileTemplateEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e APIKeyProfileTemplateEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[1] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// RevisionsOrErr returns the Revisions value or an error if the edge
// was not loaded in eager-loading.
func (e APIKeyProfileTemplateEdges) RevisionsOrErr() ([]*APIKeyProfileTemplateRevision, error) {
	if e.loadedTypes[2] {
		return e.Revisions, nil
	}
	return nil, &NotLoadedError{edge: "revisions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*APIKeyProfileTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeyprofiletemplate.FieldProfile:
			values[i] = new([]byte)
		case apikeyprofiletemplate.FieldSelfServiceVisible:
			values[i] = new(sql.NullBool)
		case apikeyprofiletemplate.FieldID, apikeyprofiletemplate.FieldDeletedAt, apikeyprofiletemplate.FieldProjectID, apikeyprofiletemplate.FieldRevision:
			values[i] = new(sql.NullInt64)
		case apikeyprofiletemplate.FieldName, apikeyprofiletemplate.FieldDescription:
			values[i] = new(sql.NullString)
		case apikeyprofiletemplate.FieldCreatedAt, apikeyprofiletemplate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the APIKeyProfileTemplate fields.
func (_m *APIKeyProfileTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeyprofiletemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case apikeyprofiletemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikeyprofiletemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case apikeyprofiletemplate.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case apikeyprofiletemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case apikeyprofiletemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case apikeyprofiletemplate.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case apikeyprofiletemplate.FieldProfile:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field profile", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Profile); err != nil {
					return fmt.Errorf("unmarshal field profile: %w", err)
				}
			}
		case apikeyprofiletemplate.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.Int64
			}
		case apikeyprofiletemplate.FieldSelfServiceVisible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field self_service_visible", values[i])
			} else if value.Valid {
				_m.SelfServiceVisible = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the APIKeyProfileTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *APIKeyProfileTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the APIKeyProfileTemplate entity.
func (_m *APIKeyProfileTemplate) QueryProject() *ProjectQuery {
	return NewAPIKeyProfileTemplateClient(_m.config).QueryProject(_m)
}

// QueryAPIKeys queries the "api_keys" edge of the APIKeyProfileTemplate entity.
func (_m *APIKeyProfileTemplate) QueryAPIKeys() *APIKeyQuery {
	return NewAPIKeyProfileTemplateClient(_m.config).QueryAPIKeys(_m)
}

// QueryRevisions queries the "revisions" edge of the APIKeyProfileTemplate entity.
func (_m *APIKeyProfileTemplate) QueryRevisions() *APIKeyProfileTemplateRevisionQuery {
	return NewAPIKeyProfileTemplateClient(_m.config).QueryRevisions(_m)
}

// Update returns a builder for updating this APIKeyProfileTemplate.
// Note that you need to call APIKeyProfileTemplate.Unwrap() before calling this method if this APIKeyProfileTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *APIKeyProfileTemplate) Update() *APIKeyProfileTemplateUpdateOne {
	return NewAPIKeyProfileTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the APIKeyProfileTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *APIKeyProfileTemplate) Unwrap() *APIKeyProfileTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: APIKeyProfileTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *APIKeyProfileTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("APIKeyProfileTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("profile=")
	builder.WriteString(fmt.Sprintf("%v", _m.Profile))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("self_service_visible=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelfServiceVisible))
	builder.WriteByte(')')
	return builder.String()
}

// NamedAPIKeys returns the APIKeys named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *APIKeyProfileTemplate) NamedAPIKeys(name string) ([]*APIKey, error) {
	if _m.Edges.namedAPIKeys == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedAPIKeys[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *APIKeyProfileTemplate) appendNamedAPIKeys(name string, edges ...*APIKey) {
	if _m.Edges.namedAPIKeys == nil {
		_m.Edges.namedAPIKeys = make(map[string][]*APIKey)
	}
	if len(edges) == 0 {
		_m.Edges.namedAPIKeys[name] = []*APIKey{}
	} else {
		_m.Edges.namedAPIKeys[name] = append(_m.Edges.namedAPIKeys[name], edges...)
	}
}

// NamedRevisions returns the Revisions named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *APIKeyProfileTemplate) NamedRevisions(name string) ([]*APIKeyProfileTemplateRevision, error) {
	if _m.Edges.namedRevisions == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRevisions[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *APIKeyProfileTemplate) appendNamedRevisions(name string, edges ...*APIKeyProfileTemplateRevision) {
	if _m.Edges.namedRevisions == nil {
		_m.Edges.namedRevisions = make(map[string][]*APIKeyProfileTemplateRevision)
	}
	if len(edges) == 0 {
		_m.Edges.namedRevisions[name] = []*APIKeyProfileTemplateRevision{}
	} else {
		_m.Edges.namedRevisions[name] = append(_m.Edges.namedRevisions[name], edges...)
	}
}

// APIKeyProfileTemplates is a parsable slice of APIKeyProfileTemplate.
type APIKeyProfileTemplates []*APIKeyProfileTemplate
