// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplate"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplaterevision"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/objects"
)

// APIKeyProfileTemplateRevision is the model entity for the APIKeyProfileTemplateRevision schema.
type APIKeyProfileTemplateRevision struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int `json:"project_id,omitempty"`
	// TemplateID holds the value of the "template_id" field.
	TemplateID int `json:"template_id,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int64 `json:"revision,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Profile holds the value of the "profile" field.
	Profile *objects.APIKeyProfile `json:"profile,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID *int `json:"created_by_user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the APIKeyProfileTemplateRevisionQuery when eager-loading is set.
	Edges        APIKeyProfileTemplateRevisionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// APIKeyProfileTemplateRevisionEdges holds the relations/edges for other nodes in the graph.
type APIKeyProfileTemplateRevisionEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Template holds the value of the template edge.
	Template *APIKeyProfileTemplate `json:"template,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyProfileTemplateRevisionEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TemplateOrErr returns the Template value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyProfileTemplateRevisionEdges) TemplateOrErr() (*APIKeyProfileTemplate, error) {
	if e.Template != nil {
		return e.Template, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikeyprofiletemplate.Label}
	}
	return nil, &NotLoadedError{edge: "template"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*APIKeyProfileTemplateRevision) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeyprofiletemplaterevision.FieldProfile:
			values[i] = new([]byte)
		case apikeyprofiletemplaterevision.FieldID, apikeyprofiletemplaterevision.FieldProjectID, apikeyprofiletemplaterevision.FieldTemplateID, apikeyprofiletemplaterevision.FieldRevision, apikeyprofiletemplaterevision.FieldCreatedByUserID:
			values[i] = new(sql.NullInt64)
		case apikeyprofiletemplaterevision.FieldName, apikeyprofiletemplaterevision.FieldDescription:
			values[i] = new(sql.NullString)
		case apikeyprofiletemplaterevision.FieldCreatedAt, apikeyprofiletemplaterevision.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the APIKeyProfileTemplateRevision fields.
func (_m *APIKeyProfileTemplateRevision) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeyprofiletemplaterevision.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case apikeyprofiletemplaterevision.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikeyprofiletemplaterevision.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case apikeyprofiletemplaterevision.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case apikeyprofiletemplaterevision.FieldTemplateID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = int(value.Int64)
			}
		case apikeyprofiletemplaterevision.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.Int64
			}
		case apikeyprofiletemplaterevision.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case apikeyprofiletemplaterevision.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case apikeyprofiletemplaterevision.FieldProfile:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field profile", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Profile); err != nil {
					return fmt.Errorf("unmarshal field profile: %w", err)
				}
			}
		case apikeyprofiletemplaterevision.FieldCreatedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value.Valid {
				_m.CreatedByUserID = new(int)
				*_m.CreatedByUserID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the APIKeyProfileTemplateRevision.
// This includes values selected through modifiers, order, etc.
func (_m *APIKeyProfileTemplateRevision) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the APIKeyProfileTemplateRevision entity.
func (_m *APIKeyProfileTemplateRevision) QueryProject() *ProjectQuery {
	return NewAPIKeyProfileTemplateRevisionClient(_m.config).QueryProject(_m)
}

// QueryTemplate queries the "template" edge of the APIKeyProfileTemplateRevision entity.
func (_m *APIKeyProfileTemplateRevision) QueryTemplate() *APIKeyProfileTemplateQuery {
	return NewAPIKeyProfileTemplateRevisionClient(_m.config).QueryTemplate(_m)
}

// Update returns a builder for updating this APIKeyProfileTemplateRevision.
// Note that you need to call APIKeyProfileTemplateRevision.Unwrap() before calling this method if this APIKeyProfileTemplateRevision
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *APIKeyProfileTemplateRevision) Update() *APIKeyProfileTemplateRevisionUpdateOne {
	return NewAPIKeyProfileTemplateRevisionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the APIKeyProfileTemplateRevision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *APIKeyProfileTemplateRevision) Unwrap() *APIKeyProfileTemplateRevision {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: APIKeyProfileTemplateRevision is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *APIKeyProfileTemplateRevision) String() string {
	var builder strings.Builder
	builder.WriteString("APIKeyProfileTemplateRevision(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateID))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("profile=")
	builder.WriteString(fmt.Sprintf("%v", _m.Profile))
	builder.WriteString(", ")
	if v := _m.CreatedByUserID; v != nil {
		builder.WriteString("created_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// APIKeyProfileTemplateRevisions is a parsable slice of APIKeyProfileTemplateRevision.
type APIKeyProfileTemplateRevisions []*APIKeyProfileTemplateRevision
