// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelkeymonitoringevent"
	"github.com/looplj/axonhub/internal/objects"
)

// ChannelKeyMonitoringEventCreate is the builder for creating a ChannelKeyMonitoringEvent entity.
type ChannelKeyMonitoringEventCreate struct {
	config
	mutation *ChannelKeyMonitoringEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelKeyMonitoringEventCreate) SetCreatedAt(v time.Time) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableCreatedAt(v *time.Time) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelKeyMonitoringEventCreate) SetUpdatedAt(v time.Time) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableUpdatedAt(v *time.Time) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ChannelKeyMonitoringEventCreate) SetChannelID(v int) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetChannelName sets the "channel_name" field.
func (_c *ChannelKeyMonitoringEventCreate) SetChannelName(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetChannelName(v)
	return _c
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableChannelName(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetChannelName(*v)
	}
	return _c
}

// SetKeyID sets the "key_id" field.
func (_c *ChannelKeyMonitoringEventCreate) SetKeyID(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetKeyID(v)
	return _c
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableKeyID(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetKeyID(*v)
	}
	return _c
}

// SetMaskedKey sets the "masked_key" field.
func (_c *ChannelKeyMonitoringEventCreate) SetMaskedKey(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetMaskedKey(v)
	return _c
}

// SetNillableMaskedKey sets the "masked_key" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableMaskedKey(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetMaskedKey(*v)
	}
	return _c
}

// SetRuleID sets the "rule_id" field.
func (_c *ChannelKeyMonitoringEventCreate) SetRuleID(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetRuleID(v)
	return _c
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableRuleID(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetRuleID(*v)
	}
	return _c
}

// SetRuleName sets the "rule_name" field.
func (_c *ChannelKeyMonitoringEventCreate) SetRuleName(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetRuleName(v)
	return _c
}

// SetNillableRuleName sets the "rule_name" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableRuleName(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetRuleName(*v)
	}
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *ChannelKeyMonitoringEventCreate) SetTrigger(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableTrigger(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetTrigger(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *ChannelKeyMonitoringEventCreate) SetSource(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableSource(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *ChannelKeyMonitoringEventCreate) SetSuccess(v bool) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableSuccess(v *bool) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetSkipped sets the "skipped" field.
func (_c *ChannelKeyMonitoringEventCreate) SetSkipped(v bool) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetSkipped(v)
	return _c
}

// SetNillableSkipped sets the "skipped" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableSkipped(v *bool) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetSkipped(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *ChannelKeyMonitoringEventCreate) SetReason(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableReason(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *ChannelKeyMonitoringEventCreate) SetStatusCode(v int) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableStatusCode(v *int) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *ChannelKeyMonitoringEventCreate) SetBalance(v objects.JSONRawMessage) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ChannelKeyMonitoringEventCreate) SetCurrency(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableCurrency(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetAvailable sets the "available" field.
func (_c *ChannelKeyMonitoringEventCreate) SetAvailable(v bool) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetAvailable(v)
	return _c
}

// SetNillableAvailable sets the "available" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableAvailable(v *bool) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetAvailable(*v)
	}
	return _c
}

// SetProbe sets the "probe" field.
func (_c *ChannelKeyMonitoringEventCreate) SetProbe(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetProbe(v)
	return _c
}

// SetNillableProbe sets the "probe" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableProbe(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetProbe(*v)
	}
	return _c
}

// SetMatchedPolicy sets the "matched_policy" field.
func (_c *ChannelKeyMonitoringEventCreate) SetMatchedPolicy(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetMatchedPolicy(v)
	return _c
}

// SetNillableMatchedPolicy sets the "matched_policy" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableMatchedPolicy(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetMatchedPolicy(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *ChannelKeyMonitoringEventCreate) SetAction(v string) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableAction(v *string) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetNextCheckAt sets the "next_check_at" field.
func (_c *ChannelKeyMonitoringEventCreate) SetNextCheckAt(v time.Time) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetNextCheckAt(v)
	return _c
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableNextCheckAt(v *time.Time) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetNextCheckAt(*v)
	}
	return _c
}

// SetBackoffAttempt sets the "backoff_attempt" field.
func (_c *ChannelKeyMonitoringEventCreate) SetBackoffAttempt(v int) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetBackoffAttempt(v)
	return _c
}

// SetNillableBackoffAttempt sets the "backoff_attempt" field if the given value is not nil.
func (_c *ChannelKeyMonitoringEventCreate) SetNillableBackoffAttempt(v *int) *ChannelKeyMonitoringEventCreate {
	if v != nil {
		_c.SetBackoffAttempt(*v)
	}
	return _c
}

// SetCheckedAt sets the "checked_at" field.
func (_c *ChannelKeyMonitoringEventCreate) SetCheckedAt(v time.Time) *ChannelKeyMonitoringEventCreate {
	_c.mutation.SetCheckedAt(v)
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelKeyMonitoringEventCreate) SetChannel(v *Channel) *ChannelKeyMonitoringEventCreate {
	return _c.SetChannelID(v.ID)
}

// Mutation returns the ChannelKeyMonitoringEventMutation object of the builder.
func (_c *ChannelKeyMonitoringEventCreate) Mutation() *ChannelKeyMonitoringEventMutation {
	return _c.mutation
}

// Save creates the ChannelKeyMonitoringEvent in the database.
func (_c *ChannelKeyMonitoringEventCreate) Save(ctx context.Context) (*ChannelKeyMonitoringEvent, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelKeyMonitoringEventCreate) SaveX(ctx context.Context) *ChannelKeyMonitoringEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelKeyMonitoringEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelKeyMonitoringEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelKeyMonitoringEventCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if channelkeymonitoringevent.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelkeymonitoringevent.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := channelkeymonitoringevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if channelkeymonitoringevent.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelkeymonitoringevent.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelkeymonitoringevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		v := channelkeymonitoringevent.DefaultTrigger
		_c.mutation.SetTrigger(v)
	}
	if _, ok := _c.mutation.Success(); !ok {
		v := channelkeymonitoringevent.DefaultSuccess
		_c.mutation.SetSuccess(v)
	}
	if _, ok := _c.mutation.Skipped(); !ok {
		v := channelkeymonitoringevent.DefaultSkipped
		_c.mutation.SetSkipped(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelKeyMonitoringEventCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ChannelKeyMonitoringEvent.channel_id"`)}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "ChannelKeyMonitoringEvent.trigger"`)}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "ChannelKeyMonitoringEvent.success"`)}
	}
	if _, ok := _c.mutation.Skipped(); !ok {
		return &ValidationError{Name: "skipped", err: errors.New(`ent: missing required field "ChannelKeyMonitoringEvent.skipped"`)}
	}
	if _, ok := _c.mutation.CheckedAt(); !ok {
		return &ValidationError{Name: "checked_at", err: errors.New(`ent: missing required field "ChannelKeyMonitoringEvent.checked_at"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelKeyMonitoringEvent.channel"`)}
	}
	return nil
}

func (_c *ChannelKeyMonitoringEventCreate) sqlSave(ctx context.Context) (*ChannelKeyMonitoringEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelKeyMonitoringEventCreate) createSpec() (*ChannelKeyMonitoringEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelKeyMonitoringEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelkeymonitoringevent.Table, sqlgraph.NewFieldSpec(channelkeymonitoringevent.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ChannelName(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldChannelName, field.TypeString, value)
		_node.ChannelName = value
	}
	if value, ok := _c.mutation.KeyID(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldKeyID, field.TypeString, value)
		_node.KeyID = value
	}
	if value, ok := _c.mutation.MaskedKey(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldMaskedKey, field.TypeString, value)
		_node.MaskedKey = value
	}
	if value, ok := _c.mutation.RuleID(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldRuleID, field.TypeString, value)
		_node.RuleID = value
	}
	if value, ok := _c.mutation.RuleName(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldRuleName, field.TypeString, value)
		_node.RuleName = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldTrigger, field.TypeString, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.Skipped(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldSkipped, field.TypeBool, value)
		_node.Skipped = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = &value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldBalance, field.TypeJSON, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Available(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldAvailable, field.TypeBool, value)
		_node.Available = &value
	}
	if value, ok := _c.mutation.Probe(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldProbe, field.TypeString, value)
		_node.Probe = value
	}
	if value, ok := _c.mutation.MatchedPolicy(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldMatchedPolicy, field.TypeString, value)
		_node.MatchedPolicy = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.NextCheckAt(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldNextCheckAt, field.TypeTime, value)
		_node.NextCheckAt = &value
	}
	if value, ok := _c.mutation.BackoffAttempt(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldBackoffAttempt, field.TypeInt, value)
		_node.BackoffAttempt = value
	}
	if value, ok := _c.mutation.CheckedAt(); ok {
		_spec.SetField(channelkeymonitoringevent.FieldCheckedAt, field.TypeTime, value)
		_node.CheckedAt = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelkeymonitoringevent.ChannelTable,
			Columns: []string{channelkeymonitoringevent.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelKeyMonitoringEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelKeyMonitoringEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelKeyMonitoringEventCreate) OnConflict(opts ...sql.ConflictOption) *ChannelKeyMonitoringEventUpsertOne {
	_c.conflict = opts
	return &ChannelKeyMonitoringEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelKeyMonitoringEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelKeyMonitoringEventCreate) OnConflictColumns(columns ...string) *ChannelKeyMonitoringEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelKeyMonitoringEventUpsertOne{
		create: _c,
	}
}

type (
	// ChannelKeyMonitoringEventUpsertOne is the builder for "upsert"-ing
	//  one ChannelKeyMonitoringEvent node.
	ChannelKeyMonitoringEventUpsertOne struct {
		create *ChannelKeyMonitoringEventCreate
	}

	// ChannelKeyMonitoringEventUpsert is the "OnConflict" setter.
	ChannelKeyMonitoringEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelKeyMonitoringEventUpsert) SetUpdatedAt(v time.Time) *ChannelKeyMonitoringEventUpsert {
	u.Set(channelkeymonitoringevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelKeyMonitoringEventUpsert) UpdateUpdatedAt() *ChannelKeyMonitoringEventUpsert {
	u.SetExcluded(channelkeymonitoringevent.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelKeyMonitoringEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelKeyMonitoringEventUpsertOne) UpdateNewValues() *ChannelKeyMonitoringEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ChannelID(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldChannelID)
		}
		if _, exists := u.create.mutation.ChannelName(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldChannelName)
		}
		if _, exists := u.create.mutation.KeyID(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldKeyID)
		}
		if _, exists := u.create.mutation.MaskedKey(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldMaskedKey)
		}
		if _, exists := u.create.mutation.RuleID(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldRuleID)
		}
		if _, exists := u.create.mutation.RuleName(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldRuleName)
		}
		if _, exists := u.create.mutation.Trigger(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldTrigger)
		}
		if _, exists := u.create.mutation.Source(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldSource)
		}
		if _, exists := u.create.mutation.Success(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldSuccess)
		}
		if _, exists := u.create.mutation.Skipped(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldSkipped)
		}
		if _, exists := u.create.mutation.Reason(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldReason)
		}
		if _, exists := u.create.mutation.StatusCode(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldStatusCode)
		}
		if _, exists := u.create.mutation.Balance(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldBalance)
		}
		if _, exists := u.create.mutation.Currency(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldCurrency)
		}
		if _, exists := u.create.mutation.Available(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldAvailable)
		}
		if _, exists := u.create.mutation.Probe(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldProbe)
		}
		if _, exists := u.create.mutation.MatchedPolicy(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldMatchedPolicy)
		}
		if _, exists := u.create.mutation.Action(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldAction)
		}
		if _, exists := u.create.mutation.NextCheckAt(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldNextCheckAt)
		}
		if _, exists := u.create.mutation.BackoffAttempt(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldBackoffAttempt)
		}
		if _, exists := u.create.mutation.CheckedAt(); exists {
			s.SetIgnore(channelkeymonitoringevent.FieldCheckedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelKeyMonitoringEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelKeyMonitoringEventUpsertOne) Ignore() *ChannelKeyMonitoringEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelKeyMonitoringEventUpsertOne) DoNothing() *ChannelKeyMonitoringEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelKeyMonitoringEventCreate.OnConflict
// documentation for more info.
func (u *ChannelKeyMonitoringEventUpsertOne) Update(set func(*ChannelKeyMonitoringEventUpsert)) *ChannelKeyMonitoringEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelKeyMonitoringEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelKeyMonitoringEventUpsertOne) SetUpdatedAt(v time.Time) *ChannelKeyMonitoringEventUpsertOne {
	return u.Update(func(s *ChannelKeyMonitoringEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelKeyMonitoringEventUpsertOne) UpdateUpdatedAt() *ChannelKeyMonitoringEventUpsertOne {
	return u.Update(func(s *ChannelKeyMonitoringEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelKeyMonitoringEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelKeyMonitoringEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelKeyMonitoringEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelKeyMonitoringEventUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelKeyMonitoringEventUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelKeyMonitoringEventCreateBulk is the builder for creating many ChannelKeyMonitoringEvent entities in bulk.
type ChannelKeyMonitoringEventCreateBulk struct {
	config
	err      error
	builders []*ChannelKeyMonitoringEventCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelKeyMonitoringEvent entities in the database.
func (_c *ChannelKeyMonitoringEventCreateBulk) Save(ctx context.Context) ([]*ChannelKeyMonitoringEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelKeyMonitoringEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelKeyMonitoringEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelKeyMonitoringEventCreateBulk) SaveX(ctx context.Context) []*ChannelKeyMonitoringEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelKeyMonitoringEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelKeyMonitoringEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelKeyMonitoringEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelKeyMonitoringEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelKeyMonitoringEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelKeyMonitoringEventUpsertBulk {
	_c.conflict = opts
	return &ChannelKeyMonitoringEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelKeyMonitoringEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelKeyMonitoringEventCreateBulk) OnConflictColumns(columns ...string) *ChannelKeyMonitoringEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelKeyMonitoringEventUpsertBulk{
		create: _c,
	}
}

// ChannelKeyMonitoringEventUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelKeyMonitoringEvent nodes.
type ChannelKeyMonitoringEventUpsertBulk struct {
	create *ChannelKeyMonitoringEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelKeyMonitoringEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelKeyMonitoringEventUpsertBulk) UpdateNewValues() *ChannelKeyMonitoringEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldCreatedAt)
			}
			if _, exists := b.mutation.ChannelID(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldChannelID)
			}
			if _, exists := b.mutation.ChannelName(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldChannelName)
			}
			if _, exists := b.mutation.KeyID(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldKeyID)
			}
			if _, exists := b.mutation.MaskedKey(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldMaskedKey)
			}
			if _, exists := b.mutation.RuleID(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldRuleID)
			}
			if _, exists := b.mutation.RuleName(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldRuleName)
			}
			if _, exists := b.mutation.Trigger(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldTrigger)
			}
			if _, exists := b.mutation.Source(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldSource)
			}
			if _, exists := b.mutation.Success(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldSuccess)
			}
			if _, exists := b.mutation.Skipped(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldSkipped)
			}
			if _, exists := b.mutation.Reason(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldReason)
			}
			if _, exists := b.mutation.StatusCode(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldStatusCode)
			}
			if _, exists := b.mutation.Balance(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldBalance)
			}
			if _, exists := b.mutation.Currency(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldCurrency)
			}
			if _, exists := b.mutation.Available(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldAvailable)
			}
			if _, exists := b.mutation.Probe(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldProbe)
			}
			if _, exists := b.mutation.MatchedPolicy(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldMatchedPolicy)
			}
			if _, exists := b.mutation.Action(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldAction)
			}
			if _, exists := b.mutation.NextCheckAt(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldNextCheckAt)
			}
			if _, exists := b.mutation.BackoffAttempt(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldBackoffAttempt)
			}
			if _, exists := b.mutation.CheckedAt(); exists {
				s.SetIgnore(channelkeymonitoringevent.FieldCheckedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelKeyMonitoringEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelKeyMonitoringEventUpsertBulk) Ignore() *ChannelKeyMonitoringEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelKeyMonitoringEventUpsertBulk) DoNothing() *ChannelKeyMonitoringEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelKeyMonitoringEventCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelKeyMonitoringEventUpsertBulk) Update(set func(*ChannelKeyMonitoringEventUpsert)) *ChannelKeyMonitoringEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelKeyMonitoringEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelKeyMonitoringEventUpsertBulk) SetUpdatedAt(v time.Time) *ChannelKeyMonitoringEventUpsertBulk {
	return u.Update(func(s *ChannelKeyMonitoringEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelKeyMonitoringEventUpsertBulk) UpdateUpdatedAt() *ChannelKeyMonitoringEventUpsertBulk {
	return u.Update(func(s *ChannelKeyMonitoringEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelKeyMonitoringEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelKeyMonitoringEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelKeyMonitoringEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelKeyMonitoringEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
