// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channelkeymonitoringevent"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ChannelKeyMonitoringEventDelete is the builder for deleting a ChannelKeyMonitoringEvent entity.
type ChannelKeyMonitoringEventDelete struct {
	config
	hooks    []Hook
	mutation *ChannelKeyMonitoringEventMutation
}

// Where appends a list predicates to the ChannelKeyMonitoringEventDelete builder.
func (_d *ChannelKeyMonitoringEventDelete) Where(ps ...predicate.ChannelKeyMonitoringEvent) *ChannelKeyMonitoringEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChannelKeyMonitoringEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelKeyMonitoringEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChannelKeyMonitoringEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelkeymonitoringevent.Table, sqlgraph.NewFieldSpec(channelkeymonitoringevent.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChannelKeyMonitoringEventDeleteOne is the builder for deleting a single ChannelKeyMonitoringEvent entity.
type ChannelKeyMonitoringEventDeleteOne struct {
	_d *ChannelKeyMonitoringEventDelete
}

// Where appends a list predicates to the ChannelKeyMonitoringEventDelete builder.
func (_d *ChannelKeyMonitoringEventDeleteOne) Where(ps ...predicate.ChannelKeyMonitoringEvent) *ChannelKeyMonitoringEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChannelKeyMonitoringEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelkeymonitoringevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelKeyMonitoringEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
