// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelkeymonitoringevent"
	"github.com/looplj/axonhub/internal/objects"
)

// ChannelKeyMonitoringEvent is the model entity for the ChannelKeyMonitoringEvent schema.
type ChannelKeyMonitoringEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// ChannelName holds the value of the "channel_name" field.
	ChannelName string `json:"channel_name,omitempty"`
	// KeyID holds the value of the "key_id" field.
	KeyID string `json:"key_id,omitempty"`
	// MaskedKey holds the value of the "masked_key" field.
	MaskedKey string `json:"masked_key,omitempty"`
	// RuleID holds the value of the "rule_id" field.
	RuleID string `json:"rule_id,omitempty"`
	// RuleName holds the value of the "rule_name" field.
	RuleName string `json:"rule_name,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger string `json:"trigger,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Success holds the value of the "success" field.
	Success bool `json:"success,omitempty"`
	// Skipped holds the value of the "skipped" field.
	Skipped bool `json:"skipped,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode *int `json:"status_code,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance objects.JSONRawMessage `json:"balance,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Available holds the value of the "available" field.
	Available *bool `json:"available,omitempty"`
	// Probe holds the value of the "probe" field.
	Probe string `json:"probe,omitempty"`
	// MatchedPolicy holds the value of the "matched_policy" field.
	MatchedPolicy string `json:"matched_policy,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// NextCheckAt holds the value of the "next_check_at" field.
	NextCheckAt *time.Time `json:"next_check_at,omitempty"`
	// BackoffAttempt holds the value of the "backoff_attempt" field.
	BackoffAttempt int `json:"backoff_attempt,omitempty"`
	// CheckedAt holds the value of the "checked_at" field.
	CheckedAt time.Time `json:"checked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelKeyMonitoringEventQuery when eager-loading is set.
	Edges        ChannelKeyMonitoringEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChannelKeyMonitoringEventEdges holds the relations/edges for other nodes in the graph.
type ChannelKeyMonitoringEventEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelKeyMonitoringEventEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelKeyMonitoringEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelkeymonitoringevent.FieldBalance:
			values[i] = new([]byte)
		case channelkeymonitoringevent.FieldSuccess, channelkeymonitoringevent.FieldSkipped, channelkeymonitoringevent.FieldAvailable:
			values[i] = new(sql.NullBool)
		case channelkeymonitoringevent.FieldID, channelkeymonitoringevent.FieldChannelID, channelkeymonitoringevent.FieldStatusCode, channelkeymonitoringevent.FieldBackoffAttempt:
			values[i] = new(sql.NullInt64)
		case channelkeymonitoringevent.FieldChannelName, channelkeymonitoringevent.FieldKeyID, channelkeymonitoringevent.FieldMaskedKey, channelkeymonitoringevent.FieldRuleID, channelkeymonitoringevent.FieldRuleName, channelkeymonitoringevent.FieldTrigger, channelkeymonitoringevent.FieldSource, channelkeymonitoringevent.FieldReason, channelkeymonitoringevent.FieldCurrency, channelkeymonitoringevent.FieldProbe, channelkeymonitoringevent.FieldMatchedPolicy, channelkeymonitoringevent.FieldAction:
			values[i] = new(sql.NullString)
		case channelkeymonitoringevent.FieldCreatedAt, channelkeymonitoringevent.FieldUpdatedAt, channelkeymonitoringevent.FieldNextCheckAt, channelkeymonitoringevent.FieldCheckedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelKeyMonitoringEvent fields.
func (_m *ChannelKeyMonitoringEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelkeymonitoringevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case channelkeymonitoringevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelkeymonitoringevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case channelkeymonitoringevent.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case channelkeymonitoringevent.FieldChannelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_name", values[i])
			} else if value.Valid {
				_m.ChannelName = value.String
			}
		case channelkeymonitoringevent.FieldKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_id", values[i])
			} else if value.Valid {
				_m.KeyID = value.String
			}
		case channelkeymonitoringevent.FieldMaskedKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field masked_key", values[i])
			} else if value.Valid {
				_m.MaskedKey = value.String
			}
		case channelkeymonitoringevent.FieldRuleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = value.String
			}
		case channelkeymonitoringevent.FieldRuleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_name", values[i])
			} else if value.Valid {
				_m.RuleName = value.String
			}
		case channelkeymonitoringevent.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				_m.Trigger = value.String
			}
		case channelkeymonitoringevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case channelkeymonitoringevent.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		case channelkeymonitoringevent.FieldSkipped:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field skipped", values[i])
			} else if value.Valid {
				_m.Skipped = value.Bool
			}
		case channelkeymonitoringevent.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case channelkeymonitoringevent.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = new(int)
				*_m.StatusCode = int(value.Int64)
			}
		case channelkeymonitoringevent.FieldBalance:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Balance); err != nil {
					return fmt.Errorf("unmarshal field balance: %w", err)
				}
			}
		case channelkeymonitoringevent.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case channelkeymonitoringevent.FieldAvailable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field available", values[i])
			} else if value.Valid {
				_m.Available = new(bool)
				*_m.Available = value.Bool
			}
		case channelkeymonitoringevent.FieldProbe:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field probe", values[i])
			} else if value.Valid {
				_m.Probe = value.String
			}
		case channelkeymonitoringevent.FieldMatchedPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field matched_policy", values[i])
			} else if value.Valid {
				_m.MatchedPolicy = value.String
			}
		case channelkeymonitoringevent.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case channelkeymonitoringevent.FieldNextCheckAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_check_at", values[i])
			} else if value.Valid {
				_m.NextCheckAt = new(time.Time)
				*_m.NextCheckAt = value.Time
			}
		case channelkeymonitoringevent.FieldBackoffAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field backoff_attempt", values[i])
			} else if value.Valid {
				_m.BackoffAttempt = int(value.Int64)
			}
		case channelkeymonitoringevent.FieldCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_at", values[i])
			} else if value.Valid {
				_m.CheckedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelKeyMonitoringEvent.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelKeyMonitoringEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ChannelKeyMonitoringEvent entity.
func (_m *ChannelKeyMonitoringEvent) QueryChannel() *ChannelQuery {
	return NewChannelKeyMonitoringEventClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this ChannelKeyMonitoringEvent.
// Note that you need to call ChannelKeyMonitoringEvent.Unwrap() before calling this method if this ChannelKeyMonitoringEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelKeyMonitoringEvent) Update() *ChannelKeyMonitoringEventUpdateOne {
	return NewChannelKeyMonitoringEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelKeyMonitoringEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelKeyMonitoringEvent) Unwrap() *ChannelKeyMonitoringEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelKeyMonitoringEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelKeyMonitoringEvent) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelKeyMonitoringEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("channel_name=")
	builder.WriteString(_m.ChannelName)
	builder.WriteString(", ")
	builder.WriteString("key_id=")
	builder.WriteString(_m.KeyID)
	builder.WriteString(", ")
	builder.WriteString("masked_key=")
	builder.WriteString(_m.MaskedKey)
	builder.WriteString(", ")
	builder.WriteString("rule_id=")
	builder.WriteString(_m.RuleID)
	builder.WriteString(", ")
	builder.WriteString("rule_name=")
	builder.WriteString(_m.RuleName)
	builder.WriteString(", ")
	builder.WriteString("trigger=")
	builder.WriteString(_m.Trigger)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteString(", ")
	builder.WriteString("skipped=")
	builder.WriteString(fmt.Sprintf("%v", _m.Skipped))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.StatusCode; v != nil {
		builder.WriteString("status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	if v := _m.Available; v != nil {
		builder.WriteString("available=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("probe=")
	builder.WriteString(_m.Probe)
	builder.WriteString(", ")
	builder.WriteString("matched_policy=")
	builder.WriteString(_m.MatchedPolicy)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	if v := _m.NextCheckAt; v != nil {
		builder.WriteString("next_check_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("backoff_attempt=")
	builder.WriteString(fmt.Sprintf("%v", _m.BackoffAttempt))
	builder.WriteString(", ")
	builder.WriteString("checked_at=")
	builder.WriteString(_m.CheckedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelKeyMonitoringEvents is a parsable slice of ChannelKeyMonitoringEvent.
type ChannelKeyMonitoringEvents []*ChannelKeyMonitoringEvent
