// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/managedobservabilitystate"
)

// ManagedObservabilityState is the model entity for the ManagedObservabilityState schema.
type ManagedObservabilityState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ChargedBytes holds the value of the "charged_bytes" field.
	ChargedBytes int64 `json:"charged_bytes,omitempty"`
	// UnderPressure holds the value of the "under_pressure" field.
	UnderPressure bool `json:"under_pressure,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ManagedObservabilityState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case managedobservabilitystate.FieldUnderPressure:
			values[i] = new(sql.NullBool)
		case managedobservabilitystate.FieldID, managedobservabilitystate.FieldChargedBytes:
			values[i] = new(sql.NullInt64)
		case managedobservabilitystate.FieldLastError:
			values[i] = new(sql.NullString)
		case managedobservabilitystate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ManagedObservabilityState fields.
func (_m *ManagedObservabilityState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case managedobservabilitystate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case managedobservabilitystate.FieldChargedBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field charged_bytes", values[i])
			} else if value.Valid {
				_m.ChargedBytes = value.Int64
			}
		case managedobservabilitystate.FieldUnderPressure:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field under_pressure", values[i])
			} else if value.Valid {
				_m.UnderPressure = value.Bool
			}
		case managedobservabilitystate.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case managedobservabilitystate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ManagedObservabilityState.
// This includes values selected through modifiers, order, etc.
func (_m *ManagedObservabilityState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ManagedObservabilityState.
// Note that you need to call ManagedObservabilityState.Unwrap() before calling this method if this ManagedObservabilityState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ManagedObservabilityState) Update() *ManagedObservabilityStateUpdateOne {
	return NewManagedObservabilityStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ManagedObservabilityState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ManagedObservabilityState) Unwrap() *ManagedObservabilityState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ManagedObservabilityState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ManagedObservabilityState) String() string {
	var builder strings.Builder
	builder.WriteString("ManagedObservabilityState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("charged_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChargedBytes))
	builder.WriteString(", ")
	builder.WriteString("under_pressure=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnderPressure))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ManagedObservabilityStates is a parsable slice of ManagedObservabilityState.
type ManagedObservabilityStates []*ManagedObservabilityState
