// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/managedobservabilitystate"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ManagedObservabilityStateUpdate is the builder for updating ManagedObservabilityState entities.
type ManagedObservabilityStateUpdate struct {
	config
	hooks     []Hook
	mutation  *ManagedObservabilityStateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ManagedObservabilityStateUpdate builder.
func (_u *ManagedObservabilityStateUpdate) Where(ps ...predicate.ManagedObservabilityState) *ManagedObservabilityStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChargedBytes sets the "charged_bytes" field.
func (_u *ManagedObservabilityStateUpdate) SetChargedBytes(v int64) *ManagedObservabilityStateUpdate {
	_u.mutation.ResetChargedBytes()
	_u.mutation.SetChargedBytes(v)
	return _u
}

// SetNillableChargedBytes sets the "charged_bytes" field if the given value is not nil.
func (_u *ManagedObservabilityStateUpdate) SetNillableChargedBytes(v *int64) *ManagedObservabilityStateUpdate {
	if v != nil {
		_u.SetChargedBytes(*v)
	}
	return _u
}

// AddChargedBytes adds value to the "charged_bytes" field.
func (_u *ManagedObservabilityStateUpdate) AddChargedBytes(v int64) *ManagedObservabilityStateUpdate {
	_u.mutation.AddChargedBytes(v)
	return _u
}

// SetUnderPressure sets the "under_pressure" field.
func (_u *ManagedObservabilityStateUpdate) SetUnderPressure(v bool) *ManagedObservabilityStateUpdate {
	_u.mutation.SetUnderPressure(v)
	return _u
}

// SetNillableUnderPressure sets the "under_pressure" field if the given value is not nil.
func (_u *ManagedObservabilityStateUpdate) SetNillableUnderPressure(v *bool) *ManagedObservabilityStateUpdate {
	if v != nil {
		_u.SetUnderPressure(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ManagedObservabilityStateUpdate) SetLastError(v string) *ManagedObservabilityStateUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ManagedObservabilityStateUpdate) SetNillableLastError(v *string) *ManagedObservabilityStateUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ManagedObservabilityStateUpdate) ClearLastError() *ManagedObservabilityStateUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManagedObservabilityStateUpdate) SetUpdatedAt(v time.Time) *ManagedObservabilityStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ManagedObservabilityStateMutation object of the builder.
func (_u *ManagedObservabilityStateUpdate) Mutation() *ManagedObservabilityStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ManagedObservabilityStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedObservabilityStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ManagedObservabilityStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedObservabilityStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ManagedObservabilityStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := managedobservabilitystate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ManagedObservabilityStateUpdate) check() error {
	if v, ok := _u.mutation.ChargedBytes(); ok {
		if err := managedobservabilitystate.ChargedBytesValidator(v); err != nil {
			return &ValidationError{Name: "charged_bytes", err: fmt.Errorf(`ent: validator failed for field "ManagedObservabilityState.charged_bytes": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ManagedObservabilityStateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ManagedObservabilityStateUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ManagedObservabilityStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(managedobservabilitystate.Table, managedobservabilitystate.Columns, sqlgraph.NewFieldSpec(managedobservabilitystate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChargedBytes(); ok {
		_spec.SetField(managedobservabilitystate.FieldChargedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChargedBytes(); ok {
		_spec.AddField(managedobservabilitystate.FieldChargedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UnderPressure(); ok {
		_spec.SetField(managedobservabilitystate.FieldUnderPressure, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(managedobservabilitystate.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(managedobservabilitystate.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(managedobservabilitystate.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedobservabilitystate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ManagedObservabilityStateUpdateOne is the builder for updating a single ManagedObservabilityState entity.
type ManagedObservabilityStateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ManagedObservabilityStateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetChargedBytes sets the "charged_bytes" field.
func (_u *ManagedObservabilityStateUpdateOne) SetChargedBytes(v int64) *ManagedObservabilityStateUpdateOne {
	_u.mutation.ResetChargedBytes()
	_u.mutation.SetChargedBytes(v)
	return _u
}

// SetNillableChargedBytes sets the "charged_bytes" field if the given value is not nil.
func (_u *ManagedObservabilityStateUpdateOne) SetNillableChargedBytes(v *int64) *ManagedObservabilityStateUpdateOne {
	if v != nil {
		_u.SetChargedBytes(*v)
	}
	return _u
}

// AddChargedBytes adds value to the "charged_bytes" field.
func (_u *ManagedObservabilityStateUpdateOne) AddChargedBytes(v int64) *ManagedObservabilityStateUpdateOne {
	_u.mutation.AddChargedBytes(v)
	return _u
}

// SetUnderPressure sets the "under_pressure" field.
func (_u *ManagedObservabilityStateUpdateOne) SetUnderPressure(v bool) *ManagedObservabilityStateUpdateOne {
	_u.mutation.SetUnderPressure(v)
	return _u
}

// SetNillableUnderPressure sets the "under_pressure" field if the given value is not nil.
func (_u *ManagedObservabilityStateUpdateOne) SetNillableUnderPressure(v *bool) *ManagedObservabilityStateUpdateOne {
	if v != nil {
		_u.SetUnderPressure(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ManagedObservabilityStateUpdateOne) SetLastError(v string) *ManagedObservabilityStateUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ManagedObservabilityStateUpdateOne) SetNillableLastError(v *string) *ManagedObservabilityStateUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ManagedObservabilityStateUpdateOne) ClearLastError() *ManagedObservabilityStateUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManagedObservabilityStateUpdateOne) SetUpdatedAt(v time.Time) *ManagedObservabilityStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ManagedObservabilityStateMutation object of the builder.
func (_u *ManagedObservabilityStateUpdateOne) Mutation() *ManagedObservabilityStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ManagedObservabilityStateUpdate builder.
func (_u *ManagedObservabilityStateUpdateOne) Where(ps ...predicate.ManagedObservabilityState) *ManagedObservabilityStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ManagedObservabilityStateUpdateOne) Select(field string, fields ...string) *ManagedObservabilityStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ManagedObservabilityState entity.
func (_u *ManagedObservabilityStateUpdateOne) Save(ctx context.Context) (*ManagedObservabilityState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedObservabilityStateUpdateOne) SaveX(ctx context.Context) *ManagedObservabilityState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ManagedObservabilityStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedObservabilityStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ManagedObservabilityStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := managedobservabilitystate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ManagedObservabilityStateUpdateOne) check() error {
	if v, ok := _u.mutation.ChargedBytes(); ok {
		if err := managedobservabilitystate.ChargedBytesValidator(v); err != nil {
			return &ValidationError{Name: "charged_bytes", err: fmt.Errorf(`ent: validator failed for field "ManagedObservabilityState.charged_bytes": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ManagedObservabilityStateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ManagedObservabilityStateUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ManagedObservabilityStateUpdateOne) sqlSave(ctx context.Context) (_node *ManagedObservabilityState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(managedobservabilitystate.Table, managedobservabilitystate.Columns, sqlgraph.NewFieldSpec(managedobservabilitystate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ManagedObservabilityState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, managedobservabilitystate.FieldID)
		for _, f := range fields {
			if !managedobservabilitystate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != managedobservabilitystate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChargedBytes(); ok {
		_spec.SetField(managedobservabilitystate.FieldChargedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChargedBytes(); ok {
		_spec.AddField(managedobservabilitystate.FieldChargedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UnderPressure(); ok {
		_spec.SetField(managedobservabilitystate.FieldUnderPressure, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(managedobservabilitystate.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(managedobservabilitystate.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(managedobservabilitystate.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ManagedObservabilityState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedobservabilitystate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
