// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/managedobservabilitystate"
)

// ManagedObservabilityStateCreate is the builder for creating a ManagedObservabilityState entity.
type ManagedObservabilityStateCreate struct {
	config
	mutation *ManagedObservabilityStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetChargedBytes sets the "charged_bytes" field.
func (_c *ManagedObservabilityStateCreate) SetChargedBytes(v int64) *ManagedObservabilityStateCreate {
	_c.mutation.SetChargedBytes(v)
	return _c
}

// SetNillableChargedBytes sets the "charged_bytes" field if the given value is not nil.
func (_c *ManagedObservabilityStateCreate) SetNillableChargedBytes(v *int64) *ManagedObservabilityStateCreate {
	if v != nil {
		_c.SetChargedBytes(*v)
	}
	return _c
}

// SetUnderPressure sets the "under_pressure" field.
func (_c *ManagedObservabilityStateCreate) SetUnderPressure(v bool) *ManagedObservabilityStateCreate {
	_c.mutation.SetUnderPressure(v)
	return _c
}

// SetNillableUnderPressure sets the "under_pressure" field if the given value is not nil.
func (_c *ManagedObservabilityStateCreate) SetNillableUnderPressure(v *bool) *ManagedObservabilityStateCreate {
	if v != nil {
		_c.SetUnderPressure(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *ManagedObservabilityStateCreate) SetLastError(v string) *ManagedObservabilityStateCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *ManagedObservabilityStateCreate) SetNillableLastError(v *string) *ManagedObservabilityStateCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ManagedObservabilityStateCreate) SetUpdatedAt(v time.Time) *ManagedObservabilityStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ManagedObservabilityStateCreate) SetNillableUpdatedAt(v *time.Time) *ManagedObservabilityStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ManagedObservabilityStateCreate) SetID(v int) *ManagedObservabilityStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ManagedObservabilityStateCreate) SetNillableID(v *int) *ManagedObservabilityStateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ManagedObservabilityStateMutation object of the builder.
func (_c *ManagedObservabilityStateCreate) Mutation() *ManagedObservabilityStateMutation {
	return _c.mutation
}

// Save creates the ManagedObservabilityState in the database.
func (_c *ManagedObservabilityStateCreate) Save(ctx context.Context) (*ManagedObservabilityState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ManagedObservabilityStateCreate) SaveX(ctx context.Context) *ManagedObservabilityState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ManagedObservabilityStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ManagedObservabilityStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ManagedObservabilityStateCreate) defaults() {
	if _, ok := _c.mutation.ChargedBytes(); !ok {
		v := managedobservabilitystate.DefaultChargedBytes
		_c.mutation.SetChargedBytes(v)
	}
	if _, ok := _c.mutation.UnderPressure(); !ok {
		v := managedobservabilitystate.DefaultUnderPressure
		_c.mutation.SetUnderPressure(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := managedobservabilitystate.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := managedobservabilitystate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := managedobservabilitystate.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ManagedObservabilityStateCreate) check() error {
	if _, ok := _c.mutation.ChargedBytes(); !ok {
		return &ValidationError{Name: "charged_bytes", err: errors.New(`ent: missing required field "ManagedObservabilityState.charged_bytes"`)}
	}
	if v, ok := _c.mutation.ChargedBytes(); ok {
		if err := managedobservabilitystate.ChargedBytesValidator(v); err != nil {
			return &ValidationError{Name: "charged_bytes", err: fmt.Errorf(`ent: validator failed for field "ManagedObservabilityState.charged_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UnderPressure(); !ok {
		return &ValidationError{Name: "under_pressure", err: errors.New(`ent: missing required field "ManagedObservabilityState.under_pressure"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ManagedObservabilityState.updated_at"`)}
	}
	return nil
}

func (_c *ManagedObservabilityStateCreate) sqlSave(ctx context.Context) (*ManagedObservabilityState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ManagedObservabilityStateCreate) createSpec() (*ManagedObservabilityState, *sqlgraph.CreateSpec) {
	var (
		_node = &ManagedObservabilityState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(managedobservabilitystate.Table, sqlgraph.NewFieldSpec(managedobservabilitystate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ChargedBytes(); ok {
		_spec.SetField(managedobservabilitystate.FieldChargedBytes, field.TypeInt64, value)
		_node.ChargedBytes = value
	}
	if value, ok := _c.mutation.UnderPressure(); ok {
		_spec.SetField(managedobservabilitystate.FieldUnderPressure, field.TypeBool, value)
		_node.UnderPressure = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(managedobservabilitystate.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(managedobservabilitystate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ManagedObservabilityState.Create().
//		SetChargedBytes(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ManagedObservabilityStateUpsert) {
//			SetChargedBytes(v+v).
//		}).
//		Exec(ctx)
func (_c *ManagedObservabilityStateCreate) OnConflict(opts ...sql.ConflictOption) *ManagedObservabilityStateUpsertOne {
	_c.conflict = opts
	return &ManagedObservabilityStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ManagedObservabilityState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ManagedObservabilityStateCreate) OnConflictColumns(columns ...string) *ManagedObservabilityStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ManagedObservabilityStateUpsertOne{
		create: _c,
	}
}

type (
	// ManagedObservabilityStateUpsertOne is the builder for "upsert"-ing
	//  one ManagedObservabilityState node.
	ManagedObservabilityStateUpsertOne struct {
		create *ManagedObservabilityStateCreate
	}

	// ManagedObservabilityStateUpsert is the "OnConflict" setter.
	ManagedObservabilityStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetChargedBytes sets the "charged_bytes" field.
func (u *ManagedObservabilityStateUpsert) SetChargedBytes(v int64) *ManagedObservabilityStateUpsert {
	u.Set(managedobservabilitystate.FieldChargedBytes, v)
	return u
}

// UpdateChargedBytes sets the "charged_bytes" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsert) UpdateChargedBytes() *ManagedObservabilityStateUpsert {
	u.SetExcluded(managedobservabilitystate.FieldChargedBytes)
	return u
}

// AddChargedBytes adds v to the "charged_bytes" field.
func (u *ManagedObservabilityStateUpsert) AddChargedBytes(v int64) *ManagedObservabilityStateUpsert {
	u.Add(managedobservabilitystate.FieldChargedBytes, v)
	return u
}

// SetUnderPressure sets the "under_pressure" field.
func (u *ManagedObservabilityStateUpsert) SetUnderPressure(v bool) *ManagedObservabilityStateUpsert {
	u.Set(managedobservabilitystate.FieldUnderPressure, v)
	return u
}

// UpdateUnderPressure sets the "under_pressure" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsert) UpdateUnderPressure() *ManagedObservabilityStateUpsert {
	u.SetExcluded(managedobservabilitystate.FieldUnderPressure)
	return u
}

// SetLastError sets the "last_error" field.
func (u *ManagedObservabilityStateUpsert) SetLastError(v string) *ManagedObservabilityStateUpsert {
	u.Set(managedobservabilitystate.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsert) UpdateLastError() *ManagedObservabilityStateUpsert {
	u.SetExcluded(managedobservabilitystate.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *ManagedObservabilityStateUpsert) ClearLastError() *ManagedObservabilityStateUpsert {
	u.SetNull(managedobservabilitystate.FieldLastError)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ManagedObservabilityStateUpsert) SetUpdatedAt(v time.Time) *ManagedObservabilityStateUpsert {
	u.Set(managedobservabilitystate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsert) UpdateUpdatedAt() *ManagedObservabilityStateUpsert {
	u.SetExcluded(managedobservabilitystate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ManagedObservabilityState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(managedobservabilitystate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ManagedObservabilityStateUpsertOne) UpdateNewValues() *ManagedObservabilityStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(managedobservabilitystate.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ManagedObservabilityState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ManagedObservabilityStateUpsertOne) Ignore() *ManagedObservabilityStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ManagedObservabilityStateUpsertOne) DoNothing() *ManagedObservabilityStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ManagedObservabilityStateCreate.OnConflict
// documentation for more info.
func (u *ManagedObservabilityStateUpsertOne) Update(set func(*ManagedObservabilityStateUpsert)) *ManagedObservabilityStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ManagedObservabilityStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetChargedBytes sets the "charged_bytes" field.
func (u *ManagedObservabilityStateUpsertOne) SetChargedBytes(v int64) *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.SetChargedBytes(v)
	})
}

// AddChargedBytes adds v to the "charged_bytes" field.
func (u *ManagedObservabilityStateUpsertOne) AddChargedBytes(v int64) *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.AddChargedBytes(v)
	})
}

// UpdateChargedBytes sets the "charged_bytes" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsertOne) UpdateChargedBytes() *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.UpdateChargedBytes()
	})
}

// SetUnderPressure sets the "under_pressure" field.
func (u *ManagedObservabilityStateUpsertOne) SetUnderPressure(v bool) *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.SetUnderPressure(v)
	})
}

// UpdateUnderPressure sets the "under_pressure" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsertOne) UpdateUnderPressure() *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.UpdateUnderPressure()
	})
}

// SetLastError sets the "last_error" field.
func (u *ManagedObservabilityStateUpsertOne) SetLastError(v string) *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsertOne) UpdateLastError() *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ManagedObservabilityStateUpsertOne) ClearLastError() *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.ClearLastError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ManagedObservabilityStateUpsertOne) SetUpdatedAt(v time.Time) *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsertOne) UpdateUpdatedAt() *ManagedObservabilityStateUpsertOne {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ManagedObservabilityStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ManagedObservabilityStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ManagedObservabilityStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ManagedObservabilityStateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ManagedObservabilityStateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ManagedObservabilityStateCreateBulk is the builder for creating many ManagedObservabilityState entities in bulk.
type ManagedObservabilityStateCreateBulk struct {
	config
	err      error
	builders []*ManagedObservabilityStateCreate
	conflict []sql.ConflictOption
}

// Save creates the ManagedObservabilityState entities in the database.
func (_c *ManagedObservabilityStateCreateBulk) Save(ctx context.Context) ([]*ManagedObservabilityState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ManagedObservabilityState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ManagedObservabilityStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ManagedObservabilityStateCreateBulk) SaveX(ctx context.Context) []*ManagedObservabilityState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ManagedObservabilityStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ManagedObservabilityStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ManagedObservabilityState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ManagedObservabilityStateUpsert) {
//			SetChargedBytes(v+v).
//		}).
//		Exec(ctx)
func (_c *ManagedObservabilityStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *ManagedObservabilityStateUpsertBulk {
	_c.conflict = opts
	return &ManagedObservabilityStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ManagedObservabilityState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ManagedObservabilityStateCreateBulk) OnConflictColumns(columns ...string) *ManagedObservabilityStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ManagedObservabilityStateUpsertBulk{
		create: _c,
	}
}

// ManagedObservabilityStateUpsertBulk is the builder for "upsert"-ing
// a bulk of ManagedObservabilityState nodes.
type ManagedObservabilityStateUpsertBulk struct {
	create *ManagedObservabilityStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ManagedObservabilityState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(managedobservabilitystate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ManagedObservabilityStateUpsertBulk) UpdateNewValues() *ManagedObservabilityStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(managedobservabilitystate.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ManagedObservabilityState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ManagedObservabilityStateUpsertBulk) Ignore() *ManagedObservabilityStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ManagedObservabilityStateUpsertBulk) DoNothing() *ManagedObservabilityStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ManagedObservabilityStateCreateBulk.OnConflict
// documentation for more info.
func (u *ManagedObservabilityStateUpsertBulk) Update(set func(*ManagedObservabilityStateUpsert)) *ManagedObservabilityStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ManagedObservabilityStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetChargedBytes sets the "charged_bytes" field.
func (u *ManagedObservabilityStateUpsertBulk) SetChargedBytes(v int64) *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.SetChargedBytes(v)
	})
}

// AddChargedBytes adds v to the "charged_bytes" field.
func (u *ManagedObservabilityStateUpsertBulk) AddChargedBytes(v int64) *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.AddChargedBytes(v)
	})
}

// UpdateChargedBytes sets the "charged_bytes" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsertBulk) UpdateChargedBytes() *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.UpdateChargedBytes()
	})
}

// SetUnderPressure sets the "under_pressure" field.
func (u *ManagedObservabilityStateUpsertBulk) SetUnderPressure(v bool) *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.SetUnderPressure(v)
	})
}

// UpdateUnderPressure sets the "under_pressure" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsertBulk) UpdateUnderPressure() *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.UpdateUnderPressure()
	})
}

// SetLastError sets the "last_error" field.
func (u *ManagedObservabilityStateUpsertBulk) SetLastError(v string) *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsertBulk) UpdateLastError() *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ManagedObservabilityStateUpsertBulk) ClearLastError() *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.ClearLastError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ManagedObservabilityStateUpsertBulk) SetUpdatedAt(v time.Time) *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ManagedObservabilityStateUpsertBulk) UpdateUpdatedAt() *ManagedObservabilityStateUpsertBulk {
	return u.Update(func(s *ManagedObservabilityStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ManagedObservabilityStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ManagedObservabilityStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ManagedObservabilityStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ManagedObservabilityStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
