// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/observabilitypayload"
	"github.com/looplj/axonhub/internal/ent/request"
)

// ObservabilityPayload is the model entity for the ObservabilityPayload schema.
type ObservabilityPayload struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID int `json:"request_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind observabilitypayload.Kind `json:"kind,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// ByteLength holds the value of the "byte_length" field.
	ByteLength int64 `json:"byte_length,omitempty"`
	// ChargedBytes holds the value of the "charged_bytes" field.
	ChargedBytes int64 `json:"charged_bytes,omitempty"`
	// Data holds the value of the "data" field.
	Data []byte `json:"data,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ObservabilityPayloadQuery when eager-loading is set.
	Edges        ObservabilityPayloadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ObservabilityPayloadEdges holds the relations/edges for other nodes in the graph.
type ObservabilityPayloadEdges struct {
	// Request holds the value of the request edge.
	Request *Request `json:"request,omitempty"`
	// RequestBodyRequests holds the value of the request_body_requests edge.
	RequestBodyRequests []*Request `json:"request_body_requests,omitempty"`
	// RequestBodyExecutions holds the value of the request_body_executions edge.
	RequestBodyExecutions []*RequestExecution `json:"request_body_executions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int

	namedRequestBodyRequests   map[string][]*Request
	namedRequestBodyExecutions map[string][]*RequestExecution
}

// RequestOrErr returns the Request value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ObservabilityPayloadEdges) RequestOrErr() (*Request, error) {
	if e.Request != nil {
		return e.Request, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: request.Label}
	}
	return nil, &NotLoadedError{edge: "request"}
}

// RequestBodyRequestsOrErr returns the RequestBodyRequests value or an error if the edge
// was not loaded in eager-loading.
func (e ObservabilityPayloadEdges) RequestBodyRequestsOrErr() ([]*Request, error) {
	if e.loadedTypes[1] {
		return e.RequestBodyRequests, nil
	}
	return nil, &NotLoadedError{edge: "request_body_requests"}
}

// RequestBodyExecutionsOrErr returns the RequestBodyExecutions value or an error if the edge
// was not loaded in eager-loading.
func (e ObservabilityPayloadEdges) RequestBodyExecutionsOrErr() ([]*RequestExecution, error) {
	if e.loadedTypes[2] {
		return e.RequestBodyExecutions, nil
	}
	return nil, &NotLoadedError{edge: "request_body_executions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ObservabilityPayload) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case observabilitypayload.FieldData:
			values[i] = new([]byte)
		case observabilitypayload.FieldID, observabilitypayload.FieldRequestID, observabilitypayload.FieldByteLength, observabilitypayload.FieldChargedBytes:
			values[i] = new(sql.NullInt64)
		case observabilitypayload.FieldKind, observabilitypayload.FieldSha256:
			values[i] = new(sql.NullString)
		case observabilitypayload.FieldCreatedAt, observabilitypayload.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ObservabilityPayload fields.
func (_m *ObservabilityPayload) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case observabilitypayload.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case observabilitypayload.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case observabilitypayload.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case observabilitypayload.FieldRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = int(value.Int64)
			}
		case observabilitypayload.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = observabilitypayload.Kind(value.String)
			}
		case observabilitypayload.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case observabilitypayload.FieldByteLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field byte_length", values[i])
			} else if value.Valid {
				_m.ByteLength = value.Int64
			}
		case observabilitypayload.FieldChargedBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field charged_bytes", values[i])
			} else if value.Valid {
				_m.ChargedBytes = value.Int64
			}
		case observabilitypayload.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil {
				_m.Data = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ObservabilityPayload.
// This includes values selected through modifiers, order, etc.
func (_m *ObservabilityPayload) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequest queries the "request" edge of the ObservabilityPayload entity.
func (_m *ObservabilityPayload) QueryRequest() *RequestQuery {
	return NewObservabilityPayloadClient(_m.config).QueryRequest(_m)
}

// QueryRequestBodyRequests queries the "request_body_requests" edge of the ObservabilityPayload entity.
func (_m *ObservabilityPayload) QueryRequestBodyRequests() *RequestQuery {
	return NewObservabilityPayloadClient(_m.config).QueryRequestBodyRequests(_m)
}

// QueryRequestBodyExecutions queries the "request_body_executions" edge of the ObservabilityPayload entity.
func (_m *ObservabilityPayload) QueryRequestBodyExecutions() *RequestExecutionQuery {
	return NewObservabilityPayloadClient(_m.config).QueryRequestBodyExecutions(_m)
}

// Update returns a builder for updating this ObservabilityPayload.
// Note that you need to call ObservabilityPayload.Unwrap() before calling this method if this ObservabilityPayload
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ObservabilityPayload) Update() *ObservabilityPayloadUpdateOne {
	return NewObservabilityPayloadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ObservabilityPayload entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ObservabilityPayload) Unwrap() *ObservabilityPayload {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ObservabilityPayload is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ObservabilityPayload) String() string {
	var builder strings.Builder
	builder.WriteString("ObservabilityPayload(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("byte_length=")
	builder.WriteString(fmt.Sprintf("%v", _m.ByteLength))
	builder.WriteString(", ")
	builder.WriteString("charged_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChargedBytes))
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", _m.Data))
	builder.WriteByte(')')
	return builder.String()
}

// NamedRequestBodyRequests returns the RequestBodyRequests named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *ObservabilityPayload) NamedRequestBodyRequests(name string) ([]*Request, error) {
	if _m.Edges.namedRequestBodyRequests == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRequestBodyRequests[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *ObservabilityPayload) appendNamedRequestBodyRequests(name string, edges ...*Request) {
	if _m.Edges.namedRequestBodyRequests == nil {
		_m.Edges.namedRequestBodyRequests = make(map[string][]*Request)
	}
	if len(edges) == 0 {
		_m.Edges.namedRequestBodyRequests[name] = []*Request{}
	} else {
		_m.Edges.namedRequestBodyRequests[name] = append(_m.Edges.namedRequestBodyRequests[name], edges...)
	}
}

// NamedRequestBodyExecutions returns the RequestBodyExecutions named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *ObservabilityPayload) NamedRequestBodyExecutions(name string) ([]*RequestExecution, error) {
	if _m.Edges.namedRequestBodyExecutions == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRequestBodyExecutions[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *ObservabilityPayload) appendNamedRequestBodyExecutions(name string, edges ...*RequestExecution) {
	if _m.Edges.namedRequestBodyExecutions == nil {
		_m.Edges.namedRequestBodyExecutions = make(map[string][]*RequestExecution)
	}
	if len(edges) == 0 {
		_m.Edges.namedRequestBodyExecutions[name] = []*RequestExecution{}
	} else {
		_m.Edges.namedRequestBodyExecutions[name] = append(_m.Edges.namedRequestBodyExecutions[name], edges...)
	}
}

// ObservabilityPayloads is a parsable slice of ObservabilityPayload.
type ObservabilityPayloads []*ObservabilityPayload
