// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/observabilitypayload"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ObservabilityPayloadDelete is the builder for deleting a ObservabilityPayload entity.
type ObservabilityPayloadDelete struct {
	config
	hooks    []Hook
	mutation *ObservabilityPayloadMutation
}

// Where appends a list predicates to the ObservabilityPayloadDelete builder.
func (_d *ObservabilityPayloadDelete) Where(ps ...predicate.ObservabilityPayload) *ObservabilityPayloadDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ObservabilityPayloadDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ObservabilityPayloadDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ObservabilityPayloadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(observabilitypayload.Table, sqlgraph.NewFieldSpec(observabilitypayload.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ObservabilityPayloadDeleteOne is the builder for deleting a single ObservabilityPayload entity.
type ObservabilityPayloadDeleteOne struct {
	_d *ObservabilityPayloadDelete
}

// Where appends a list predicates to the ObservabilityPayloadDelete builder.
func (_d *ObservabilityPayloadDeleteOne) Where(ps ...predicate.ObservabilityPayload) *ObservabilityPayloadDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ObservabilityPayloadDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{observabilitypayload.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ObservabilityPayloadDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
