// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/observabilitypayload"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
)

// ObservabilityPayloadQuery is the builder for querying ObservabilityPayload entities.
type ObservabilityPayloadQuery struct {
	config
	ctx                            *QueryContext
	order                          []observabilitypayload.OrderOption
	inters                         []Interceptor
	predicates                     []predicate.ObservabilityPayload
	withRequest                    *RequestQuery
	withRequestBodyRequests        *RequestQuery
	withRequestBodyExecutions      *RequestExecutionQuery
	loadTotal                      []func(context.Context, []*ObservabilityPayload) error
	modifiers                      []func(*sql.Selector)
	withNamedRequestBodyRequests   map[string]*RequestQuery
	withNamedRequestBodyExecutions map[string]*RequestExecutionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ObservabilityPayloadQuery builder.
func (_q *ObservabilityPayloadQuery) Where(ps ...predicate.ObservabilityPayload) *ObservabilityPayloadQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ObservabilityPayloadQuery) Limit(limit int) *ObservabilityPayloadQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ObservabilityPayloadQuery) Offset(offset int) *ObservabilityPayloadQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ObservabilityPayloadQuery) Unique(unique bool) *ObservabilityPayloadQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ObservabilityPayloadQuery) Order(o ...observabilitypayload.OrderOption) *ObservabilityPayloadQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRequest chains the current query on the "request" edge.
func (_q *ObservabilityPayloadQuery) QueryRequest() *RequestQuery {
	query := (&RequestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(observabilitypayload.Table, observabilitypayload.FieldID, selector),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, observabilitypayload.RequestTable, observabilitypayload.RequestColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRequestBodyRequests chains the current query on the "request_body_requests" edge.
func (_q *ObservabilityPayloadQuery) QueryRequestBodyRequests() *RequestQuery {
	query := (&RequestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(observabilitypayload.Table, observabilitypayload.FieldID, selector),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, observabilitypayload.RequestBodyRequestsTable, observabilitypayload.RequestBodyRequestsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRequestBodyExecutions chains the current query on the "request_body_executions" edge.
func (_q *ObservabilityPayloadQuery) QueryRequestBodyExecutions() *RequestExecutionQuery {
	query := (&RequestExecutionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(observabilitypayload.Table, observabilitypayload.FieldID, selector),
			sqlgraph.To(requestexecution.Table, requestexecution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, observabilitypayload.RequestBodyExecutionsTable, observabilitypayload.RequestBodyExecutionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ObservabilityPayload entity from the query.
// Returns a *NotFoundError when no ObservabilityPayload was found.
func (_q *ObservabilityPayloadQuery) First(ctx context.Context) (*ObservabilityPayload, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{observabilitypayload.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ObservabilityPayloadQuery) FirstX(ctx context.Context) *ObservabilityPayload {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ObservabilityPayload ID from the query.
// Returns a *NotFoundError when no ObservabilityPayload ID was found.
func (_q *ObservabilityPayloadQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{observabilitypayload.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ObservabilityPayloadQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ObservabilityPayload entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ObservabilityPayload entity is found.
// Returns a *NotFoundError when no ObservabilityPayload entities are found.
func (_q *ObservabilityPayloadQuery) Only(ctx context.Context) (*ObservabilityPayload, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{observabilitypayload.Label}
	default:
		return nil, &NotSingularError{observabilitypayload.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ObservabilityPayloadQuery) OnlyX(ctx context.Context) *ObservabilityPayload {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ObservabilityPayload ID in the query.
// Returns a *NotSingularError when more than one ObservabilityPayload ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ObservabilityPayloadQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{observabilitypayload.Label}
	default:
		err = &NotSingularError{observabilitypayload.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ObservabilityPayloadQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ObservabilityPayloads.
func (_q *ObservabilityPayloadQuery) All(ctx context.Context) ([]*ObservabilityPayload, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ObservabilityPayload, *ObservabilityPayloadQuery]()
	return withInterceptors[[]*ObservabilityPayload](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ObservabilityPayloadQuery) AllX(ctx context.Context) []*ObservabilityPayload {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ObservabilityPayload IDs.
func (_q *ObservabilityPayloadQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(observabilitypayload.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ObservabilityPayloadQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ObservabilityPayloadQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ObservabilityPayloadQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ObservabilityPayloadQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ObservabilityPayloadQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ObservabilityPayloadQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ObservabilityPayloadQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ObservabilityPayloadQuery) Clone() *ObservabilityPayloadQuery {
	if _q == nil {
		return nil
	}
	return &ObservabilityPayloadQuery{
		config:                    _q.config,
		ctx:                       _q.ctx.Clone(),
		order:                     append([]observabilitypayload.OrderOption{}, _q.order...),
		inters:                    append([]Interceptor{}, _q.inters...),
		predicates:                append([]predicate.ObservabilityPayload{}, _q.predicates...),
		withRequest:               _q.withRequest.Clone(),
		withRequestBodyRequests:   _q.withRequestBodyRequests.Clone(),
		withRequestBodyExecutions: _q.withRequestBodyExecutions.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithRequest tells the query-builder to eager-load the nodes that are connected to
// the "request" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ObservabilityPayloadQuery) WithRequest(opts ...func(*RequestQuery)) *ObservabilityPayloadQuery {
	query := (&RequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRequest = query
	return _q
}

// WithRequestBodyRequests tells the query-builder to eager-load the nodes that are connected to
// the "request_body_requests" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ObservabilityPayloadQuery) WithRequestBodyRequests(opts ...func(*RequestQuery)) *ObservabilityPayloadQuery {
	query := (&RequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRequestBodyRequests = query
	return _q
}

// WithRequestBodyExecutions tells the query-builder to eager-load the nodes that are connected to
// the "request_body_executions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ObservabilityPayloadQuery) WithRequestBodyExecutions(opts ...func(*RequestExecutionQuery)) *ObservabilityPayloadQuery {
	query := (&RequestExecutionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRequestBodyExecutions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ObservabilityPayload.Query().
//		GroupBy(observabilitypayload.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ObservabilityPayloadQuery) GroupBy(field string, fields ...string) *ObservabilityPayloadGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ObservabilityPayloadGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = observabilitypayload.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ObservabilityPayload.Query().
//		Select(observabilitypayload.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ObservabilityPayloadQuery) Select(fields ...string) *ObservabilityPayloadSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ObservabilityPayloadSelect{ObservabilityPayloadQuery: _q}
	sbuild.label = observabilitypayload.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ObservabilityPayloadSelect configured with the given aggregations.
func (_q *ObservabilityPayloadQuery) Aggregate(fns ...AggregateFunc) *ObservabilityPayloadSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ObservabilityPayloadQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !observabilitypayload.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ObservabilityPayloadQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ObservabilityPayload, error) {
	var (
		nodes       = []*ObservabilityPayload{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withRequest != nil,
			_q.withRequestBodyRequests != nil,
			_q.withRequestBodyExecutions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ObservabilityPayload).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ObservabilityPayload{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRequest; query != nil {
		if err := _q.loadRequest(ctx, query, nodes, nil,
			func(n *ObservabilityPayload, e *Request) { n.Edges.Request = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRequestBodyRequests; query != nil {
		if err := _q.loadRequestBodyRequests(ctx, query, nodes,
			func(n *ObservabilityPayload) { n.Edges.RequestBodyRequests = []*Request{} },
			func(n *ObservabilityPayload, e *Request) {
				n.Edges.RequestBodyRequests = append(n.Edges.RequestBodyRequests, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withRequestBodyExecutions; query != nil {
		if err := _q.loadRequestBodyExecutions(ctx, query, nodes,
			func(n *ObservabilityPayload) { n.Edges.RequestBodyExecutions = []*RequestExecution{} },
			func(n *ObservabilityPayload, e *RequestExecution) {
				n.Edges.RequestBodyExecutions = append(n.Edges.RequestBodyExecutions, e)
			}); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedRequestBodyRequests {
		if err := _q.loadRequestBodyRequests(ctx, query, nodes,
			func(n *ObservabilityPayload) { n.appendNamedRequestBodyRequests(name) },
			func(n *ObservabilityPayload, e *Request) { n.appendNamedRequestBodyRequests(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedRequestBodyExecutions {
		if err := _q.loadRequestBodyExecutions(ctx, query, nodes,
			func(n *ObservabilityPayload) { n.appendNamedRequestBodyExecutions(name) },
			func(n *ObservabilityPayload, e *RequestExecution) { n.appendNamedRequestBodyExecutions(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ObservabilityPayloadQuery) loadRequest(ctx context.Context, query *RequestQuery, nodes []*ObservabilityPayload, init func(*ObservabilityPayload), assign func(*ObservabilityPayload, *Request)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ObservabilityPayload)
	for i := range nodes {
		fk := nodes[i].RequestID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(request.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "request_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ObservabilityPayloadQuery) loadRequestBodyRequests(ctx context.Context, query *RequestQuery, nodes []*ObservabilityPayload, init func(*ObservabilityPayload), assign func(*ObservabilityPayload, *Request)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ObservabilityPayload)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(request.FieldRequestBodyPayloadID)
	}
	query.Where(predicate.Request(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(observabilitypayload.RequestBodyRequestsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RequestBodyPayloadID
		if fk == nil {
			return fmt.Errorf(`foreign-key "request_body_payload_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "request_body_payload_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ObservabilityPayloadQuery) loadRequestBodyExecutions(ctx context.Context, query *RequestExecutionQuery, nodes []*ObservabilityPayload, init func(*ObservabilityPayload), assign func(*ObservabilityPayload, *RequestExecution)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ObservabilityPayload)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(requestexecution.FieldRequestBodyPayloadID)
	}
	query.Where(predicate.RequestExecution(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(observabilitypayload.RequestBodyExecutionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RequestBodyPayloadID
		if fk == nil {
			return fmt.Errorf(`foreign-key "request_body_payload_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "request_body_payload_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ObservabilityPayloadQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ObservabilityPayloadQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(observabilitypayload.Table, observabilitypayload.Columns, sqlgraph.NewFieldSpec(observabilitypayload.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, observabilitypayload.FieldID)
		for i := range fields {
			if fields[i] != observabilitypayload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRequest != nil {
			_spec.Node.AddColumnOnce(observabilitypayload.FieldRequestID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ObservabilityPayloadQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(observabilitypayload.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = observabilitypayload.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ObservabilityPayloadQuery) Modify(modifiers ...func(s *sql.Selector)) *ObservabilityPayloadSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WithNamedRequestBodyRequests tells the query-builder to eager-load the nodes that are connected to the "request_body_requests"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *ObservabilityPayloadQuery) WithNamedRequestBodyRequests(name string, opts ...func(*RequestQuery)) *ObservabilityPayloadQuery {
	query := (&RequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedRequestBodyRequests == nil {
		_q.withNamedRequestBodyRequests = make(map[string]*RequestQuery)
	}
	_q.withNamedRequestBodyRequests[name] = query
	return _q
}

// WithNamedRequestBodyExecutions tells the query-builder to eager-load the nodes that are connected to the "request_body_executions"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *ObservabilityPayloadQuery) WithNamedRequestBodyExecutions(name string, opts ...func(*RequestExecutionQuery)) *ObservabilityPayloadQuery {
	query := (&RequestExecutionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedRequestBodyExecutions == nil {
		_q.withNamedRequestBodyExecutions = make(map[string]*RequestExecutionQuery)
	}
	_q.withNamedRequestBodyExecutions[name] = query
	return _q
}

// ObservabilityPayloadGroupBy is the group-by builder for ObservabilityPayload entities.
type ObservabilityPayloadGroupBy struct {
	selector
	build *ObservabilityPayloadQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ObservabilityPayloadGroupBy) Aggregate(fns ...AggregateFunc) *ObservabilityPayloadGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ObservabilityPayloadGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ObservabilityPayloadQuery, *ObservabilityPayloadGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ObservabilityPayloadGroupBy) sqlScan(ctx context.Context, root *ObservabilityPayloadQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ObservabilityPayloadSelect is the builder for selecting fields of ObservabilityPayload entities.
type ObservabilityPayloadSelect struct {
	*ObservabilityPayloadQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ObservabilityPayloadSelect) Aggregate(fns ...AggregateFunc) *ObservabilityPayloadSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ObservabilityPayloadSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ObservabilityPayloadQuery, *ObservabilityPayloadSelect](ctx, _s.ObservabilityPayloadQuery, _s, _s.inters, v)
}

func (_s *ObservabilityPayloadSelect) sqlScan(ctx context.Context, root *ObservabilityPayloadQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ObservabilityPayloadSelect) Modify(modifiers ...func(s *sql.Selector)) *ObservabilityPayloadSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
