// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/observabilitypayload"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
)

// ObservabilityPayloadCreate is the builder for creating a ObservabilityPayload entity.
type ObservabilityPayloadCreate struct {
	config
	mutation *ObservabilityPayloadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ObservabilityPayloadCreate) SetCreatedAt(v time.Time) *ObservabilityPayloadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ObservabilityPayloadCreate) SetNillableCreatedAt(v *time.Time) *ObservabilityPayloadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ObservabilityPayloadCreate) SetUpdatedAt(v time.Time) *ObservabilityPayloadCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ObservabilityPayloadCreate) SetNillableUpdatedAt(v *time.Time) *ObservabilityPayloadCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *ObservabilityPayloadCreate) SetRequestID(v int) *ObservabilityPayloadCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ObservabilityPayloadCreate) SetKind(v observabilitypayload.Kind) *ObservabilityPayloadCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *ObservabilityPayloadCreate) SetSha256(v string) *ObservabilityPayloadCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetByteLength sets the "byte_length" field.
func (_c *ObservabilityPayloadCreate) SetByteLength(v int64) *ObservabilityPayloadCreate {
	_c.mutation.SetByteLength(v)
	return _c
}

// SetChargedBytes sets the "charged_bytes" field.
func (_c *ObservabilityPayloadCreate) SetChargedBytes(v int64) *ObservabilityPayloadCreate {
	_c.mutation.SetChargedBytes(v)
	return _c
}

// SetData sets the "data" field.
func (_c *ObservabilityPayloadCreate) SetData(v []byte) *ObservabilityPayloadCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetRequest sets the "request" edge to the Request entity.
func (_c *ObservabilityPayloadCreate) SetRequest(v *Request) *ObservabilityPayloadCreate {
	return _c.SetRequestID(v.ID)
}

// AddRequestBodyRequestIDs adds the "request_body_requests" edge to the Request entity by IDs.
func (_c *ObservabilityPayloadCreate) AddRequestBodyRequestIDs(ids ...int) *ObservabilityPayloadCreate {
	_c.mutation.AddRequestBodyRequestIDs(ids...)
	return _c
}

// AddRequestBodyRequests adds the "request_body_requests" edges to the Request entity.
func (_c *ObservabilityPayloadCreate) AddRequestBodyRequests(v ...*Request) *ObservabilityPayloadCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRequestBodyRequestIDs(ids...)
}

// AddRequestBodyExecutionIDs adds the "request_body_executions" edge to the RequestExecution entity by IDs.
func (_c *ObservabilityPayloadCreate) AddRequestBodyExecutionIDs(ids ...int) *ObservabilityPayloadCreate {
	_c.mutation.AddRequestBodyExecutionIDs(ids...)
	return _c
}

// AddRequestBodyExecutions adds the "request_body_executions" edges to the RequestExecution entity.
func (_c *ObservabilityPayloadCreate) AddRequestBodyExecutions(v ...*RequestExecution) *ObservabilityPayloadCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRequestBodyExecutionIDs(ids...)
}

// Mutation returns the ObservabilityPayloadMutation object of the builder.
func (_c *ObservabilityPayloadCreate) Mutation() *ObservabilityPayloadMutation {
	return _c.mutation
}

// Save creates the ObservabilityPayload in the database.
func (_c *ObservabilityPayloadCreate) Save(ctx context.Context) (*ObservabilityPayload, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ObservabilityPayloadCreate) SaveX(ctx context.Context) *ObservabilityPayload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObservabilityPayloadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObservabilityPayloadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ObservabilityPayloadCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := observabilitypayload.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := observabilitypayload.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ObservabilityPayloadCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "ObservabilityPayload.request_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ObservabilityPayload.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := observabilitypayload.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ObservabilityPayload.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "ObservabilityPayload.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := observabilitypayload.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ObservabilityPayload.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ByteLength(); !ok {
		return &ValidationError{Name: "byte_length", err: errors.New(`ent: missing required field "ObservabilityPayload.byte_length"`)}
	}
	if v, ok := _c.mutation.ByteLength(); ok {
		if err := observabilitypayload.ByteLengthValidator(v); err != nil {
			return &ValidationError{Name: "byte_length", err: fmt.Errorf(`ent: validator failed for field "ObservabilityPayload.byte_length": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChargedBytes(); !ok {
		return &ValidationError{Name: "charged_bytes", err: errors.New(`ent: missing required field "ObservabilityPayload.charged_bytes"`)}
	}
	if v, ok := _c.mutation.ChargedBytes(); ok {
		if err := observabilitypayload.ChargedBytesValidator(v); err != nil {
			return &ValidationError{Name: "charged_bytes", err: fmt.Errorf(`ent: validator failed for field "ObservabilityPayload.charged_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "ObservabilityPayload.data"`)}
	}
	if len(_c.mutation.RequestIDs()) == 0 {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required edge "ObservabilityPayload.request"`)}
	}
	return nil
}

func (_c *ObservabilityPayloadCreate) sqlSave(ctx context.Context) (*ObservabilityPayload, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ObservabilityPayloadCreate) createSpec() (*ObservabilityPayload, *sqlgraph.CreateSpec) {
	var (
		_node = &ObservabilityPayload{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(observabilitypayload.Table, sqlgraph.NewFieldSpec(observabilitypayload.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(observabilitypayload.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(observabilitypayload.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(observabilitypayload.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(observabilitypayload.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.ByteLength(); ok {
		_spec.SetField(observabilitypayload.FieldByteLength, field.TypeInt64, value)
		_node.ByteLength = value
	}
	if value, ok := _c.mutation.ChargedBytes(); ok {
		_spec.SetField(observabilitypayload.FieldChargedBytes, field.TypeInt64, value)
		_node.ChargedBytes = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(observabilitypayload.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	if nodes := _c.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   observabilitypayload.RequestTable,
			Columns: []string{observabilitypayload.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RequestBodyRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyRequestsTable,
			Columns: []string{observabilitypayload.RequestBodyRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RequestBodyExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyExecutionsTable,
			Columns: []string{observabilitypayload.RequestBodyExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ObservabilityPayload.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ObservabilityPayloadUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ObservabilityPayloadCreate) OnConflict(opts ...sql.ConflictOption) *ObservabilityPayloadUpsertOne {
	_c.conflict = opts
	return &ObservabilityPayloadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ObservabilityPayload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ObservabilityPayloadCreate) OnConflictColumns(columns ...string) *ObservabilityPayloadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ObservabilityPayloadUpsertOne{
		create: _c,
	}
}

type (
	// ObservabilityPayloadUpsertOne is the builder for "upsert"-ing
	//  one ObservabilityPayload node.
	ObservabilityPayloadUpsertOne struct {
		create *ObservabilityPayloadCreate
	}

	// ObservabilityPayloadUpsert is the "OnConflict" setter.
	ObservabilityPayloadUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ObservabilityPayloadUpsert) SetUpdatedAt(v time.Time) *ObservabilityPayloadUpsert {
	u.Set(observabilitypayload.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ObservabilityPayloadUpsert) UpdateUpdatedAt() *ObservabilityPayloadUpsert {
	u.SetExcluded(observabilitypayload.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ObservabilityPayload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ObservabilityPayloadUpsertOne) UpdateNewValues() *ObservabilityPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(observabilitypayload.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.RequestID(); exists {
			s.SetIgnore(observabilitypayload.FieldRequestID)
		}
		if _, exists := u.create.mutation.Kind(); exists {
			s.SetIgnore(observabilitypayload.FieldKind)
		}
		if _, exists := u.create.mutation.Sha256(); exists {
			s.SetIgnore(observabilitypayload.FieldSha256)
		}
		if _, exists := u.create.mutation.ByteLength(); exists {
			s.SetIgnore(observabilitypayload.FieldByteLength)
		}
		if _, exists := u.create.mutation.ChargedBytes(); exists {
			s.SetIgnore(observabilitypayload.FieldChargedBytes)
		}
		if _, exists := u.create.mutation.Data(); exists {
			s.SetIgnore(observabilitypayload.FieldData)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ObservabilityPayload.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ObservabilityPayloadUpsertOne) Ignore() *ObservabilityPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ObservabilityPayloadUpsertOne) DoNothing() *ObservabilityPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ObservabilityPayloadCreate.OnConflict
// documentation for more info.
func (u *ObservabilityPayloadUpsertOne) Update(set func(*ObservabilityPayloadUpsert)) *ObservabilityPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ObservabilityPayloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ObservabilityPayloadUpsertOne) SetUpdatedAt(v time.Time) *ObservabilityPayloadUpsertOne {
	return u.Update(func(s *ObservabilityPayloadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ObservabilityPayloadUpsertOne) UpdateUpdatedAt() *ObservabilityPayloadUpsertOne {
	return u.Update(func(s *ObservabilityPayloadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ObservabilityPayloadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ObservabilityPayloadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ObservabilityPayloadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ObservabilityPayloadUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ObservabilityPayloadUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ObservabilityPayloadCreateBulk is the builder for creating many ObservabilityPayload entities in bulk.
type ObservabilityPayloadCreateBulk struct {
	config
	err      error
	builders []*ObservabilityPayloadCreate
	conflict []sql.ConflictOption
}

// Save creates the ObservabilityPayload entities in the database.
func (_c *ObservabilityPayloadCreateBulk) Save(ctx context.Context) ([]*ObservabilityPayload, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ObservabilityPayload, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ObservabilityPayloadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ObservabilityPayloadCreateBulk) SaveX(ctx context.Context) []*ObservabilityPayload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObservabilityPayloadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObservabilityPayloadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ObservabilityPayload.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ObservabilityPayloadUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ObservabilityPayloadCreateBulk) OnConflict(opts ...sql.ConflictOption) *ObservabilityPayloadUpsertBulk {
	_c.conflict = opts
	return &ObservabilityPayloadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ObservabilityPayload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ObservabilityPayloadCreateBulk) OnConflictColumns(columns ...string) *ObservabilityPayloadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ObservabilityPayloadUpsertBulk{
		create: _c,
	}
}

// ObservabilityPayloadUpsertBulk is the builder for "upsert"-ing
// a bulk of ObservabilityPayload nodes.
type ObservabilityPayloadUpsertBulk struct {
	create *ObservabilityPayloadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ObservabilityPayload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ObservabilityPayloadUpsertBulk) UpdateNewValues() *ObservabilityPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(observabilitypayload.FieldCreatedAt)
			}
			if _, exists := b.mutation.RequestID(); exists {
				s.SetIgnore(observabilitypayload.FieldRequestID)
			}
			if _, exists := b.mutation.Kind(); exists {
				s.SetIgnore(observabilitypayload.FieldKind)
			}
			if _, exists := b.mutation.Sha256(); exists {
				s.SetIgnore(observabilitypayload.FieldSha256)
			}
			if _, exists := b.mutation.ByteLength(); exists {
				s.SetIgnore(observabilitypayload.FieldByteLength)
			}
			if _, exists := b.mutation.ChargedBytes(); exists {
				s.SetIgnore(observabilitypayload.FieldChargedBytes)
			}
			if _, exists := b.mutation.Data(); exists {
				s.SetIgnore(observabilitypayload.FieldData)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ObservabilityPayload.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ObservabilityPayloadUpsertBulk) Ignore() *ObservabilityPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ObservabilityPayloadUpsertBulk) DoNothing() *ObservabilityPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ObservabilityPayloadCreateBulk.OnConflict
// documentation for more info.
func (u *ObservabilityPayloadUpsertBulk) Update(set func(*ObservabilityPayloadUpsert)) *ObservabilityPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ObservabilityPayloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ObservabilityPayloadUpsertBulk) SetUpdatedAt(v time.Time) *ObservabilityPayloadUpsertBulk {
	return u.Update(func(s *ObservabilityPayloadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ObservabilityPayloadUpsertBulk) UpdateUpdatedAt() *ObservabilityPayloadUpsertBulk {
	return u.Update(func(s *ObservabilityPayloadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ObservabilityPayloadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ObservabilityPayloadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ObservabilityPayloadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ObservabilityPayloadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
