// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/observabilitypayload"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
)

// ObservabilityPayloadUpdate is the builder for updating ObservabilityPayload entities.
type ObservabilityPayloadUpdate struct {
	config
	hooks     []Hook
	mutation  *ObservabilityPayloadMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ObservabilityPayloadUpdate builder.
func (_u *ObservabilityPayloadUpdate) Where(ps ...predicate.ObservabilityPayload) *ObservabilityPayloadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObservabilityPayloadUpdate) SetUpdatedAt(v time.Time) *ObservabilityPayloadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRequestBodyRequestIDs adds the "request_body_requests" edge to the Request entity by IDs.
func (_u *ObservabilityPayloadUpdate) AddRequestBodyRequestIDs(ids ...int) *ObservabilityPayloadUpdate {
	_u.mutation.AddRequestBodyRequestIDs(ids...)
	return _u
}

// AddRequestBodyRequests adds the "request_body_requests" edges to the Request entity.
func (_u *ObservabilityPayloadUpdate) AddRequestBodyRequests(v ...*Request) *ObservabilityPayloadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestBodyRequestIDs(ids...)
}

// AddRequestBodyExecutionIDs adds the "request_body_executions" edge to the RequestExecution entity by IDs.
func (_u *ObservabilityPayloadUpdate) AddRequestBodyExecutionIDs(ids ...int) *ObservabilityPayloadUpdate {
	_u.mutation.AddRequestBodyExecutionIDs(ids...)
	return _u
}

// AddRequestBodyExecutions adds the "request_body_executions" edges to the RequestExecution entity.
func (_u *ObservabilityPayloadUpdate) AddRequestBodyExecutions(v ...*RequestExecution) *ObservabilityPayloadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestBodyExecutionIDs(ids...)
}

// Mutation returns the ObservabilityPayloadMutation object of the builder.
func (_u *ObservabilityPayloadUpdate) Mutation() *ObservabilityPayloadMutation {
	return _u.mutation
}

// ClearRequestBodyRequests clears all "request_body_requests" edges to the Request entity.
func (_u *ObservabilityPayloadUpdate) ClearRequestBodyRequests() *ObservabilityPayloadUpdate {
	_u.mutation.ClearRequestBodyRequests()
	return _u
}

// RemoveRequestBodyRequestIDs removes the "request_body_requests" edge to Request entities by IDs.
func (_u *ObservabilityPayloadUpdate) RemoveRequestBodyRequestIDs(ids ...int) *ObservabilityPayloadUpdate {
	_u.mutation.RemoveRequestBodyRequestIDs(ids...)
	return _u
}

// RemoveRequestBodyRequests removes "request_body_requests" edges to Request entities.
func (_u *ObservabilityPayloadUpdate) RemoveRequestBodyRequests(v ...*Request) *ObservabilityPayloadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestBodyRequestIDs(ids...)
}

// ClearRequestBodyExecutions clears all "request_body_executions" edges to the RequestExecution entity.
func (_u *ObservabilityPayloadUpdate) ClearRequestBodyExecutions() *ObservabilityPayloadUpdate {
	_u.mutation.ClearRequestBodyExecutions()
	return _u
}

// RemoveRequestBodyExecutionIDs removes the "request_body_executions" edge to RequestExecution entities by IDs.
func (_u *ObservabilityPayloadUpdate) RemoveRequestBodyExecutionIDs(ids ...int) *ObservabilityPayloadUpdate {
	_u.mutation.RemoveRequestBodyExecutionIDs(ids...)
	return _u
}

// RemoveRequestBodyExecutions removes "request_body_executions" edges to RequestExecution entities.
func (_u *ObservabilityPayloadUpdate) RemoveRequestBodyExecutions(v ...*RequestExecution) *ObservabilityPayloadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestBodyExecutionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ObservabilityPayloadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObservabilityPayloadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ObservabilityPayloadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObservabilityPayloadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObservabilityPayloadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := observabilitypayload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ObservabilityPayloadUpdate) check() error {
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ObservabilityPayload.request"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ObservabilityPayloadUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ObservabilityPayloadUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ObservabilityPayloadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(observabilitypayload.Table, observabilitypayload.Columns, sqlgraph.NewFieldSpec(observabilitypayload.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(observabilitypayload.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestBodyRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyRequestsTable,
			Columns: []string{observabilitypayload.RequestBodyRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestBodyRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestBodyRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyRequestsTable,
			Columns: []string{observabilitypayload.RequestBodyRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestBodyRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyRequestsTable,
			Columns: []string{observabilitypayload.RequestBodyRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestBodyExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyExecutionsTable,
			Columns: []string{observabilitypayload.RequestBodyExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestBodyExecutionsIDs(); len(nodes) > 0 && !_u.mutation.RequestBodyExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyExecutionsTable,
			Columns: []string{observabilitypayload.RequestBodyExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestBodyExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyExecutionsTable,
			Columns: []string{observabilitypayload.RequestBodyExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{observabilitypayload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ObservabilityPayloadUpdateOne is the builder for updating a single ObservabilityPayload entity.
type ObservabilityPayloadUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ObservabilityPayloadMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObservabilityPayloadUpdateOne) SetUpdatedAt(v time.Time) *ObservabilityPayloadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRequestBodyRequestIDs adds the "request_body_requests" edge to the Request entity by IDs.
func (_u *ObservabilityPayloadUpdateOne) AddRequestBodyRequestIDs(ids ...int) *ObservabilityPayloadUpdateOne {
	_u.mutation.AddRequestBodyRequestIDs(ids...)
	return _u
}

// AddRequestBodyRequests adds the "request_body_requests" edges to the Request entity.
func (_u *ObservabilityPayloadUpdateOne) AddRequestBodyRequests(v ...*Request) *ObservabilityPayloadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestBodyRequestIDs(ids...)
}

// AddRequestBodyExecutionIDs adds the "request_body_executions" edge to the RequestExecution entity by IDs.
func (_u *ObservabilityPayloadUpdateOne) AddRequestBodyExecutionIDs(ids ...int) *ObservabilityPayloadUpdateOne {
	_u.mutation.AddRequestBodyExecutionIDs(ids...)
	return _u
}

// AddRequestBodyExecutions adds the "request_body_executions" edges to the RequestExecution entity.
func (_u *ObservabilityPayloadUpdateOne) AddRequestBodyExecutions(v ...*RequestExecution) *ObservabilityPayloadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestBodyExecutionIDs(ids...)
}

// Mutation returns the ObservabilityPayloadMutation object of the builder.
func (_u *ObservabilityPayloadUpdateOne) Mutation() *ObservabilityPayloadMutation {
	return _u.mutation
}

// ClearRequestBodyRequests clears all "request_body_requests" edges to the Request entity.
func (_u *ObservabilityPayloadUpdateOne) ClearRequestBodyRequests() *ObservabilityPayloadUpdateOne {
	_u.mutation.ClearRequestBodyRequests()
	return _u
}

// RemoveRequestBodyRequestIDs removes the "request_body_requests" edge to Request entities by IDs.
func (_u *ObservabilityPayloadUpdateOne) RemoveRequestBodyRequestIDs(ids ...int) *ObservabilityPayloadUpdateOne {
	_u.mutation.RemoveRequestBodyRequestIDs(ids...)
	return _u
}

// RemoveRequestBodyRequests removes "request_body_requests" edges to Request entities.
func (_u *ObservabilityPayloadUpdateOne) RemoveRequestBodyRequests(v ...*Request) *ObservabilityPayloadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestBodyRequestIDs(ids...)
}

// ClearRequestBodyExecutions clears all "request_body_executions" edges to the RequestExecution entity.
func (_u *ObservabilityPayloadUpdateOne) ClearRequestBodyExecutions() *ObservabilityPayloadUpdateOne {
	_u.mutation.ClearRequestBodyExecutions()
	return _u
}

// RemoveRequestBodyExecutionIDs removes the "request_body_executions" edge to RequestExecution entities by IDs.
func (_u *ObservabilityPayloadUpdateOne) RemoveRequestBodyExecutionIDs(ids ...int) *ObservabilityPayloadUpdateOne {
	_u.mutation.RemoveRequestBodyExecutionIDs(ids...)
	return _u
}

// RemoveRequestBodyExecutions removes "request_body_executions" edges to RequestExecution entities.
func (_u *ObservabilityPayloadUpdateOne) RemoveRequestBodyExecutions(v ...*RequestExecution) *ObservabilityPayloadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestBodyExecutionIDs(ids...)
}

// Where appends a list predicates to the ObservabilityPayloadUpdate builder.
func (_u *ObservabilityPayloadUpdateOne) Where(ps ...predicate.ObservabilityPayload) *ObservabilityPayloadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ObservabilityPayloadUpdateOne) Select(field string, fields ...string) *ObservabilityPayloadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ObservabilityPayload entity.
func (_u *ObservabilityPayloadUpdateOne) Save(ctx context.Context) (*ObservabilityPayload, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObservabilityPayloadUpdateOne) SaveX(ctx context.Context) *ObservabilityPayload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ObservabilityPayloadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObservabilityPayloadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObservabilityPayloadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := observabilitypayload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ObservabilityPayloadUpdateOne) check() error {
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ObservabilityPayload.request"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ObservabilityPayloadUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ObservabilityPayloadUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ObservabilityPayloadUpdateOne) sqlSave(ctx context.Context) (_node *ObservabilityPayload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(observabilitypayload.Table, observabilitypayload.Columns, sqlgraph.NewFieldSpec(observabilitypayload.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ObservabilityPayload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, observabilitypayload.FieldID)
		for _, f := range fields {
			if !observabilitypayload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != observabilitypayload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(observabilitypayload.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestBodyRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyRequestsTable,
			Columns: []string{observabilitypayload.RequestBodyRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestBodyRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestBodyRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyRequestsTable,
			Columns: []string{observabilitypayload.RequestBodyRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestBodyRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyRequestsTable,
			Columns: []string{observabilitypayload.RequestBodyRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestBodyExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyExecutionsTable,
			Columns: []string{observabilitypayload.RequestBodyExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestBodyExecutionsIDs(); len(nodes) > 0 && !_u.mutation.RequestBodyExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyExecutionsTable,
			Columns: []string{observabilitypayload.RequestBodyExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestBodyExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   observabilitypayload.RequestBodyExecutionsTable,
			Columns: []string{observabilitypayload.RequestBodyExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ObservabilityPayload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{observabilitypayload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
