// Code generated by ent, DO NOT EDIT.

package channelkeymonitoringevent

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the channelkeymonitoringevent type in the database.
	Label = "channel_key_monitoring_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldChannelName holds the string denoting the channel_name field in the database.
	FieldChannelName = "channel_name"
	// FieldKeyID holds the string denoting the key_id field in the database.
	FieldKeyID = "key_id"
	// FieldMaskedKey holds the string denoting the masked_key field in the database.
	FieldMaskedKey = "masked_key"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldRuleName holds the string denoting the rule_name field in the database.
	FieldRuleName = "rule_name"
	// FieldTrigger holds the string denoting the trigger field in the database.
	FieldTrigger = "trigger"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldSkipped holds the string denoting the skipped field in the database.
	FieldSkipped = "skipped"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldAvailable holds the string denoting the available field in the database.
	FieldAvailable = "available"
	// FieldProbe holds the string denoting the probe field in the database.
	FieldProbe = "probe"
	// FieldMatchedPolicy holds the string denoting the matched_policy field in the database.
	FieldMatchedPolicy = "matched_policy"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldNextCheckAt holds the string denoting the next_check_at field in the database.
	FieldNextCheckAt = "next_check_at"
	// FieldBackoffAttempt holds the string denoting the backoff_attempt field in the database.
	FieldBackoffAttempt = "backoff_attempt"
	// FieldCheckedAt holds the string denoting the checked_at field in the database.
	FieldCheckedAt = "checked_at"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// Table holds the table name of the channelkeymonitoringevent in the database.
	Table = "channel_key_monitoring_events"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "channel_key_monitoring_events"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
)

// Columns holds all SQL columns for channelkeymonitoringevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldChannelID,
	FieldChannelName,
	FieldKeyID,
	FieldMaskedKey,
	FieldRuleID,
	FieldRuleName,
	FieldTrigger,
	FieldSource,
	FieldSuccess,
	FieldSkipped,
	FieldReason,
	FieldStatusCode,
	FieldBalance,
	FieldCurrency,
	FieldAvailable,
	FieldProbe,
	FieldMatchedPolicy,
	FieldAction,
	FieldNextCheckAt,
	FieldBackoffAttempt,
	FieldCheckedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTrigger holds the default value on creation for the "trigger" field.
	DefaultTrigger string
	// DefaultSuccess holds the default value on creation for the "success" field.
	DefaultSuccess bool
	// DefaultSkipped holds the default value on creation for the "skipped" field.
	DefaultSkipped bool
)

// OrderOption defines the ordering options for the ChannelKeyMonitoringEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByChannelName orders the results by the channel_name field.
func ByChannelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelName, opts...).ToFunc()
}

// ByKeyID orders the results by the key_id field.
func ByKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyID, opts...).ToFunc()
}

// ByMaskedKey orders the results by the masked_key field.
func ByMaskedKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaskedKey, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// ByRuleName orders the results by the rule_name field.
func ByRuleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleName, opts...).ToFunc()
}

// ByTrigger orders the results by the trigger field.
func ByTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrigger, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySuccess orders the results by the success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// BySkipped orders the results by the skipped field.
func BySkipped(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkipped, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByAvailable orders the results by the available field.
func ByAvailable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailable, opts...).ToFunc()
}

// ByProbe orders the results by the probe field.
func ByProbe(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbe, opts...).ToFunc()
}

// ByMatchedPolicy orders the results by the matched_policy field.
func ByMatchedPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedPolicy, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByNextCheckAt orders the results by the next_check_at field.
func ByNextCheckAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextCheckAt, opts...).ToFunc()
}

// ByBackoffAttempt orders the results by the backoff_attempt field.
func ByBackoffAttempt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackoffAttempt, opts...).ToFunc()
}

// ByCheckedAt orders the results by the checked_at field.
func ByCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedAt, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
