// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contractv1

import (
	"encoding/json"
	"time"
)

type APIKeysData []struct {
	// AccessGroupID corresponds to the JSON schema field "accessGroupId".
	AccessGroupID APIKeysDataElemAccessGroupID `json:"accessGroupId"`

	// AccessGroupRevision corresponds to the JSON schema field "accessGroupRevision".
	AccessGroupRevision APIKeysDataElemAccessGroupRevision `json:"accessGroupRevision"`

	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// Key corresponds to the JSON schema field "key".
	Key Credential `json:"key"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// ProfileMode corresponds to the JSON schema field "profileMode".
	ProfileMode string `json:"profileMode"`

	// Profiles corresponds to the JSON schema field "profiles".
	Profiles *APIKeysDataElemProfiles `json:"profiles"`

	// ProjectID corresponds to the JSON schema field "projectId".
	ProjectID int `json:"projectId"`

	// ProvisioningSource corresponds to the JSON schema field "provisioningSource".
	ProvisioningSource string `json:"provisioningSource"`

	// Scopes corresponds to the JSON schema field "scopes".
	Scopes []string `json:"scopes"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// UpdatedAt corresponds to the JSON schema field "updatedAt".
	UpdatedAt string `json:"updatedAt"`

	// UserID corresponds to the JSON schema field "userId".
	UserID APIKeysDataElemUserID `json:"userId"`
}

type APIKeysDataElemAccessGroupID *int

type APIKeysDataElemAccessGroupRevision *int

type APIKeysDataElemProfiles struct {
	// ActiveProfile corresponds to the JSON schema field "activeProfile".
	ActiveProfile string `json:"activeProfile"`

	// Profiles corresponds to the JSON schema field "profiles".
	Profiles []APIKeysDataElemProfilesProfilesElem `json:"profiles"`
}

type APIKeysDataElemProfilesProfilesElem struct {
	// ChannelIDs corresponds to the JSON schema field "channelIDs".
	ChannelIDs []int `json:"channelIDs,omitempty"`

	// ChannelTags corresponds to the JSON schema field "channelTags".
	ChannelTags []string `json:"channelTags,omitempty"`

	// ChannelTagsMatchMode corresponds to the JSON schema field
	// "channelTagsMatchMode".
	ChannelTagsMatchMode *string `json:"channelTagsMatchMode,omitempty"`

	// LoadBalanceStrategy corresponds to the JSON schema field "loadBalanceStrategy".
	LoadBalanceStrategy APIKeysDataElemProfilesProfilesElemLoadBalanceStrategy `json:"loadBalanceStrategy,omitempty"`

	// ModelIDs corresponds to the JSON schema field "modelIDs".
	ModelIDs []string `json:"modelIDs,omitempty"`

	// ModelMappings corresponds to the JSON schema field "modelMappings".
	ModelMappings []APIKeysDataElemProfilesProfilesElemModelMappingsElem `json:"modelMappings"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Quota corresponds to the JSON schema field "quota".
	Quota *APIKeysDataElemProfilesProfilesElemQuota `json:"quota,omitempty"`
}

type APIKeysDataElemProfilesProfilesElemLoadBalanceStrategy *string

type APIKeysDataElemProfilesProfilesElemModelMappingsElem struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// To corresponds to the JSON schema field "to".
	To string `json:"to"`
}

type APIKeysDataElemProfilesProfilesElemQuota struct {
	// Cost corresponds to the JSON schema field "cost".
	Cost *APIKeysDataElemProfilesProfilesElemQuotaCost `json:"cost,omitempty"`

	// Period corresponds to the JSON schema field "period".
	Period APIKeysDataElemProfilesProfilesElemQuotaPeriod `json:"period"`

	// Requests corresponds to the JSON schema field "requests".
	Requests APIKeysDataElemProfilesProfilesElemQuotaRequests `json:"requests,omitempty"`

	// TotalTokens corresponds to the JSON schema field "totalTokens".
	TotalTokens APIKeysDataElemProfilesProfilesElemQuotaTotalTokens `json:"totalTokens,omitempty"`
}

type APIKeysDataElemProfilesProfilesElemQuotaCost map[string]interface{}

type APIKeysDataElemProfilesProfilesElemQuotaPeriod struct {
	// CalendarDuration corresponds to the JSON schema field "calendarDuration".
	CalendarDuration *APIKeysDataElemProfilesProfilesElemQuotaPeriodCalendarDuration `json:"calendarDuration,omitempty"`

	// PastDuration corresponds to the JSON schema field "pastDuration".
	PastDuration *APIKeysDataElemProfilesProfilesElemQuotaPeriodPastDuration `json:"pastDuration,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type APIKeysDataElemProfilesProfilesElemQuotaPeriodCalendarDuration struct {
	// Unit corresponds to the JSON schema field "unit".
	Unit string `json:"unit"`
}

type APIKeysDataElemProfilesProfilesElemQuotaPeriodPastDuration struct {
	// Unit corresponds to the JSON schema field "unit".
	Unit string `json:"unit"`

	// Value corresponds to the JSON schema field "value".
	Value int `json:"value"`
}

type APIKeysDataElemProfilesProfilesElemQuotaRequests *int

type APIKeysDataElemProfilesProfilesElemQuotaTotalTokens *int

type APIKeysDataElemUserID *int

type APIKeysSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status APIKeysSectionStatus `json:"status"`
}

type APIKeysSectionStatus string

const APIKeysSectionStatusAvailable APIKeysSectionStatus = "available"
const APIKeysSectionStatusNotRequested APIKeysSectionStatus = "notRequested"
const APIKeysSectionStatusPartial APIKeysSectionStatus = "partial"
const APIKeysSectionStatusUnavailable APIKeysSectionStatus = "unavailable"

type AccessGroupsData []struct {
	// AttachedKeyCount corresponds to the JSON schema field "attachedKeyCount".
	AttachedKeyCount int `json:"attachedKeyCount"`

	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Profile corresponds to the JSON schema field "profile".
	Profile *AccessGroupsDataElemProfile `json:"profile"`

	// ProjectID corresponds to the JSON schema field "projectId".
	ProjectID int `json:"projectId"`

	// ReferencedRevisions corresponds to the JSON schema field "referencedRevisions".
	ReferencedRevisions []AccessGroupsDataElemReferencedRevisionsElem `json:"referencedRevisions"`

	// Revision corresponds to the JSON schema field "revision".
	Revision int `json:"revision"`

	// SelfServiceVisible corresponds to the JSON schema field "selfServiceVisible".
	SelfServiceVisible bool `json:"selfServiceVisible"`

	// UpdatedAt corresponds to the JSON schema field "updatedAt".
	UpdatedAt string `json:"updatedAt"`
}

type AccessGroupsDataElemProfile struct {
	// ChannelIDs corresponds to the JSON schema field "channelIDs".
	ChannelIDs []int `json:"channelIDs,omitempty"`

	// ChannelTags corresponds to the JSON schema field "channelTags".
	ChannelTags []string `json:"channelTags,omitempty"`

	// ChannelTagsMatchMode corresponds to the JSON schema field
	// "channelTagsMatchMode".
	ChannelTagsMatchMode *string `json:"channelTagsMatchMode,omitempty"`

	// LoadBalanceStrategy corresponds to the JSON schema field "loadBalanceStrategy".
	LoadBalanceStrategy AccessGroupsDataElemProfileLoadBalanceStrategy `json:"loadBalanceStrategy,omitempty"`

	// ModelIDs corresponds to the JSON schema field "modelIDs".
	ModelIDs []string `json:"modelIDs,omitempty"`

	// ModelMappings corresponds to the JSON schema field "modelMappings".
	ModelMappings []AccessGroupsDataElemProfileModelMappingsElem `json:"modelMappings"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Quota corresponds to the JSON schema field "quota".
	Quota *AccessGroupsDataElemProfileQuota `json:"quota,omitempty"`
}

type AccessGroupsDataElemProfileLoadBalanceStrategy *string

type AccessGroupsDataElemProfileModelMappingsElem struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// To corresponds to the JSON schema field "to".
	To string `json:"to"`
}

type AccessGroupsDataElemProfileQuota struct {
	// Cost corresponds to the JSON schema field "cost".
	Cost *AccessGroupsDataElemProfileQuotaCost `json:"cost,omitempty"`

	// Period corresponds to the JSON schema field "period".
	Period AccessGroupsDataElemProfileQuotaPeriod `json:"period"`

	// Requests corresponds to the JSON schema field "requests".
	Requests AccessGroupsDataElemProfileQuotaRequests `json:"requests,omitempty"`

	// TotalTokens corresponds to the JSON schema field "totalTokens".
	TotalTokens AccessGroupsDataElemProfileQuotaTotalTokens `json:"totalTokens,omitempty"`
}

type AccessGroupsDataElemProfileQuotaCost map[string]interface{}

type AccessGroupsDataElemProfileQuotaPeriod struct {
	// CalendarDuration corresponds to the JSON schema field "calendarDuration".
	CalendarDuration *AccessGroupsDataElemProfileQuotaPeriodCalendarDuration `json:"calendarDuration,omitempty"`

	// PastDuration corresponds to the JSON schema field "pastDuration".
	PastDuration *AccessGroupsDataElemProfileQuotaPeriodPastDuration `json:"pastDuration,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type AccessGroupsDataElemProfileQuotaPeriodCalendarDuration struct {
	// Unit corresponds to the JSON schema field "unit".
	Unit string `json:"unit"`
}

type AccessGroupsDataElemProfileQuotaPeriodPastDuration struct {
	// Unit corresponds to the JSON schema field "unit".
	Unit string `json:"unit"`

	// Value corresponds to the JSON schema field "value".
	Value int `json:"value"`
}

type AccessGroupsDataElemProfileQuotaRequests *int

type AccessGroupsDataElemProfileQuotaTotalTokens *int

type AccessGroupsDataElemReferencedRevisionsElem struct {
	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// CreatedByUserID corresponds to the JSON schema field "createdByUserId".
	CreatedByUserID AccessGroupsDataElemReferencedRevisionsElemCreatedByUserID `json:"createdByUserId"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Profile corresponds to the JSON schema field "profile".
	Profile *AccessGroupsDataElemReferencedRevisionsElemProfile `json:"profile"`

	// Revision corresponds to the JSON schema field "revision".
	Revision int `json:"revision"`
}

type AccessGroupsDataElemReferencedRevisionsElemCreatedByUserID *int

type AccessGroupsDataElemReferencedRevisionsElemProfile struct {
	// ChannelIDs corresponds to the JSON schema field "channelIDs".
	ChannelIDs []int `json:"channelIDs,omitempty"`

	// ChannelTags corresponds to the JSON schema field "channelTags".
	ChannelTags []string `json:"channelTags,omitempty"`

	// ChannelTagsMatchMode corresponds to the JSON schema field
	// "channelTagsMatchMode".
	ChannelTagsMatchMode *string `json:"channelTagsMatchMode,omitempty"`

	// LoadBalanceStrategy corresponds to the JSON schema field "loadBalanceStrategy".
	LoadBalanceStrategy AccessGroupsDataElemReferencedRevisionsElemProfileLoadBalanceStrategy `json:"loadBalanceStrategy,omitempty"`

	// ModelIDs corresponds to the JSON schema field "modelIDs".
	ModelIDs []string `json:"modelIDs,omitempty"`

	// ModelMappings corresponds to the JSON schema field "modelMappings".
	ModelMappings []AccessGroupsDataElemReferencedRevisionsElemProfileModelMappingsElem `json:"modelMappings"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Quota corresponds to the JSON schema field "quota".
	Quota *AccessGroupsDataElemReferencedRevisionsElemProfileQuota `json:"quota,omitempty"`
}

type AccessGroupsDataElemReferencedRevisionsElemProfileLoadBalanceStrategy *string

type AccessGroupsDataElemReferencedRevisionsElemProfileModelMappingsElem struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// To corresponds to the JSON schema field "to".
	To string `json:"to"`
}

type AccessGroupsDataElemReferencedRevisionsElemProfileQuota struct {
	// Cost corresponds to the JSON schema field "cost".
	Cost *AccessGroupsDataElemReferencedRevisionsElemProfileQuotaCost `json:"cost,omitempty"`

	// Period corresponds to the JSON schema field "period".
	Period AccessGroupsDataElemReferencedRevisionsElemProfileQuotaPeriod `json:"period"`

	// Requests corresponds to the JSON schema field "requests".
	Requests AccessGroupsDataElemReferencedRevisionsElemProfileQuotaRequests `json:"requests,omitempty"`

	// TotalTokens corresponds to the JSON schema field "totalTokens".
	TotalTokens AccessGroupsDataElemReferencedRevisionsElemProfileQuotaTotalTokens `json:"totalTokens,omitempty"`
}

type AccessGroupsDataElemReferencedRevisionsElemProfileQuotaCost map[string]interface{}

type AccessGroupsDataElemReferencedRevisionsElemProfileQuotaPeriod struct {
	// CalendarDuration corresponds to the JSON schema field "calendarDuration".
	CalendarDuration *AccessGroupsDataElemReferencedRevisionsElemProfileQuotaPeriodCalendarDuration `json:"calendarDuration,omitempty"`

	// PastDuration corresponds to the JSON schema field "pastDuration".
	PastDuration *AccessGroupsDataElemReferencedRevisionsElemProfileQuotaPeriodPastDuration `json:"pastDuration,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type AccessGroupsDataElemReferencedRevisionsElemProfileQuotaPeriodCalendarDuration struct {
	// Unit corresponds to the JSON schema field "unit".
	Unit string `json:"unit"`
}

type AccessGroupsDataElemReferencedRevisionsElemProfileQuotaPeriodPastDuration struct {
	// Unit corresponds to the JSON schema field "unit".
	Unit string `json:"unit"`

	// Value corresponds to the JSON schema field "value".
	Value int `json:"value"`
}

type AccessGroupsDataElemReferencedRevisionsElemProfileQuotaRequests *int

type AccessGroupsDataElemReferencedRevisionsElemProfileQuotaTotalTokens *int

type AccessGroupsSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status AccessGroupsSectionStatus `json:"status"`
}

type AccessGroupsSectionStatus string

const AccessGroupsSectionStatusAvailable AccessGroupsSectionStatus = "available"
const AccessGroupsSectionStatusNotRequested AccessGroupsSectionStatus = "notRequested"
const AccessGroupsSectionStatusPartial AccessGroupsSectionStatus = "partial"
const AccessGroupsSectionStatusUnavailable AccessGroupsSectionStatus = "unavailable"

type Authorization struct {
	// CredentialsIncluded corresponds to the JSON schema field "credentialsIncluded".
	CredentialsIncluded bool `json:"credentialsIncluded"`

	// PersonalDataExcluded corresponds to the JSON schema field
	// "personalDataExcluded".
	PersonalDataExcluded bool `json:"personalDataExcluded"`

	// PrincipalID corresponds to the JSON schema field "principalId".
	PrincipalID int `json:"principalId"`

	// PrincipalType corresponds to the JSON schema field "principalType".
	PrincipalType AuthorizationPrincipalType `json:"principalType"`

	// ProjectID corresponds to the JSON schema field "projectId".
	ProjectID int `json:"projectId"`

	// SubjectUserID corresponds to the JSON schema field "subjectUserId".
	SubjectUserID AuthorizationSubjectUserID `json:"subjectUserId"`
}

type AuthorizationPrincipalType string

const AuthorizationPrincipalTypeServiceAccount AuthorizationPrincipalType = "serviceAccount"
const AuthorizationPrincipalTypeUser AuthorizationPrincipalType = "user"

type AuthorizationSubjectUserID *int

type Bundle struct {
	// GeneratedAt corresponds to the JSON schema field "generatedAt".
	GeneratedAt time.Time `json:"generatedAt"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// PageGeneratedAt corresponds to the JSON schema field "pageGeneratedAt".
	PageGeneratedAt time.Time `json:"pageGeneratedAt"`

	// PageIndex corresponds to the JSON schema field "pageIndex".
	PageIndex int `json:"pageIndex"`

	// Status corresponds to the JSON schema field "status".
	Status BundleStatus `json:"status"`
}

type BundleStatus string

const BundleStatusComplete BundleStatus = "complete"
const BundleStatusPartial BundleStatus = "partial"

type ChannelsData []struct {
	// AutoSyncModelPattern corresponds to the JSON schema field
	// "autoSyncModelPattern".
	AutoSyncModelPattern string `json:"autoSyncModelPattern"`

	// AutoSyncSupportedModels corresponds to the JSON schema field
	// "autoSyncSupportedModels".
	AutoSyncSupportedModels bool `json:"autoSyncSupportedModels"`

	// BaseURL corresponds to the JSON schema field "baseUrl".
	BaseURL ChannelsDataElemBaseURL `json:"baseUrl"`

	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// Credentials corresponds to the JSON schema field "credentials".
	Credentials Credential `json:"credentials"`

	// DefaultTestModel corresponds to the JSON schema field "defaultTestModel".
	DefaultTestModel string `json:"defaultTestModel"`

	// DisabledAPIKeys corresponds to the JSON schema field "disabledApiKeys".
	DisabledAPIKeys Credential `json:"disabledApiKeys"`

	// Endpoints corresponds to the JSON schema field "endpoints".
	Endpoints []ChannelsDataElemEndpointsElem `json:"endpoints"`

	// ErrorMessage corresponds to the JSON schema field "errorMessage".
	ErrorMessage ChannelsDataElemErrorMessage `json:"errorMessage"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// ManualModels corresponds to the JSON schema field "manualModels".
	ManualModels []string `json:"manualModels"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// OrderingWeight corresponds to the JSON schema field "orderingWeight".
	OrderingWeight int `json:"orderingWeight"`

	// Policies corresponds to the JSON schema field "policies".
	Policies ChannelsDataElemPolicies `json:"policies"`

	// Remark corresponds to the JSON schema field "remark".
	Remark ChannelsDataElemRemark `json:"remark"`

	// Settings corresponds to the JSON schema field "settings".
	Settings *ChannelsDataElemSettings `json:"settings"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`

	// SupportedModels corresponds to the JSON schema field "supportedModels".
	SupportedModels []string `json:"supportedModels"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// UpdatedAt corresponds to the JSON schema field "updatedAt".
	UpdatedAt string `json:"updatedAt"`
}

type ChannelsDataElemBaseURL struct {
	// Base corresponds to the JSON schema field "base".
	Base string `json:"base"`

	// Query corresponds to the JSON schema field "query".
	Query Credential `json:"query"`

	// UserInfo corresponds to the JSON schema field "userInfo".
	UserInfo Credential `json:"userInfo"`
}

type ChannelsDataElemEndpointsElem struct {
	// APIFormat corresponds to the JSON schema field "apiFormat".
	APIFormat string `json:"apiFormat"`

	// BaseURL corresponds to the JSON schema field "baseUrl".
	BaseURL ChannelsDataElemEndpointsElemBaseURL `json:"baseUrl"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Transport corresponds to the JSON schema field "transport".
	Transport string `json:"transport"`
}

type ChannelsDataElemEndpointsElemBaseURL struct {
	// Base corresponds to the JSON schema field "base".
	Base string `json:"base"`

	// Query corresponds to the JSON schema field "query".
	Query Credential `json:"query"`

	// UserInfo corresponds to the JSON schema field "userInfo".
	UserInfo Credential `json:"userInfo"`
}

type ChannelsDataElemErrorMessage *string

type ChannelsDataElemPolicies struct {
	// Stream corresponds to the JSON schema field "stream".
	Stream *string `json:"stream,omitempty"`
}

type ChannelsDataElemRemark *string

type ChannelsDataElemSettings struct {
	// AutoTrimedModelPrefixes corresponds to the JSON schema field
	// "autoTrimedModelPrefixes".
	AutoTrimedModelPrefixes []string `json:"autoTrimedModelPrefixes"`

	// BodyOverrideOperations corresponds to the JSON schema field
	// "bodyOverrideOperations".
	BodyOverrideOperations []ChannelsDataElemSettingsBodyOverrideOperationsElem `json:"bodyOverrideOperations,omitempty"`

	// DisableRetries corresponds to the JSON schema field "disableRetries".
	DisableRetries *bool `json:"disableRetries,omitempty"`

	// ExtraModelPrefix corresponds to the JSON schema field "extraModelPrefix".
	ExtraModelPrefix string `json:"extraModelPrefix"`

	// FullPassThrough corresponds to the JSON schema field "fullPassThrough".
	FullPassThrough *bool `json:"fullPassThrough,omitempty"`

	// HeaderOverrideOperations corresponds to the JSON schema field
	// "headerOverrideOperations".
	HeaderOverrideOperations []ChannelsDataElemSettingsHeaderOverrideOperationsElem `json:"headerOverrideOperations,omitempty"`

	// HideMappedModels corresponds to the JSON schema field "hideMappedModels".
	HideMappedModels bool `json:"hideMappedModels"`

	// HideOriginalModels corresponds to the JSON schema field "hideOriginalModels".
	HideOriginalModels bool `json:"hideOriginalModels"`

	// LowercaseModelID corresponds to the JSON schema field "lowercaseModelId".
	LowercaseModelID bool `json:"lowercaseModelId"`

	// ModelMappings corresponds to the JSON schema field "modelMappings".
	ModelMappings []ChannelsDataElemSettingsModelMappingsElem `json:"modelMappings"`

	// OverrideHeaders corresponds to the JSON schema field "overrideHeaders".
	OverrideHeaders []ChannelsDataElemSettingsOverrideHeadersElem `json:"overrideHeaders"`

	// OverrideParameters corresponds to the JSON schema field "overrideParameters".
	OverrideParameters Credential `json:"overrideParameters"`

	// PassThroughBody corresponds to the JSON schema field "passThroughBody".
	PassThroughBody ChannelsDataElemSettingsPassThroughBody `json:"passThroughBody,omitempty"`

	// PassThroughUserAgent corresponds to the JSON schema field
	// "passThroughUserAgent".
	PassThroughUserAgent ChannelsDataElemSettingsPassThroughUserAgent `json:"passThroughUserAgent,omitempty"`

	// ProviderQuota corresponds to the JSON schema field "providerQuota".
	ProviderQuota *ChannelsDataElemSettingsProviderQuota `json:"providerQuota,omitempty"`

	// Proxy corresponds to the JSON schema field "proxy".
	Proxy *ChannelsDataElemSettingsProxy `json:"proxy,omitempty"`

	// RateLimit corresponds to the JSON schema field "rateLimit".
	RateLimit *ChannelsDataElemSettingsRateLimit `json:"rateLimit,omitempty"`

	// RetryableErrorPatterns corresponds to the JSON schema field
	// "retryableErrorPatterns".
	RetryableErrorPatterns []ChannelsDataElemSettingsRetryableErrorPatternsElem `json:"retryableErrorPatterns,omitempty"`

	// RetryableStatusCodes corresponds to the JSON schema field
	// "retryableStatusCodes".
	RetryableStatusCodes []int `json:"retryableStatusCodes,omitempty"`

	// StoreExecutionRequestBody corresponds to the JSON schema field
	// "storeExecutionRequestBody".
	StoreExecutionRequestBody ChannelsDataElemSettingsStoreExecutionRequestBody `json:"storeExecutionRequestBody,omitempty"`

	// StoreExecutionResponseBody corresponds to the JSON schema field
	// "storeExecutionResponseBody".
	StoreExecutionResponseBody ChannelsDataElemSettingsStoreExecutionResponseBody `json:"storeExecutionResponseBody,omitempty"`

	// StoreExecutionStreamChunks corresponds to the JSON schema field
	// "storeExecutionStreamChunks".
	StoreExecutionStreamChunks ChannelsDataElemSettingsStoreExecutionStreamChunks `json:"storeExecutionStreamChunks,omitempty"`

	// TransformOptions corresponds to the JSON schema field "transformOptions".
	TransformOptions ChannelsDataElemSettingsTransformOptions `json:"transformOptions"`
}

type ChannelsDataElemSettingsBodyOverrideOperationsElem struct {
	// Condition corresponds to the JSON schema field "condition".
	Condition *string `json:"condition,omitempty"`

	// From corresponds to the JSON schema field "from".
	From *string `json:"from,omitempty"`

	// Index corresponds to the JSON schema field "index".
	Index ChannelsDataElemSettingsBodyOverrideOperationsElemIndex `json:"index,omitempty"`

	// Match corresponds to the JSON schema field "match".
	Match *ChannelsDataElemSettingsBodyOverrideOperationsElemMatch `json:"match,omitempty"`

	// Op corresponds to the JSON schema field "op".
	Op string `json:"op"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty"`

	// Splat corresponds to the JSON schema field "splat".
	Splat ChannelsDataElemSettingsBodyOverrideOperationsElemSplat `json:"splat,omitempty"`

	// To corresponds to the JSON schema field "to".
	To *string `json:"to,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value *Credential `json:"value,omitempty"`
}

type ChannelsDataElemSettingsBodyOverrideOperationsElemIndex *int

type ChannelsDataElemSettingsBodyOverrideOperationsElemMatch struct {
	// Eq corresponds to the JSON schema field "eq".
	Eq Credential `json:"eq"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type ChannelsDataElemSettingsBodyOverrideOperationsElemSplat *bool

type ChannelsDataElemSettingsHeaderOverrideOperationsElem struct {
	// Condition corresponds to the JSON schema field "condition".
	Condition *string `json:"condition,omitempty"`

	// From corresponds to the JSON schema field "from".
	From *string `json:"from,omitempty"`

	// Index corresponds to the JSON schema field "index".
	Index ChannelsDataElemSettingsHeaderOverrideOperationsElemIndex `json:"index,omitempty"`

	// Match corresponds to the JSON schema field "match".
	Match *ChannelsDataElemSettingsHeaderOverrideOperationsElemMatch `json:"match,omitempty"`

	// Op corresponds to the JSON schema field "op".
	Op string `json:"op"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty"`

	// Splat corresponds to the JSON schema field "splat".
	Splat ChannelsDataElemSettingsHeaderOverrideOperationsElemSplat `json:"splat,omitempty"`

	// To corresponds to the JSON schema field "to".
	To *string `json:"to,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value *Credential `json:"value,omitempty"`
}

type ChannelsDataElemSettingsHeaderOverrideOperationsElemIndex *int

type ChannelsDataElemSettingsHeaderOverrideOperationsElemMatch struct {
	// Eq corresponds to the JSON schema field "eq".
	Eq Credential `json:"eq"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type ChannelsDataElemSettingsHeaderOverrideOperationsElemSplat *bool

type ChannelsDataElemSettingsModelMappingsElem struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// To corresponds to the JSON schema field "to".
	To string `json:"to"`
}

type ChannelsDataElemSettingsOverrideHeadersElem struct {
	// Key corresponds to the JSON schema field "key".
	Key string `json:"key"`

	// Value corresponds to the JSON schema field "value".
	Value Credential `json:"value"`
}

type ChannelsDataElemSettingsPassThroughBody *bool

type ChannelsDataElemSettingsPassThroughUserAgent *bool

type ChannelsDataElemSettingsProviderQuota struct {
	// OpencodeGo corresponds to the JSON schema field "opencodeGo".
	OpencodeGo *ChannelsDataElemSettingsProviderQuotaOpencodeGo `json:"opencodeGo,omitempty"`
}

type ChannelsDataElemSettingsProviderQuotaOpencodeGo struct {
	// AuthCookie corresponds to the JSON schema field "authCookie".
	AuthCookie Credential `json:"authCookie"`

	// WorkspaceID corresponds to the JSON schema field "workspaceId".
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

type ChannelsDataElemSettingsProxy struct {
	// Password corresponds to the JSON schema field "password".
	Password Credential `json:"password"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// URL corresponds to the JSON schema field "url".
	URL ChannelsDataElemSettingsProxyURL `json:"url"`

	// Username corresponds to the JSON schema field "username".
	Username Credential `json:"username"`
}

type ChannelsDataElemSettingsProxyURL struct {
	// Base corresponds to the JSON schema field "base".
	Base string `json:"base"`

	// Query corresponds to the JSON schema field "query".
	Query Credential `json:"query"`

	// UserInfo corresponds to the JSON schema field "userInfo".
	UserInfo Credential `json:"userInfo"`
}

type ChannelsDataElemSettingsRateLimit struct {
	// MaxConcurrent corresponds to the JSON schema field "maxConcurrent".
	MaxConcurrent ChannelsDataElemSettingsRateLimitMaxConcurrent `json:"maxConcurrent,omitempty"`

	// QueueSize corresponds to the JSON schema field "queueSize".
	QueueSize ChannelsDataElemSettingsRateLimitQueueSize `json:"queueSize,omitempty"`

	// QueueTimeoutMs corresponds to the JSON schema field "queueTimeoutMs".
	QueueTimeoutMs ChannelsDataElemSettingsRateLimitQueueTimeoutMs `json:"queueTimeoutMs,omitempty"`

	// Rpm corresponds to the JSON schema field "rpm".
	Rpm ChannelsDataElemSettingsRateLimitRpm `json:"rpm,omitempty"`

	// Tpm corresponds to the JSON schema field "tpm".
	Tpm ChannelsDataElemSettingsRateLimitTpm `json:"tpm,omitempty"`
}

type ChannelsDataElemSettingsRateLimitMaxConcurrent *int

type ChannelsDataElemSettingsRateLimitQueueSize *int

type ChannelsDataElemSettingsRateLimitQueueTimeoutMs *int

type ChannelsDataElemSettingsRateLimitRpm *int

type ChannelsDataElemSettingsRateLimitTpm *int

type ChannelsDataElemSettingsRetryableErrorPatternsElem struct {
	// Pattern corresponds to the JSON schema field "pattern".
	Pattern string `json:"pattern"`

	// Regex corresponds to the JSON schema field "regex".
	Regex *bool `json:"regex,omitempty"`
}

type ChannelsDataElemSettingsStoreExecutionRequestBody *bool

type ChannelsDataElemSettingsStoreExecutionResponseBody *bool

type ChannelsDataElemSettingsStoreExecutionStreamChunks *bool

type ChannelsDataElemSettingsTransformOptions struct {
	// ForceArrayInputs corresponds to the JSON schema field "forceArrayInputs".
	ForceArrayInputs bool `json:"forceArrayInputs"`

	// ForceArrayInstructions corresponds to the JSON schema field
	// "forceArrayInstructions".
	ForceArrayInstructions bool `json:"forceArrayInstructions"`

	// ReasoningEffortMapping corresponds to the JSON schema field
	// "reasoningEffortMapping".
	ReasoningEffortMapping []ChannelsDataElemSettingsTransformOptionsReasoningEffortMappingElem `json:"reasoningEffortMapping,omitempty"`

	// ReplaceDeveloperRoleWithSystem corresponds to the JSON schema field
	// "replaceDeveloperRoleWithSystem".
	ReplaceDeveloperRoleWithSystem bool `json:"replaceDeveloperRoleWithSystem"`
}

type ChannelsDataElemSettingsTransformOptionsReasoningEffortMappingElem struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// To corresponds to the JSON schema field "to".
	To string `json:"to"`
}

type ChannelsSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status ChannelsSectionStatus `json:"status"`
}

type ChannelsSectionStatus string

const ChannelsSectionStatusAvailable ChannelsSectionStatus = "available"
const ChannelsSectionStatusNotRequested ChannelsSectionStatus = "notRequested"
const ChannelsSectionStatusPartial ChannelsSectionStatus = "partial"
const ChannelsSectionStatusUnavailable ChannelsSectionStatus = "unavailable"

type Condition struct {
	// Conditions corresponds to the JSON schema field "conditions".
	Conditions []Condition `json:"conditions,omitempty"`

	// Field corresponds to the JSON schema field "field".
	Field *string `json:"field,omitempty"`

	// Logic corresponds to the JSON schema field "logic".
	Logic *string `json:"logic,omitempty"`

	// Operator corresponds to the JSON schema field "operator".
	Operator *string `json:"operator,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type ConditionType `json:"type"`

	// Value corresponds to the JSON schema field "value".
	Value interface{} `json:"value,omitempty"`
}

type ConditionType string

const ConditionTypeCondition ConditionType = "condition"
const ConditionTypeGroup ConditionType = "group"

type ConfigurationData struct {
	// BodyPassThrough corresponds to the JSON schema field "bodyPassThrough".
	BodyPassThrough bool `json:"bodyPassThrough"`

	// DataStorages corresponds to the JSON schema field "dataStorages".
	DataStorages []ConfigurationDataDataStoragesElem `json:"dataStorages"`

	// DefaultDataStorageID corresponds to the JSON schema field
	// "defaultDataStorageId".
	DefaultDataStorageID ConfigurationDataDefaultDataStorageID `json:"defaultDataStorageId"`

	// ModelSettings corresponds to the JSON schema field "modelSettings".
	ModelSettings ConfigurationDataModelSettings `json:"modelSettings"`

	// Registration corresponds to the JSON schema field "registration".
	Registration ConfigurationDataRegistration `json:"registration"`

	// RetryPolicy corresponds to the JSON schema field "retryPolicy".
	RetryPolicy ConfigurationDataRetryPolicy `json:"retryPolicy"`

	// StoragePolicy corresponds to the JSON schema field "storagePolicy".
	StoragePolicy ConfigurationDataStoragePolicy `json:"storagePolicy"`

	// UserAgentPassThrough corresponds to the JSON schema field
	// "userAgentPassThrough".
	UserAgentPassThrough bool `json:"userAgentPassThrough"`
}

type ConfigurationDataDataStoragesElem struct {
	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Primary corresponds to the JSON schema field "primary".
	Primary bool `json:"primary"`

	// Settings corresponds to the JSON schema field "settings".
	Settings ConfigurationDataDataStoragesElemSettings `json:"settings"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// UpdatedAt corresponds to the JSON schema field "updatedAt".
	UpdatedAt string `json:"updatedAt"`
}

type ConfigurationDataDataStoragesElemSettings struct {
	// Directory corresponds to the JSON schema field "directory".
	Directory ConfigurationDataDataStoragesElemSettingsDirectory `json:"directory"`

	// Dsn corresponds to the JSON schema field "dsn".
	Dsn Credential `json:"dsn"`

	// Gcs corresponds to the JSON schema field "gcs".
	Gcs *ConfigurationDataDataStoragesElemSettingsGcs `json:"gcs"`

	// S3 corresponds to the JSON schema field "s3".
	S3 *ConfigurationDataDataStoragesElemSettingsS3 `json:"s3"`

	// Webdav corresponds to the JSON schema field "webdav".
	Webdav *ConfigurationDataDataStoragesElemSettingsWebdav `json:"webdav"`
}

type ConfigurationDataDataStoragesElemSettingsDirectory *string

type ConfigurationDataDataStoragesElemSettingsGcs struct {
	// BucketName corresponds to the JSON schema field "bucketName".
	BucketName string `json:"bucketName"`

	// Credential corresponds to the JSON schema field "credential".
	Credential Credential `json:"credential"`
}

type ConfigurationDataDataStoragesElemSettingsS3 struct {
	// AccessKey corresponds to the JSON schema field "accessKey".
	AccessKey Credential `json:"accessKey"`

	// BucketName corresponds to the JSON schema field "bucketName".
	BucketName string `json:"bucketName"`

	// Endpoint corresponds to the JSON schema field "endpoint".
	Endpoint ConfigurationDataDataStoragesElemSettingsS3Endpoint `json:"endpoint"`

	// PathStyle corresponds to the JSON schema field "pathStyle".
	PathStyle bool `json:"pathStyle"`

	// Region corresponds to the JSON schema field "region".
	Region string `json:"region"`

	// SecretKey corresponds to the JSON schema field "secretKey".
	SecretKey Credential `json:"secretKey"`
}

type ConfigurationDataDataStoragesElemSettingsS3Endpoint struct {
	// Base corresponds to the JSON schema field "base".
	Base string `json:"base"`

	// Query corresponds to the JSON schema field "query".
	Query Credential `json:"query"`

	// UserInfo corresponds to the JSON schema field "userInfo".
	UserInfo Credential `json:"userInfo"`
}

type ConfigurationDataDataStoragesElemSettingsWebdav struct {
	// InsecureSkipTls corresponds to the JSON schema field "insecureSkipTls".
	InsecureSkipTls bool `json:"insecureSkipTls"`

	// Password corresponds to the JSON schema field "password".
	Password Credential `json:"password"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// URL corresponds to the JSON schema field "url".
	URL ConfigurationDataDataStoragesElemSettingsWebdavURL `json:"url"`

	// Username corresponds to the JSON schema field "username".
	Username Credential `json:"username"`
}

type ConfigurationDataDataStoragesElemSettingsWebdavURL struct {
	// Base corresponds to the JSON schema field "base".
	Base string `json:"base"`

	// Query corresponds to the JSON schema field "query".
	Query Credential `json:"query"`

	// UserInfo corresponds to the JSON schema field "userInfo".
	UserInfo Credential `json:"userInfo"`
}

type ConfigurationDataDefaultDataStorageID *int

type ConfigurationDataModelSettings struct {
	// AutoReasoningEffort corresponds to the JSON schema field
	// "auto_reasoning_effort".
	AutoReasoningEffort bool `json:"auto_reasoning_effort"`

	// DefaultModelAPIIncludeAll corresponds to the JSON schema field
	// "default_model_api_include_all".
	DefaultModelAPIIncludeAll bool `json:"default_model_api_include_all"`

	// DeveloperSettings corresponds to the JSON schema field "developer_settings".
	DeveloperSettings []*ConfigurationDataModelSettingsDeveloperSettingsElem `json:"developer_settings"`

	// FallbackToChannelsOnModelNotFound corresponds to the JSON schema field
	// "fallback_to_channels_on_model_not_found".
	FallbackToChannelsOnModelNotFound bool `json:"fallback_to_channels_on_model_not_found"`

	// ModelBlacklistRegex corresponds to the JSON schema field
	// "model_blacklist_regex".
	ModelBlacklistRegex string `json:"model_blacklist_regex"`

	// QueryAllChannelModels corresponds to the JSON schema field
	// "query_all_channel_models".
	QueryAllChannelModels bool `json:"query_all_channel_models"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElem struct {
	// Associations corresponds to the JSON schema field "associations".
	Associations []*ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElem `json:"associations"`

	// Developer corresponds to the JSON schema field "developer".
	Developer string `json:"developer"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElem struct {
	// ChannelModel corresponds to the JSON schema field "channelModel".
	ChannelModel *ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemChannelModel `json:"channelModel"`

	// ChannelRegex corresponds to the JSON schema field "channelRegex".
	ChannelRegex *ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemChannelRegex `json:"channelRegex"`

	// ChannelTagsModel corresponds to the JSON schema field "channelTagsModel".
	ChannelTagsModel *ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemChannelTagsModel `json:"channelTagsModel"`

	// ChannelTagsRegex corresponds to the JSON schema field "channelTagsRegex".
	ChannelTagsRegex *ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemChannelTagsRegex `json:"channelTagsRegex"`

	// Disabled corresponds to the JSON schema field "disabled".
	Disabled bool `json:"disabled"`

	// ModelID corresponds to the JSON schema field "modelId".
	ModelID *ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemModelID `json:"modelId"`

	// Priority corresponds to the JSON schema field "priority".
	Priority int `json:"priority"`

	// Regex corresponds to the JSON schema field "regex".
	Regex *ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemRegex `json:"regex"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// When corresponds to the JSON schema field "when".
	When *ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemWhen `json:"when,omitempty"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemChannelModel struct {
	// ChannelID corresponds to the JSON schema field "channelId".
	ChannelID int `json:"channelId"`

	// ModelID corresponds to the JSON schema field "modelId".
	ModelID string `json:"modelId"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemChannelRegex struct {
	// ChannelID corresponds to the JSON schema field "channelId".
	ChannelID int `json:"channelId"`

	// Pattern corresponds to the JSON schema field "pattern".
	Pattern string `json:"pattern"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemChannelTagsModel struct {
	// ChannelTags corresponds to the JSON schema field "channelTags".
	ChannelTags []string `json:"channelTags"`

	// ModelID corresponds to the JSON schema field "modelId".
	ModelID string `json:"modelId"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemChannelTagsRegex struct {
	// ChannelTags corresponds to the JSON schema field "channelTags".
	ChannelTags []string `json:"channelTags"`

	// Pattern corresponds to the JSON schema field "pattern".
	Pattern string `json:"pattern"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemModelID struct {
	// Exclude corresponds to the JSON schema field "exclude".
	Exclude []*ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemModelIDExcludeElem `json:"exclude"`

	// ModelID corresponds to the JSON schema field "modelId".
	ModelID string `json:"modelId"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemModelIDExcludeElem struct {
	// ChannelIds corresponds to the JSON schema field "channelIds".
	ChannelIds []int `json:"channelIds"`

	// ChannelNamePattern corresponds to the JSON schema field "channelNamePattern".
	ChannelNamePattern string `json:"channelNamePattern"`

	// ChannelTags corresponds to the JSON schema field "channelTags".
	ChannelTags []string `json:"channelTags"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemRegex struct {
	// Exclude corresponds to the JSON schema field "exclude".
	Exclude []*ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemRegexExcludeElem `json:"exclude"`

	// Pattern corresponds to the JSON schema field "pattern".
	Pattern string `json:"pattern"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemRegexExcludeElem struct {
	// ChannelIds corresponds to the JSON schema field "channelIds".
	ChannelIds []int `json:"channelIds"`

	// ChannelNamePattern corresponds to the JSON schema field "channelNamePattern".
	ChannelNamePattern string `json:"channelNamePattern"`

	// ChannelTags corresponds to the JSON schema field "channelTags".
	ChannelTags []string `json:"channelTags"`
}

type ConfigurationDataModelSettingsDeveloperSettingsElemAssociationsElemWhen struct {
	// Condition corresponds to the JSON schema field "condition".
	Condition *Condition `json:"condition,omitempty"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled"`
}

type ConfigurationDataRegistration struct {
	// AllowRequestDetails corresponds to the JSON schema field "allowRequestDetails".
	AllowRequestDetails bool `json:"allowRequestDetails"`

	// AutoJoinFirstProject corresponds to the JSON schema field
	// "autoJoinFirstProject".
	AutoJoinFirstProject bool `json:"autoJoinFirstProject"`

	// DefaultProjectID corresponds to the JSON schema field "defaultProjectId".
	DefaultProjectID int `json:"defaultProjectId"`

	// DefaultProjectScopes corresponds to the JSON schema field
	// "defaultProjectScopes".
	DefaultProjectScopes []string `json:"defaultProjectScopes"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled"`

	// InviteCode corresponds to the JSON schema field "inviteCode".
	InviteCode Credential `json:"inviteCode"`

	// OidcEnabled corresponds to the JSON schema field "oidcEnabled".
	OidcEnabled bool `json:"oidcEnabled"`

	// SelfServiceEnabled corresponds to the JSON schema field "selfServiceEnabled".
	SelfServiceEnabled bool `json:"selfServiceEnabled"`
}

type ConfigurationDataRetryPolicy struct {
	// AutoDisableChannel corresponds to the JSON schema field "auto_disable_channel".
	AutoDisableChannel ConfigurationDataRetryPolicyAutoDisableChannel `json:"auto_disable_channel"`

	// EmptyResponseDetection corresponds to the JSON schema field
	// "empty_response_detection".
	EmptyResponseDetection bool `json:"empty_response_detection"`

	// EmptyResponseTextPatterns corresponds to the JSON schema field
	// "empty_response_text_patterns".
	EmptyResponseTextPatterns []string `json:"empty_response_text_patterns"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled"`

	// LoadBalancerStrategy corresponds to the JSON schema field
	// "load_balancer_strategy".
	LoadBalancerStrategy string `json:"load_balancer_strategy"`

	// MaxChannelRetries corresponds to the JSON schema field "max_channel_retries".
	MaxChannelRetries int `json:"max_channel_retries"`

	// MaxSingleChannelRetries corresponds to the JSON schema field
	// "max_single_channel_retries".
	MaxSingleChannelRetries int `json:"max_single_channel_retries"`

	// NonStreamResponseTimeoutSeconds corresponds to the JSON schema field
	// "non_stream_response_timeout_seconds".
	NonStreamResponseTimeoutSeconds int `json:"non_stream_response_timeout_seconds"`

	// RetryDelayMs corresponds to the JSON schema field "retry_delay_ms".
	RetryDelayMs int `json:"retry_delay_ms"`

	// StreamFirstEventTimeoutSeconds corresponds to the JSON schema field
	// "stream_first_event_timeout_seconds".
	StreamFirstEventTimeoutSeconds int `json:"stream_first_event_timeout_seconds"`

	// UpstreamErrorPolicy corresponds to the JSON schema field
	// "upstream_error_policy".
	UpstreamErrorPolicy ConfigurationDataRetryPolicyUpstreamErrorPolicy `json:"upstream_error_policy"`
}

type ConfigurationDataRetryPolicyAutoDisableChannel struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled"`

	// Statuses corresponds to the JSON schema field "statuses".
	Statuses []ConfigurationDataRetryPolicyAutoDisableChannelStatusesElem `json:"statuses"`
}

type ConfigurationDataRetryPolicyAutoDisableChannelStatusesElem struct {
	// Status corresponds to the JSON schema field "status".
	Status int `json:"status"`

	// Times corresponds to the JSON schema field "times".
	Times int `json:"times"`
}

type ConfigurationDataRetryPolicyUpstreamErrorPolicy struct {
	// CustomMessage corresponds to the JSON schema field "custom_message".
	CustomMessage string `json:"custom_message"`

	// Mode corresponds to the JSON schema field "mode".
	Mode string `json:"mode"`
}

type ConfigurationDataStoragePolicy struct {
	// CleanupOptions corresponds to the JSON schema field "cleanup_options".
	CleanupOptions []ConfigurationDataStoragePolicyCleanupOptionsElem `json:"cleanup_options"`

	// LivePreview corresponds to the JSON schema field "live_preview".
	LivePreview bool `json:"live_preview"`

	// StoreChunks corresponds to the JSON schema field "store_chunks".
	StoreChunks bool `json:"store_chunks"`

	// StoreRequestBody corresponds to the JSON schema field "store_request_body".
	StoreRequestBody bool `json:"store_request_body"`

	// StoreResponseBody corresponds to the JSON schema field "store_response_body".
	StoreResponseBody bool `json:"store_response_body"`
}

type ConfigurationDataStoragePolicyCleanupOptionsElem struct {
	// CleanupDays corresponds to the JSON schema field "cleanup_days".
	CleanupDays int `json:"cleanup_days"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled"`

	// ResourceType corresponds to the JSON schema field "resource_type".
	ResourceType string `json:"resource_type"`
}

type ConfigurationSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status ConfigurationSectionStatus `json:"status"`
}

type ConfigurationSectionStatus string

const ConfigurationSectionStatusAvailable ConfigurationSectionStatus = "available"
const ConfigurationSectionStatusNotRequested ConfigurationSectionStatus = "notRequested"
const ConfigurationSectionStatusPartial ConfigurationSectionStatus = "partial"
const ConfigurationSectionStatusUnavailable ConfigurationSectionStatus = "unavailable"

type ContractRequest struct {
	// Major corresponds to the JSON schema field "major".
	Major int `json:"major"`

	// MaxMinor corresponds to the JSON schema field "maxMinor".
	MaxMinor int `json:"maxMinor"`

	// MinMinor corresponds to the JSON schema field "minMinor".
	MinMinor int `json:"minMinor"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type ContractResponse struct {
	// Major corresponds to the JSON schema field "major".
	Major int `json:"major"`

	// Minor corresponds to the JSON schema field "minor".
	Minor int `json:"minor"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// SchemaSha256 corresponds to the JSON schema field "schemaSha256".
	SchemaSha256 string `json:"schemaSha256"`
}

type Counts struct {
	// AccessGroups corresponds to the JSON schema field "accessGroups".
	AccessGroups int `json:"accessGroups"`

	// APIKeys corresponds to the JSON schema field "apiKeys".
	APIKeys int `json:"apiKeys"`

	// Channels corresponds to the JSON schema field "channels".
	Channels int `json:"channels"`

	// Executions corresponds to the JSON schema field "executions".
	Executions int `json:"executions"`

	// Requests corresponds to the JSON schema field "requests".
	Requests int `json:"requests"`

	// Threads corresponds to the JSON schema field "threads".
	Threads int `json:"threads"`

	// Traces corresponds to the JSON schema field "traces".
	Traces int `json:"traces"`

	// Usage corresponds to the JSON schema field "usage".
	Usage int `json:"usage"`
}

type Credential struct {
	// Reason corresponds to the JSON schema field "reason".
	Reason *string `json:"reason,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status CredentialStatus `json:"status"`

	// Value corresponds to the JSON schema field "value".
	Value interface{} `json:"value,omitempty"`
}

type CredentialStatus string

const CredentialStatusExcluded CredentialStatus = "excluded"
const CredentialStatusIncluded CredentialStatus = "included"
const CredentialStatusNotApplicable CredentialStatus = "notApplicable"
const CredentialStatusUnavailable CredentialStatus = "unavailable"

type ErrorDetail struct {
	// Code corresponds to the JSON schema field "code".
	Code string `json:"code"`

	// CorrelationID corresponds to the JSON schema field "correlationId".
	CorrelationID string `json:"correlationId"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Retryable corresponds to the JSON schema field "retryable".
	Retryable bool `json:"retryable"`

	// Supported corresponds to the JSON schema field "supported".
	Supported []SupportedRange `json:"supported,omitempty"`
}

type ErrorResponse struct {
	// Contract corresponds to the JSON schema field "contract".
	Contract ContractResponse `json:"contract"`

	// Error corresponds to the JSON schema field "error".
	Error ErrorDetail `json:"error"`
}

type Evidence struct {
	// ByteLength corresponds to the JSON schema field "byteLength".
	ByteLength *int `json:"byteLength,omitempty"`

	// CanonicalSha256 corresponds to the JSON schema field "canonicalSha256".
	CanonicalSha256 *string `json:"canonicalSha256,omitempty"`

	// Canonicalization corresponds to the JSON schema field "canonicalization".
	Canonicalization *string `json:"canonicalization,omitempty"`

	// CanonicalizationReason corresponds to the JSON schema field
	// "canonicalizationReason".
	CanonicalizationReason *string `json:"canonicalizationReason,omitempty"`

	// CanonicalizationStatus corresponds to the JSON schema field
	// "canonicalizationStatus".
	CanonicalizationStatus *EvidenceCanonicalizationStatus `json:"canonicalizationStatus,omitempty"`

	// Encoding corresponds to the JSON schema field "encoding".
	Encoding *EvidenceEncoding `json:"encoding,omitempty"`

	// MediaType corresponds to the JSON schema field "mediaType".
	MediaType string `json:"mediaType"`

	// RawSha256 corresponds to the JSON schema field "rawSha256".
	RawSha256 *string `json:"rawSha256,omitempty"`

	// Reason corresponds to the JSON schema field "reason".
	Reason *string `json:"reason,omitempty"`

	// Sha256 corresponds to the JSON schema field "sha256".
	Sha256 *string `json:"sha256,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source EvidenceSource `json:"source"`

	// State corresponds to the JSON schema field "state".
	State EvidenceState `json:"state"`

	// Value corresponds to the JSON schema field "value".
	Value json.RawMessage `json:"value,omitempty"`
}

type EvidenceCanonicalizationStatus string

const EvidenceCanonicalizationStatusAvailable EvidenceCanonicalizationStatus = "available"
const EvidenceCanonicalizationStatusUnavailable EvidenceCanonicalizationStatus = "unavailable"

type EvidenceEncoding string

const EvidenceEncodingBase64 EvidenceEncoding = "base64"
const EvidenceEncodingJson EvidenceEncoding = "json"

type EvidenceSource string

const EvidenceSourceDatabase EvidenceSource = "database"
const EvidenceSourceExternal EvidenceSource = "external"
const EvidenceSourceLive EvidenceSource = "live"
const EvidenceSourceNone EvidenceSource = "none"
const EvidenceSourceUnknown EvidenceSource = "unknown"

type EvidenceState string

const EvidenceStateAvailable EvidenceState = "available"
const EvidenceStateExpired EvidenceState = "expired"
const EvidenceStateLegacyUnknown EvidenceState = "legacyUnknown"
const EvidenceStateNotApplicable EvidenceState = "notApplicable"
const EvidenceStateNotPersisted EvidenceState = "notPersisted"
const EvidenceStateStorageUnavailable EvidenceState = "storageUnavailable"

type ExecutionsData []struct {
	// ChannelID corresponds to the JSON schema field "channelId".
	ChannelID ExecutionsDataElemChannelID `json:"channelId"`

	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// DataStorageID corresponds to the JSON schema field "dataStorageId".
	DataStorageID ExecutionsDataElemDataStorageID `json:"dataStorageId"`

	// ErrorMessage corresponds to the JSON schema field "errorMessage".
	ErrorMessage string `json:"errorMessage"`

	// ExternalID corresponds to the JSON schema field "externalId".
	ExternalID string `json:"externalId"`

	// Format corresponds to the JSON schema field "format".
	Format string `json:"format"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// MetricsFirstTokenLatencyMs corresponds to the JSON schema field
	// "metricsFirstTokenLatencyMs".
	MetricsFirstTokenLatencyMs ExecutionsDataElemMetricsFirstTokenLatencyMs `json:"metricsFirstTokenLatencyMs"`

	// MetricsLatencyMs corresponds to the JSON schema field "metricsLatencyMs".
	MetricsLatencyMs ExecutionsDataElemMetricsLatencyMs `json:"metricsLatencyMs"`

	// MetricsReasoningDurationMs corresponds to the JSON schema field
	// "metricsReasoningDurationMs".
	MetricsReasoningDurationMs ExecutionsDataElemMetricsReasoningDurationMs `json:"metricsReasoningDurationMs"`

	// ModelID corresponds to the JSON schema field "modelId".
	ModelID string `json:"modelId"`

	// PassThroughApplied corresponds to the JSON schema field "passThroughApplied".
	PassThroughApplied bool `json:"passThroughApplied"`

	// ProjectID corresponds to the JSON schema field "projectId".
	ProjectID int `json:"projectId"`

	// RequestBody corresponds to the JSON schema field "requestBody".
	RequestBody Evidence `json:"requestBody"`

	// RequestHeaders corresponds to the JSON schema field "requestHeaders".
	RequestHeaders Evidence `json:"requestHeaders"`

	// RequestID corresponds to the JSON schema field "requestId".
	RequestID int `json:"requestId"`

	// RequestURL corresponds to the JSON schema field "requestUrl".
	RequestURL string `json:"requestUrl"`

	// ResponseBody corresponds to the JSON schema field "responseBody".
	ResponseBody Evidence `json:"responseBody"`

	// ResponseChunks corresponds to the JSON schema field "responseChunks".
	ResponseChunks Evidence `json:"responseChunks"`

	// ResponseStatusCode corresponds to the JSON schema field "responseStatusCode".
	ResponseStatusCode ExecutionsDataElemResponseStatusCode `json:"responseStatusCode"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`

	// Stream corresponds to the JSON schema field "stream".
	Stream bool `json:"stream"`

	// UpdatedAt corresponds to the JSON schema field "updatedAt".
	UpdatedAt string `json:"updatedAt"`
}

type ExecutionsDataElemChannelID *int

type ExecutionsDataElemDataStorageID *int

type ExecutionsDataElemMetricsFirstTokenLatencyMs *int

type ExecutionsDataElemMetricsLatencyMs *int

type ExecutionsDataElemMetricsReasoningDurationMs *int

type ExecutionsDataElemResponseStatusCode *int

type ExecutionsSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status ExecutionsSectionStatus `json:"status"`
}

type ExecutionsSectionStatus string

const ExecutionsSectionStatusAvailable ExecutionsSectionStatus = "available"
const ExecutionsSectionStatusNotRequested ExecutionsSectionStatus = "notRequested"
const ExecutionsSectionStatusPartial ExecutionsSectionStatus = "partial"
const ExecutionsSectionStatusUnavailable ExecutionsSectionStatus = "unavailable"

type HealthData struct {
	// BuildTime corresponds to the JSON schema field "buildTime".
	BuildTime HealthDataBuildTime `json:"buildTime"`

	// Commit corresponds to the JSON schema field "commit".
	Commit string `json:"commit"`

	// DatabaseLatencyMs corresponds to the JSON schema field "databaseLatencyMs".
	DatabaseLatencyMs HealthDataDatabaseLatencyMs `json:"databaseLatencyMs"`

	// DatabaseStatus corresponds to the JSON schema field "databaseStatus".
	DatabaseStatus string `json:"databaseStatus"`

	// ProcessStatus corresponds to the JSON schema field "processStatus".
	ProcessStatus string `json:"processStatus"`

	// UptimeSeconds corresponds to the JSON schema field "uptimeSeconds".
	UptimeSeconds int `json:"uptimeSeconds"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version"`
}

type HealthDataBuildTime *string

type HealthDataDatabaseLatencyMs *int

type HealthSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status HealthSectionStatus `json:"status"`
}

type HealthSectionStatus string

const HealthSectionStatusAvailable HealthSectionStatus = "available"
const HealthSectionStatusNotRequested HealthSectionStatus = "notRequested"
const HealthSectionStatusPartial HealthSectionStatus = "partial"
const HealthSectionStatusUnavailable HealthSectionStatus = "unavailable"

type Include struct {
	// Credentials corresponds to the JSON schema field "credentials".
	Credentials bool `json:"credentials,omitempty"`

	// Sections corresponds to the JSON schema field "sections".
	Sections []IncludeSectionsElem `json:"sections"`
}

type IncludeSectionsElem string

const IncludeSectionsElemAPIKeys IncludeSectionsElem = "apiKeys"
const IncludeSectionsElemAccessGroups IncludeSectionsElem = "accessGroups"
const IncludeSectionsElemChannels IncludeSectionsElem = "channels"
const IncludeSectionsElemConfiguration IncludeSectionsElem = "configuration"
const IncludeSectionsElemExecutions IncludeSectionsElem = "executions"
const IncludeSectionsElemHealth IncludeSectionsElem = "health"
const IncludeSectionsElemRequests IncludeSectionsElem = "requests"
const IncludeSectionsElemThreads IncludeSectionsElem = "threads"
const IncludeSectionsElemTraces IncludeSectionsElem = "traces"
const IncludeSectionsElemUsage IncludeSectionsElem = "usage"

type Issue struct {
	// Code corresponds to the JSON schema field "code".
	Code string `json:"code"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// RecordID corresponds to the JSON schema field "recordId".
	RecordID *string `json:"recordId,omitempty"`

	// RecordType corresponds to the JSON schema field "recordType".
	RecordType *string `json:"recordType,omitempty"`

	// Retryable corresponds to the JSON schema field "retryable".
	Retryable bool `json:"retryable"`

	// Section corresponds to the JSON schema field "section".
	Section *string `json:"section,omitempty"`
}

type Limits struct {
	// MaxExecutions corresponds to the JSON schema field "maxExecutions".
	MaxExecutions int `json:"maxExecutions,omitempty"`

	// MaxRelatedRecords corresponds to the JSON schema field "maxRelatedRecords".
	MaxRelatedRecords int `json:"maxRelatedRecords,omitempty"`

	// MaxRequests corresponds to the JSON schema field "maxRequests".
	MaxRequests int `json:"maxRequests,omitempty"`

	// MaxResponseBytes corresponds to the JSON schema field "maxResponseBytes".
	MaxResponseBytes int `json:"maxResponseBytes,omitempty"`
}

type Page struct {
	// Cursor corresponds to the JSON schema field "cursor".
	Cursor PageCursor `json:"cursor,omitempty"`
}

type PageCursor *string

type PullRequest struct {
	// Contract corresponds to the JSON schema field "contract".
	Contract ContractRequest `json:"contract"`

	// Include corresponds to the JSON schema field "include".
	Include Include `json:"include"`

	// Limits corresponds to the JSON schema field "limits".
	Limits *Limits `json:"limits,omitempty"`

	// Page corresponds to the JSON schema field "page".
	Page *Page `json:"page,omitempty"`

	// Scope corresponds to the JSON schema field "scope".
	Scope Scope `json:"scope"`

	// Selector corresponds to the JSON schema field "selector".
	Selector Selector `json:"selector"`
}

type PullResponse struct {
	// Authorization corresponds to the JSON schema field "authorization".
	Authorization Authorization `json:"authorization"`

	// Bundle corresponds to the JSON schema field "bundle".
	Bundle Bundle `json:"bundle"`

	// Contract corresponds to the JSON schema field "contract".
	Contract ContractResponse `json:"contract"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Sections corresponds to the JSON schema field "sections".
	Sections Sections `json:"sections"`

	// Selection corresponds to the JSON schema field "selection".
	Selection Selection `json:"selection"`

	// Server corresponds to the JSON schema field "server".
	Server ServerInfo `json:"server"`
}

type RequestRef struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind RequestRefKind `json:"kind"`

	// MatchedRequestIds corresponds to the JSON schema field "matchedRequestIds".
	MatchedRequestIds []int `json:"matchedRequestIds,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status RequestRefStatus `json:"status"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type RequestRefKind string

const RequestRefKindExternalID RequestRefKind = "externalId"
const RequestRefKindRequestID RequestRefKind = "requestId"
const RequestRefKindThreadID RequestRefKind = "threadId"
const RequestRefKindTraceID RequestRefKind = "traceId"

type RequestRefStatus string

const RequestRefStatusMatched RequestRefStatus = "matched"
const RequestRefStatusNotFoundOrNotAuthorized RequestRefStatus = "notFoundOrNotAuthorized"

type RequestsData []struct {
	// APIKeyID corresponds to the JSON schema field "apiKeyId".
	APIKeyID RequestsDataElemAPIKeyID `json:"apiKeyId"`

	// ChannelID corresponds to the JSON schema field "channelId".
	ChannelID RequestsDataElemChannelID `json:"channelId"`

	// ClientIp corresponds to the JSON schema field "clientIp".
	ClientIp string `json:"clientIp"`

	// ContentArtifact corresponds to the JSON schema field "contentArtifact".
	ContentArtifact RequestsDataElemContentArtifact `json:"contentArtifact"`

	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// DataStorageID corresponds to the JSON schema field "dataStorageId".
	DataStorageID RequestsDataElemDataStorageID `json:"dataStorageId"`

	// ExternalID corresponds to the JSON schema field "externalId".
	ExternalID string `json:"externalId"`

	// Format corresponds to the JSON schema field "format".
	Format string `json:"format"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// MetricsFirstTokenLatencyMs corresponds to the JSON schema field
	// "metricsFirstTokenLatencyMs".
	MetricsFirstTokenLatencyMs RequestsDataElemMetricsFirstTokenLatencyMs `json:"metricsFirstTokenLatencyMs"`

	// MetricsLatencyMs corresponds to the JSON schema field "metricsLatencyMs".
	MetricsLatencyMs RequestsDataElemMetricsLatencyMs `json:"metricsLatencyMs"`

	// MetricsReasoningDurationMs corresponds to the JSON schema field
	// "metricsReasoningDurationMs".
	MetricsReasoningDurationMs RequestsDataElemMetricsReasoningDurationMs `json:"metricsReasoningDurationMs"`

	// ModelID corresponds to the JSON schema field "modelId".
	ModelID string `json:"modelId"`

	// ProjectID corresponds to the JSON schema field "projectId".
	ProjectID int `json:"projectId"`

	// ReasoningEffort corresponds to the JSON schema field "reasoningEffort".
	ReasoningEffort string `json:"reasoningEffort"`

	// RequestBody corresponds to the JSON schema field "requestBody".
	RequestBody Evidence `json:"requestBody"`

	// RequestHeaders corresponds to the JSON schema field "requestHeaders".
	RequestHeaders Evidence `json:"requestHeaders"`

	// ResponseBody corresponds to the JSON schema field "responseBody".
	ResponseBody Evidence `json:"responseBody"`

	// ResponseChunks corresponds to the JSON schema field "responseChunks".
	ResponseChunks Evidence `json:"responseChunks"`

	// RoutingContext corresponds to the JSON schema field "routingContext".
	RoutingContext RequestsDataElemRoutingContext `json:"routingContext"`

	// Source corresponds to the JSON schema field "source".
	Source string `json:"source"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`

	// Stream corresponds to the JSON schema field "stream".
	Stream bool `json:"stream"`

	// TraceDatabaseID corresponds to the JSON schema field "traceDatabaseId".
	TraceDatabaseID RequestsDataElemTraceDatabaseID `json:"traceDatabaseId"`

	// UpdatedAt corresponds to the JSON schema field "updatedAt".
	UpdatedAt string `json:"updatedAt"`
}

type RequestsDataElemAPIKeyID *int

type RequestsDataElemChannelID *int

type RequestsDataElemContentArtifact struct {
	// Content corresponds to the JSON schema field "content".
	Content Evidence `json:"content"`

	// Key corresponds to the JSON schema field "key".
	Key RequestsDataElemContentArtifactKey `json:"key"`

	// Saved corresponds to the JSON schema field "saved".
	Saved bool `json:"saved"`

	// SavedAt corresponds to the JSON schema field "savedAt".
	SavedAt RequestsDataElemContentArtifactSavedAt `json:"savedAt"`

	// StorageID corresponds to the JSON schema field "storageId".
	StorageID RequestsDataElemContentArtifactStorageID `json:"storageId"`
}

type RequestsDataElemContentArtifactKey *string

type RequestsDataElemContentArtifactSavedAt *string

type RequestsDataElemContentArtifactStorageID *int

type RequestsDataElemDataStorageID *int

type RequestsDataElemMetricsFirstTokenLatencyMs *int

type RequestsDataElemMetricsLatencyMs *int

type RequestsDataElemMetricsReasoningDurationMs *int

type RequestsDataElemRoutingContext struct {
	// State corresponds to the JSON schema field "state".
	State string `json:"state"`

	// Value corresponds to the JSON schema field "value".
	Value *RequestsDataElemRoutingContextValue `json:"value"`
}

type RequestsDataElemRoutingContextValue struct {
	// AccessGroupID corresponds to the JSON schema field "accessGroupId".
	AccessGroupID RequestsDataElemRoutingContextValueAccessGroupID `json:"accessGroupId"`

	// AccessGroupRevision corresponds to the JSON schema field "accessGroupRevision".
	AccessGroupRevision RequestsDataElemRoutingContextValueAccessGroupRevision `json:"accessGroupRevision"`

	// APIKeyID corresponds to the JSON schema field "apiKeyId".
	APIKeyID int `json:"apiKeyId"`

	// APIKeyType corresponds to the JSON schema field "apiKeyType".
	APIKeyType string `json:"apiKeyType"`

	// EffectiveProfiles corresponds to the JSON schema field "effectiveProfiles".
	EffectiveProfiles *RequestsDataElemRoutingContextValueEffectiveProfiles `json:"effectiveProfiles"`

	// EffectiveProfilesSha256 corresponds to the JSON schema field
	// "effectiveProfilesSha256".
	EffectiveProfilesSha256 string `json:"effectiveProfilesSha256"`

	// ProfileMode corresponds to the JSON schema field "profileMode".
	ProfileMode string `json:"profileMode"`

	// ProvisioningSource corresponds to the JSON schema field "provisioningSource".
	ProvisioningSource string `json:"provisioningSource"`

	// RequestedModelID corresponds to the JSON schema field "requestedModelId".
	RequestedModelID string `json:"requestedModelId"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version"`
}

type RequestsDataElemRoutingContextValueAccessGroupID *int

type RequestsDataElemRoutingContextValueAccessGroupRevision *int

type RequestsDataElemRoutingContextValueEffectiveProfiles struct {
	// ActiveProfile corresponds to the JSON schema field "activeProfile".
	ActiveProfile string `json:"activeProfile"`

	// Profiles corresponds to the JSON schema field "profiles".
	Profiles []RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElem `json:"profiles"`
}

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElem struct {
	// ChannelIDs corresponds to the JSON schema field "channelIDs".
	ChannelIDs []int `json:"channelIDs,omitempty"`

	// ChannelTags corresponds to the JSON schema field "channelTags".
	ChannelTags []string `json:"channelTags,omitempty"`

	// ChannelTagsMatchMode corresponds to the JSON schema field
	// "channelTagsMatchMode".
	ChannelTagsMatchMode *string `json:"channelTagsMatchMode,omitempty"`

	// LoadBalanceStrategy corresponds to the JSON schema field "loadBalanceStrategy".
	LoadBalanceStrategy RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemLoadBalanceStrategy `json:"loadBalanceStrategy,omitempty"`

	// ModelIDs corresponds to the JSON schema field "modelIDs".
	ModelIDs []string `json:"modelIDs,omitempty"`

	// ModelMappings corresponds to the JSON schema field "modelMappings".
	ModelMappings []RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemModelMappingsElem `json:"modelMappings"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Quota corresponds to the JSON schema field "quota".
	Quota *RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuota `json:"quota,omitempty"`
}

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemLoadBalanceStrategy *string

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemModelMappingsElem struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// To corresponds to the JSON schema field "to".
	To string `json:"to"`
}

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuota struct {
	// Cost corresponds to the JSON schema field "cost".
	Cost *RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaCost `json:"cost,omitempty"`

	// Period corresponds to the JSON schema field "period".
	Period RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaPeriod `json:"period"`

	// Requests corresponds to the JSON schema field "requests".
	Requests RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaRequests `json:"requests,omitempty"`

	// TotalTokens corresponds to the JSON schema field "totalTokens".
	TotalTokens RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaTotalTokens `json:"totalTokens,omitempty"`
}

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaCost map[string]interface{}

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaPeriod struct {
	// CalendarDuration corresponds to the JSON schema field "calendarDuration".
	CalendarDuration *RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaPeriodCalendarDuration `json:"calendarDuration,omitempty"`

	// PastDuration corresponds to the JSON schema field "pastDuration".
	PastDuration *RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaPeriodPastDuration `json:"pastDuration,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaPeriodCalendarDuration struct {
	// Unit corresponds to the JSON schema field "unit".
	Unit string `json:"unit"`
}

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaPeriodPastDuration struct {
	// Unit corresponds to the JSON schema field "unit".
	Unit string `json:"unit"`

	// Value corresponds to the JSON schema field "value".
	Value int `json:"value"`
}

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaRequests *int

type RequestsDataElemRoutingContextValueEffectiveProfilesProfilesElemQuotaTotalTokens *int

type RequestsDataElemTraceDatabaseID *int

type RequestsSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status RequestsSectionStatus `json:"status"`
}

type RequestsSectionStatus string

const RequestsSectionStatusAvailable RequestsSectionStatus = "available"
const RequestsSectionStatusNotRequested RequestsSectionStatus = "notRequested"
const RequestsSectionStatusPartial RequestsSectionStatus = "partial"
const RequestsSectionStatusUnavailable RequestsSectionStatus = "unavailable"

type Scope struct {
	// ProjectID corresponds to the JSON schema field "projectId".
	ProjectID int `json:"projectId"`

	// SubjectUserID corresponds to the JSON schema field "subjectUserId".
	SubjectUserID *int `json:"subjectUserId,omitempty"`
}

type Sections struct {
	// AccessGroups corresponds to the JSON schema field "accessGroups".
	AccessGroups AccessGroupsSection `json:"accessGroups"`

	// APIKeys corresponds to the JSON schema field "apiKeys".
	APIKeys APIKeysSection `json:"apiKeys"`

	// Channels corresponds to the JSON schema field "channels".
	Channels ChannelsSection `json:"channels"`

	// Configuration corresponds to the JSON schema field "configuration".
	Configuration ConfigurationSection `json:"configuration"`

	// Executions corresponds to the JSON schema field "executions".
	Executions ExecutionsSection `json:"executions"`

	// Health corresponds to the JSON schema field "health".
	Health HealthSection `json:"health"`

	// Requests corresponds to the JSON schema field "requests".
	Requests RequestsSection `json:"requests"`

	// Threads corresponds to the JSON schema field "threads".
	Threads ThreadsSection `json:"threads"`

	// Traces corresponds to the JSON schema field "traces".
	Traces TracesSection `json:"traces"`

	// Usage corresponds to the JSON schema field "usage".
	Usage UsageSection `json:"usage"`
}

type Selection struct {
	// AsOf corresponds to the JSON schema field "asOf".
	AsOf time.Time `json:"asOf"`

	// Counts corresponds to the JSON schema field "counts".
	Counts Counts `json:"counts"`

	// HasMore corresponds to the JSON schema field "hasMore".
	HasMore bool `json:"hasMore"`

	// NextCursor corresponds to the JSON schema field "nextCursor".
	NextCursor SelectionNextCursor `json:"nextCursor"`

	// Order corresponds to the JSON schema field "order".
	Order string `json:"order"`

	// RequestRefs corresponds to the JSON schema field "requestRefs".
	RequestRefs []RequestRef `json:"requestRefs"`

	// Selector corresponds to the JSON schema field "selector".
	Selector Selector `json:"selector"`
}

type SelectionNextCursor *string

type Selector interface{}

type ServerInfo struct {
	// BuildTime corresponds to the JSON schema field "buildTime".
	BuildTime ServerInfoBuildTime `json:"buildTime"`

	// Commit corresponds to the JSON schema field "commit".
	Commit string `json:"commit"`

	// UptimeSeconds corresponds to the JSON schema field "uptimeSeconds".
	UptimeSeconds int `json:"uptimeSeconds"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version"`
}

type ServerInfoBuildTime *time.Time

type SupportedRange struct {
	// Major corresponds to the JSON schema field "major".
	Major int `json:"major"`

	// MaxMinor corresponds to the JSON schema field "maxMinor".
	MaxMinor int `json:"maxMinor"`

	// MinMinor corresponds to the JSON schema field "minMinor".
	MinMinor int `json:"minMinor"`
}

type ThreadsData []struct {
	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// ProjectID corresponds to the JSON schema field "projectId".
	ProjectID int `json:"projectId"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// UpdatedAt corresponds to the JSON schema field "updatedAt".
	UpdatedAt string `json:"updatedAt"`
}

type ThreadsSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status ThreadsSectionStatus `json:"status"`
}

type ThreadsSectionStatus string

const ThreadsSectionStatusAvailable ThreadsSectionStatus = "available"
const ThreadsSectionStatusNotRequested ThreadsSectionStatus = "notRequested"
const ThreadsSectionStatusPartial ThreadsSectionStatus = "partial"
const ThreadsSectionStatusUnavailable ThreadsSectionStatus = "unavailable"

type TracesData []struct {
	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// ProjectID corresponds to the JSON schema field "projectId".
	ProjectID int `json:"projectId"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`

	// ThreadDatabaseID corresponds to the JSON schema field "threadDatabaseId".
	ThreadDatabaseID TracesDataElemThreadDatabaseID `json:"threadDatabaseId"`

	// TraceID corresponds to the JSON schema field "traceId".
	TraceID string `json:"traceId"`

	// UpdatedAt corresponds to the JSON schema field "updatedAt".
	UpdatedAt string `json:"updatedAt"`
}

type TracesDataElemThreadDatabaseID *int

type TracesSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status TracesSectionStatus `json:"status"`
}

type TracesSectionStatus string

const TracesSectionStatusAvailable TracesSectionStatus = "available"
const TracesSectionStatusNotRequested TracesSectionStatus = "notRequested"
const TracesSectionStatusPartial TracesSectionStatus = "partial"
const TracesSectionStatusUnavailable TracesSectionStatus = "unavailable"

type UsageData []struct {
	// APIKeyID corresponds to the JSON schema field "apiKeyId".
	APIKeyID UsageDataElemAPIKeyID `json:"apiKeyId"`

	// ChannelID corresponds to the JSON schema field "channelId".
	ChannelID UsageDataElemChannelID `json:"channelId"`

	// CompletionAcceptedPredictionTokens corresponds to the JSON schema field
	// "completionAcceptedPredictionTokens".
	CompletionAcceptedPredictionTokens int `json:"completionAcceptedPredictionTokens"`

	// CompletionAudioTokens corresponds to the JSON schema field
	// "completionAudioTokens".
	CompletionAudioTokens int `json:"completionAudioTokens"`

	// CompletionReasoningTokens corresponds to the JSON schema field
	// "completionReasoningTokens".
	CompletionReasoningTokens int `json:"completionReasoningTokens"`

	// CompletionRejectedPredictionTokens corresponds to the JSON schema field
	// "completionRejectedPredictionTokens".
	CompletionRejectedPredictionTokens int `json:"completionRejectedPredictionTokens"`

	// CompletionTokens corresponds to the JSON schema field "completionTokens".
	CompletionTokens int `json:"completionTokens"`

	// CostItems corresponds to the JSON schema field "costItems".
	CostItems []UsageDataElemCostItemsElem `json:"costItems"`

	// CostPriceReferenceID corresponds to the JSON schema field
	// "costPriceReferenceId".
	CostPriceReferenceID string `json:"costPriceReferenceId"`

	// CreatedAt corresponds to the JSON schema field "createdAt".
	CreatedAt string `json:"createdAt"`

	// Format corresponds to the JSON schema field "format".
	Format string `json:"format"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// ModelID corresponds to the JSON schema field "modelId".
	ModelID string `json:"modelId"`

	// ProjectID corresponds to the JSON schema field "projectId".
	ProjectID int `json:"projectId"`

	// PromptAudioTokens corresponds to the JSON schema field "promptAudioTokens".
	PromptAudioTokens int `json:"promptAudioTokens"`

	// PromptCachedTokens corresponds to the JSON schema field "promptCachedTokens".
	PromptCachedTokens int `json:"promptCachedTokens"`

	// PromptTokens corresponds to the JSON schema field "promptTokens".
	PromptTokens int `json:"promptTokens"`

	// PromptWriteCachedTokens corresponds to the JSON schema field
	// "promptWriteCachedTokens".
	PromptWriteCachedTokens int `json:"promptWriteCachedTokens"`

	// PromptWriteCachedTokens1H corresponds to the JSON schema field
	// "promptWriteCachedTokens1h".
	PromptWriteCachedTokens1H int `json:"promptWriteCachedTokens1h"`

	// PromptWriteCachedTokens5M corresponds to the JSON schema field
	// "promptWriteCachedTokens5m".
	PromptWriteCachedTokens5M int `json:"promptWriteCachedTokens5m"`

	// RequestID corresponds to the JSON schema field "requestId".
	RequestID int `json:"requestId"`

	// Source corresponds to the JSON schema field "source".
	Source string `json:"source"`

	// TotalCost corresponds to the JSON schema field "totalCost".
	TotalCost UsageDataElemTotalCost `json:"totalCost"`

	// TotalTokens corresponds to the JSON schema field "totalTokens".
	TotalTokens int `json:"totalTokens"`

	// UpdatedAt corresponds to the JSON schema field "updatedAt".
	UpdatedAt string `json:"updatedAt"`
}

type UsageDataElemAPIKeyID *int

type UsageDataElemChannelID *int

type UsageDataElemCostItemsElem struct {
	// ItemCode corresponds to the JSON schema field "itemCode".
	ItemCode string `json:"itemCode"`

	// PromptWriteCacheVariantCode corresponds to the JSON schema field
	// "promptWriteCacheVariantCode".
	PromptWriteCacheVariantCode *string `json:"promptWriteCacheVariantCode,omitempty"`

	// Quantity corresponds to the JSON schema field "quantity".
	Quantity int `json:"quantity"`

	// Subtotal corresponds to the JSON schema field "subtotal".
	Subtotal UsageDataElemCostItemsElemSubtotal `json:"subtotal"`

	// TierBreakdown corresponds to the JSON schema field "tierBreakdown".
	TierBreakdown []UsageDataElemCostItemsElemTierBreakdownElem `json:"tierBreakdown,omitempty"`
}

type UsageDataElemCostItemsElemSubtotal map[string]interface{}

type UsageDataElemCostItemsElemTierBreakdownElem struct {
	// Subtotal corresponds to the JSON schema field "subtotal".
	Subtotal UsageDataElemCostItemsElemTierBreakdownElemSubtotal `json:"subtotal"`

	// Units corresponds to the JSON schema field "units".
	Units int `json:"units"`

	// UpTo corresponds to the JSON schema field "upTo".
	UpTo UsageDataElemCostItemsElemTierBreakdownElemUpTo `json:"upTo,omitempty"`
}

type UsageDataElemCostItemsElemTierBreakdownElemSubtotal map[string]interface{}

type UsageDataElemCostItemsElemTierBreakdownElemUpTo *int

type UsageDataElemTotalCost *string

type UsageSection struct {
	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data"`

	// Issues corresponds to the JSON schema field "issues".
	Issues []Issue `json:"issues"`

	// Status corresponds to the JSON schema field "status".
	Status UsageSectionStatus `json:"status"`
}

type UsageSectionStatus string

const UsageSectionStatusAvailable UsageSectionStatus = "available"
const UsageSectionStatusNotRequested UsageSectionStatus = "notRequested"
const UsageSectionStatusPartial UsageSectionStatus = "partial"
const UsageSectionStatusUnavailable UsageSectionStatus = "unavailable"
