#!/usr/bin/env bash

# Deterministic PostgreSQL 18 retention/TOAST cleanup-cycle smoke.
# This script always provisions its own disposable container and never accepts a
# database DSN, so it cannot accidentally target a production connection.

set -euo pipefail

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required for the PostgreSQL 18 retention smoke" >&2
  exit 2
fi

container="axonhub-retention-pg18-$$"
password="axonhub-retention-smoke"

cleanup() {
  docker rm -f "${container}" >/dev/null 2>&1 || true
}
trap cleanup EXIT

docker run --detach --rm \
  --name "${container}" \
  --env POSTGRES_PASSWORD="${password}" \
  --env POSTGRES_DB=retention_smoke \
  postgres:18-alpine >/dev/null

for _ in $(seq 1 60); do
  if docker exec "${container}" pg_isready -U postgres -d retention_smoke >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
docker exec "${container}" pg_isready -U postgres -d retention_smoke >/dev/null

psql_exec() {
  docker exec -i \
    --env PGPASSWORD="${password}" \
    "${container}" psql -v ON_ERROR_STOP=1 -X -q -U postgres -d retention_smoke "$@"
}

psql_exec <<'SQL'
DO $$
DECLARE version_num integer := current_setting('server_version_num')::integer;
BEGIN
  IF version_num < 180000 OR version_num >= 190000 THEN
    RAISE EXCEPTION 'PostgreSQL 18 required, server_version_num=%', version_num;
  END IF;
END $$;

CREATE FUNCTION smoke_payload(seed integer) RETURNS jsonb
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT jsonb_build_object(
    'seed', seed,
    'payload', string_agg(md5((seed::bigint * 100000 + g)::text), '')
  )
  FROM generate_series(1, 4096) AS g;
$$;

CREATE TABLE smoke_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'canceled')),
  payload jsonb NOT NULL
);
CREATE INDEX smoke_requests_by_created_at ON smoke_requests (created_at);

CREATE TABLE smoke_request_executions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint NOT NULL,
  created_at timestamptz NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'canceled')),
  payload jsonb NOT NULL
);
CREATE INDEX smoke_request_executions_by_created_at ON smoke_request_executions (created_at);

INSERT INTO smoke_requests (id, created_at, status, payload) VALUES
  (1, now() - interval '96 hours', 'completed', smoke_payload(1)),
  (2, now() - interval '96 hours', 'failed', smoke_payload(2)),
  (3, now() - interval '96 hours', 'canceled', smoke_payload(3)),
  (4, now() - interval '96 hours', 'pending', smoke_payload(4)),
  (5, now() - interval '24 hours', 'completed', smoke_payload(5)),
  (6, now() - interval '96 hours', 'completed', smoke_payload(6)),
  (7, now() - interval '96 hours', 'completed', smoke_payload(7));
SELECT setval(pg_get_serial_sequence('smoke_requests', 'id'), (SELECT max(id) FROM smoke_requests));

INSERT INTO smoke_request_executions (request_id, created_at, status, payload) VALUES
  (6, now() - interval '24 hours', 'completed', smoke_payload(106)),
  (7, now() - interval '96 hours', 'completed', smoke_payload(107));

DO $$
DECLARE toast_bytes bigint;
BEGIN
  SELECT pg_total_relation_size(c.reltoastrelid)
    INTO toast_bytes
    FROM pg_class AS c
   WHERE c.oid = 'smoke_requests'::regclass;
  IF toast_bytes <= 0 THEN
    RAISE EXCEPTION 'expected out-of-line TOAST storage, got % bytes', toast_bytes;
  END IF;
END $$;

-- Execution-before-request ordering. Only old terminal executions expire.
DELETE FROM smoke_request_executions
 WHERE created_at < now() - interval '72 hours'
   AND status IN ('completed', 'failed', 'canceled');

-- Requests are terminal and old, and are removed only after no execution remains.
DELETE FROM smoke_requests AS r
 WHERE r.created_at < now() - interval '72 hours'
   AND r.status IN ('completed', 'failed', 'canceled')
   AND NOT EXISTS (
     SELECT 1 FROM smoke_request_executions AS e WHERE e.request_id = r.id
   );

DO $$
DECLARE request_ids bigint[];
DECLARE execution_requests bigint[];
BEGIN
  SELECT array_agg(id ORDER BY id) INTO request_ids FROM smoke_requests;
  SELECT array_agg(request_id ORDER BY request_id) INTO execution_requests FROM smoke_request_executions;
  IF request_ids IS DISTINCT FROM ARRAY[4,5,6]::bigint[] THEN
    RAISE EXCEPTION 'recent/active/execution-protected requests were not preserved: %', request_ids;
  END IF;
  IF execution_requests IS DISTINCT FROM ARRAY[6]::bigint[] THEN
    RAISE EXCEPTION 'bounded execution expiry mismatch: %', execution_requests;
  END IF;
END $$;
SQL

# VACUUM must run outside a transaction. It makes the dead heap/TOAST pages
# reusable; the smoke deliberately does not expect the relation file to shrink.
psql_exec -c 'VACUUM (ANALYZE) smoke_request_executions;' \
          -c 'VACUUM (ANALYZE) smoke_requests;'

relation_size() {
  psql_exec -At -c "SELECT pg_total_relation_size('smoke_requests');" | tr -d '[:space:]'
}

cycle_size=()
for cycle in 1 2 3; do
  psql_exec -v cycle="${cycle}" <<'SQL'
INSERT INTO smoke_requests (created_at, status, payload)
SELECT now() - interval '96 hours', 'completed', smoke_payload(:'cycle'::integer * 1000 + g)
  FROM generate_series(1, 24) AS g;
DELETE FROM smoke_requests
 WHERE id > 7
   AND created_at < now() - interval '72 hours'
   AND status IN ('completed', 'failed', 'canceled');
SQL
  psql_exec -c 'VACUUM (ANALYZE) smoke_requests;'
  cycle_size+=("$(relation_size)")
done

first="${cycle_size[0]}"
last="${cycle_size[2]}"
tolerance=$(( first / 4 ))
if (( tolerance < 8388608 )); then
  tolerance=8388608
fi
if (( last > first + tolerance )); then
  echo "relation did not plateau through reuse cycles: first=${first}, last=${last}, tolerance=${tolerance}" >&2
  exit 1
fi

psql_exec <<'SQL'
DO $$
DECLARE request_ids bigint[];
BEGIN
  SELECT array_agg(id ORDER BY id) INTO request_ids FROM smoke_requests;
  IF request_ids IS DISTINCT FROM ARRAY[4,5,6]::bigint[] THEN
    RAISE EXCEPTION 'cleanup cycles changed protected rows: %', request_ids;
  END IF;
END $$;
SQL

printf 'PostgreSQL 18 retention smoke passed. relation bytes by reuse cycle: %s\n' "${cycle_size[*]}"
printf '%s\n' 'Interpretation: ordinary VACUUM reused heap/TOAST high-water space; it was not expected to return that high-water allocation to the OS.'
