// Code generated by ent, DO NOT EDIT.

package managedobservabilitystate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the managedobservabilitystate type in the database.
	Label = "managed_observability_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChargedBytes holds the string denoting the charged_bytes field in the database.
	FieldChargedBytes = "charged_bytes"
	// FieldUnderPressure holds the string denoting the under_pressure field in the database.
	FieldUnderPressure = "under_pressure"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the managedobservabilitystate in the database.
	Table = "managed_observability_states"
)

// Columns holds all SQL columns for managedobservabilitystate fields.
var Columns = []string{
	FieldID,
	FieldChargedBytes,
	FieldUnderPressure,
	FieldLastError,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultChargedBytes holds the default value on creation for the "charged_bytes" field.
	DefaultChargedBytes int64
	// ChargedBytesValidator is a validator for the "charged_bytes" field. It is called by the builders before save.
	ChargedBytesValidator func(int64) error
	// DefaultUnderPressure holds the default value on creation for the "under_pressure" field.
	DefaultUnderPressure bool
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID int
)

// OrderOption defines the ordering options for the ManagedObservabilityState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChargedBytes orders the results by the charged_bytes field.
func ByChargedBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChargedBytes, opts...).ToFunc()
}

// ByUnderPressure orders the results by the under_pressure field.
func ByUnderPressure(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnderPressure, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
