// Code generated by ent, DO NOT EDIT.

package managedobservabilitystate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldLTE(FieldID, id))
}

// ChargedBytes applies equality check predicate on the "charged_bytes" field. It's identical to ChargedBytesEQ.
func ChargedBytes(v int64) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldChargedBytes, v))
}

// UnderPressure applies equality check predicate on the "under_pressure" field. It's identical to UnderPressureEQ.
func UnderPressure(v bool) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldUnderPressure, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldLastError, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldUpdatedAt, v))
}

// ChargedBytesEQ applies the EQ predicate on the "charged_bytes" field.
func ChargedBytesEQ(v int64) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldChargedBytes, v))
}

// ChargedBytesNEQ applies the NEQ predicate on the "charged_bytes" field.
func ChargedBytesNEQ(v int64) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNEQ(FieldChargedBytes, v))
}

// ChargedBytesIn applies the In predicate on the "charged_bytes" field.
func ChargedBytesIn(vs ...int64) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldIn(FieldChargedBytes, vs...))
}

// ChargedBytesNotIn applies the NotIn predicate on the "charged_bytes" field.
func ChargedBytesNotIn(vs ...int64) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNotIn(FieldChargedBytes, vs...))
}

// ChargedBytesGT applies the GT predicate on the "charged_bytes" field.
func ChargedBytesGT(v int64) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldGT(FieldChargedBytes, v))
}

// ChargedBytesGTE applies the GTE predicate on the "charged_bytes" field.
func ChargedBytesGTE(v int64) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldGTE(FieldChargedBytes, v))
}

// ChargedBytesLT applies the LT predicate on the "charged_bytes" field.
func ChargedBytesLT(v int64) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldLT(FieldChargedBytes, v))
}

// ChargedBytesLTE applies the LTE predicate on the "charged_bytes" field.
func ChargedBytesLTE(v int64) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldLTE(FieldChargedBytes, v))
}

// UnderPressureEQ applies the EQ predicate on the "under_pressure" field.
func UnderPressureEQ(v bool) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldUnderPressure, v))
}

// UnderPressureNEQ applies the NEQ predicate on the "under_pressure" field.
func UnderPressureNEQ(v bool) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNEQ(FieldUnderPressure, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldContainsFold(FieldLastError, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ManagedObservabilityState) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ManagedObservabilityState) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ManagedObservabilityState) predicate.ManagedObservabilityState {
	return predicate.ManagedObservabilityState(sql.NotPredicates(p))
}
